"""Sections 7-12: window functions, modifying data, DDL, modeling, indexes, transactions."""
from schema import Q, S

SECTIONS = [
    S("Window Functions", "🪟", "Module 7", [
        Q("I", "What is a window function?",
          "A function that computes a value across a set of rows related to the current row (its \"window\") without collapsing rows like GROUP BY does. Syntax: `func() OVER (PARTITION BY ... ORDER BY ...)`.",
          "You keep every detail row *and* get group-level numbers next to it: each salary beside its department's average.",
          "SELECT name, dept_id, salary,\n       AVG(salary) OVER (PARTITION BY dept_id) AS dept_avg\nFROM employees WHERE dept_id IS NOT NULL ORDER BY dept_id, salary DESC;"),
        Q("I", "ROW_NUMBER vs RANK vs DENSE_RANK: what's the difference?",
          "All number rows in window order. `ROW_NUMBER` always gives 1, 2, 3, 4 (ties get arbitrary distinct numbers). `RANK` gives ties the same rank and then skips (1, 2, 2, 4). `DENSE_RANK` gives ties the same rank without gaps (1, 2, 2, 3).",
          "Priya and Karan both earn 95,000, which shows the difference nicely.",
          "SELECT name, salary,\n  ROW_NUMBER() OVER (ORDER BY salary DESC) AS row_num,\n  RANK()       OVER (ORDER BY salary DESC) AS rnk,\n  DENSE_RANK() OVER (ORDER BY salary DESC) AS dense\nFROM employees ORDER BY salary DESC LIMIT 5;"),
        Q("I", "What does PARTITION BY do?",
          "It splits the rows into independent groups for the window function, so numbering, ranking and totals restart for each partition. Without it, the whole result is one window.",
          "Think of it as GROUP BY for window functions, except the rows stay separate.",
          "SELECT dept_id, name, salary,\n       RANK() OVER (PARTITION BY dept_id ORDER BY salary DESC) AS rank_in_dept\nFROM employees WHERE dept_id IN (1, 2) ORDER BY dept_id, rank_in_dept;"),
        Q("A", "How do you get the top N rows per group?",
          "Rank rows within each group with `ROW_NUMBER()` (or `RANK()` to keep ties) in a CTE or subquery, then filter on the rank. Snowflake, BigQuery and Teradata also support `QUALIFY` to filter window results directly.",
          "One of the most common interview and real-world SQL patterns.",
          "WITH ranked AS (\n  SELECT category, name, price,\n         ROW_NUMBER() OVER (PARTITION BY category ORDER BY price DESC) AS rn\n  FROM products\n)\nSELECT category, name, price FROM ranked WHERE rn = 1 ORDER BY price DESC;"),
        Q("I", "How do you compute a running total?",
          "`SUM(x) OVER (ORDER BY date)` accumulates from the first row to the current one. Add `PARTITION BY` to restart per group (per customer, per month).",
          "The default frame with ORDER BY is `RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW`, so rows with equal order values are summed together. Use `ROWS` for strict row-by-row totals.",
          "WITH daily AS (\n  SELECT o.order_date, SUM(oi.quantity * oi.unit_price) AS revenue\n  FROM orders o JOIN order_items oi ON oi.order_id = o.id\n  WHERE o.status <> 'cancelled' GROUP BY o.order_date\n)\nSELECT order_date, revenue, SUM(revenue) OVER (ORDER BY order_date) AS running_total\nFROM daily LIMIT 6;"),
        Q("I", "What do LAG and LEAD do?",
          "`LAG(col, n)` returns the value from n rows before the current row in the window order; `LEAD(col, n)` returns the value n rows after. The optional third argument is the default when there's no such row.",
          "They're perfect for period-over-period comparisons (this month vs last month) and gaps between events.",
          "SELECT customer_id, order_date,\n       LAG(order_date) OVER (PARTITION BY customer_id ORDER BY order_date) AS previous_order,\n       julianday(order_date) - julianday(LAG(order_date) OVER (PARTITION BY customer_id ORDER BY order_date)) AS days_since\nFROM orders WHERE customer_id IN (1, 2) ORDER BY customer_id, order_date;"),
        Q("A", "What are window frames (ROWS BETWEEN ...)?",
          "A frame limits which rows in the partition the function sees: `ROWS BETWEEN 2 PRECEDING AND CURRENT ROW` gives a 3-row moving window, and `UNBOUNDED PRECEDING` starts at the partition's first row.",
          "Frames power moving averages and rolling sums.",
          "SELECT id, order_date,\n       COUNT(*) OVER (ORDER BY order_date ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS last_3_window\nFROM orders LIMIT 5;"),
        Q("I", "What does NTILE do?",
          "`NTILE(n)` splits ordered rows into n nearly equal buckets and returns the bucket number, for quartiles, deciles and so on.",
          "Use it for \"top 25% of customers by spend\" style segmentation.",
          "SELECT name, salary, NTILE(4) OVER (ORDER BY salary DESC) AS quartile\nFROM employees ORDER BY salary DESC;"),
        Q("A", "What do FIRST_VALUE and LAST_VALUE do, and what's the gotcha?",
          "They return the first or last value in the window frame. The gotcha: with `ORDER BY`, the default frame ends at the current row, so `LAST_VALUE` returns the current row's value unless you set `ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING`.",
          "Many people use `FIRST_VALUE` with a descending order instead, to avoid the frame issue.",
          "SELECT name, dept_id, salary,\n       FIRST_VALUE(name) OVER (PARTITION BY dept_id ORDER BY salary DESC) AS top_earner,\n       LAST_VALUE(name)  OVER (PARTITION BY dept_id ORDER BY salary DESC\n                               ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS lowest_earner\nFROM employees WHERE dept_id = 2;"),
        Q("A", "How do you compute each row's share of a total?",
          "Divide by a window total: `x * 100.0 / SUM(x) OVER ()` gives a percentage of the grand total; add `PARTITION BY` for a share within a group.",
          "`OVER ()` with empty parentheses means \"the whole result set\".",
          "SELECT category, SUM(price) AS catalogue_value,\n       ROUND(SUM(price) * 100.0 / SUM(SUM(price)) OVER (), 1) AS pct\nFROM products GROUP BY category ORDER BY pct DESC;"),
    ]),

    S("Modifying Data", "✏️", "Module 8", [
        Q("B", "How do you insert rows?",
          "`INSERT INTO table (col1, col2) VALUES (v1, v2);`. Always list the columns. You can insert several rows at once with comma-separated tuples, or insert the results of a query with `INSERT INTO ... SELECT ...`.",
          "Listing columns protects you when the table's column order changes.",
          "INSERT INTO departments (id, name, location) VALUES (6, 'Support', 'Pune'), (7, 'Legal', 'Delhi');\nSELECT * FROM departments WHERE id >= 6;"),
        Q("B", "How do you update rows?",
          "`UPDATE table SET col = value WHERE condition;`. Without `WHERE`, *every* row is updated.",
          "Run the same `WHERE` as a `SELECT` first to check which rows will change, and do it inside a transaction.",
          "UPDATE employees SET salary = salary * 1.10 WHERE dept_id = 4;\nSELECT name, salary FROM employees WHERE dept_id = 4;"),
        Q("B", "How do you delete rows?",
          "`DELETE FROM table WHERE condition;`. Without `WHERE`, all rows are deleted (but the table remains).",
          "With foreign keys, deleting a parent row may be blocked or may cascade to child rows, depending on `ON DELETE` rules.",
          "DELETE FROM order_items WHERE order_id = 4;\nDELETE FROM orders WHERE status = 'cancelled';\nSELECT COUNT(*) AS orders_left FROM orders;"),
        Q("I", "DELETE vs TRUNCATE vs DROP: what's the difference?",
          "`DELETE` removes chosen rows, is logged row by row, can be rolled back and fires triggers. `TRUNCATE` removes all rows at once, is fast and minimally logged, and often can't be rolled back (it's DDL in many databases). `DROP` removes the whole table: structure, data, indexes and permissions.",
          "SQLite has no TRUNCATE; `DELETE FROM t` without WHERE is optimised to do the same.",
          "-- PostgreSQL / MySQL / Snowflake\nDELETE FROM staging_orders WHERE loaded_at < '2024-01-01';\nTRUNCATE TABLE staging_orders;\nDROP TABLE staging_orders;", run=False, play=False, lang="text"),
        Q("I", "What is an UPSERT?",
          "Insert a row, or update it if it already exists (a key conflict). SQLite and PostgreSQL use `INSERT ... ON CONFLICT (key) DO UPDATE SET ...`; MySQL uses `ON DUPLICATE KEY UPDATE`; SQL Server, Oracle and Snowflake use `MERGE`.",
          "`excluded.col` refers to the value you tried to insert.",
          "INSERT INTO products (id, name, category, price) VALUES (2, 'Wireless Mouse', 'Electronics', 999)\nON CONFLICT (id) DO UPDATE SET price = excluded.price;\nSELECT id, name, price FROM products WHERE id = 2;"),
        Q("I", "What does RETURNING do?",
          "It returns the rows affected by an `INSERT`, `UPDATE` or `DELETE`, including generated ids, so you don't need a second query. It's supported by PostgreSQL, SQLite (3.35+) and Oracle; SQL Server uses `OUTPUT`.",
          "Handy for getting the auto-generated primary key of a new row.",
          "INSERT INTO customers (name, city, country, signup_date)\nVALUES ('Isha Menon', 'Kochi', 'India', '2024-09-01')\nRETURNING id, name;"),
        Q("I", "How do you insert the result of a query?",
          "`INSERT INTO target (cols) SELECT ... FROM source WHERE ...;` copies data in one set-based statement, which is much faster than looping row by row.",
          "`CREATE TABLE new AS SELECT ...` (CTAS) creates and fills a table in one go.",
          "CREATE TABLE big_orders AS\nSELECT order_id, SUM(quantity * unit_price) AS total FROM order_items GROUP BY order_id HAVING total > 20000;\nSELECT COUNT(*) AS big_orders FROM big_orders;"),
        Q("A", "How do you update rows using data from another table?",
          "Use a correlated subquery in `SET`, or `UPDATE ... FROM` (PostgreSQL, SQLite 3.33+, SQL Server) / `UPDATE ... JOIN` (MySQL), or `MERGE`.",
          "Always make sure the join produces at most one source row per target row, otherwise the result is ambiguous.",
          "ALTER TABLE customers ADD COLUMN lifetime_value INTEGER DEFAULT 0;\nUPDATE customers SET lifetime_value = t.total\nFROM (SELECT o.customer_id, SUM(oi.quantity * oi.unit_price) AS total\n      FROM orders o JOIN order_items oi ON oi.order_id = o.id GROUP BY o.customer_id) AS t\nWHERE t.customer_id = customers.id;\nSELECT name, lifetime_value FROM customers ORDER BY lifetime_value DESC LIMIT 3;"),
        Q("A", "How do you delete duplicate rows but keep one?",
          "Number the rows within each duplicate group with `ROW_NUMBER() OVER (PARTITION BY dup_cols ORDER BY id)` and delete those with a number above 1. Or keep `MIN(id)` per group and delete the rest.",
          "Add a UNIQUE constraint afterwards so duplicates can't come back.",
          "CREATE TABLE signups (id INTEGER PRIMARY KEY, email TEXT);\nINSERT INTO signups (email) VALUES ('a@x.com'), ('b@x.com'), ('a@x.com'), ('a@x.com');\nDELETE FROM signups WHERE id NOT IN (SELECT MIN(id) FROM signups GROUP BY email);\nSELECT * FROM signups;"),
    ]),

    S("Tables, Types & Constraints", "🏗️", "Module 9", [
        Q("B", "How do you create a table?",
          "`CREATE TABLE name (col type constraints, ...);`. Give every table a primary key and choose precise data types.",
          "`CREATE TABLE IF NOT EXISTS` avoids an error if it already exists.",
          "CREATE TABLE IF NOT EXISTS reviews (\n  id          INTEGER PRIMARY KEY,\n  product_id  INTEGER NOT NULL REFERENCES products(id),\n  rating      INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),\n  comment     TEXT,\n  created_at  TEXT DEFAULT CURRENT_TIMESTAMP\n);\nINSERT INTO reviews (product_id, rating, comment) VALUES (1, 5, 'Fast!');\nSELECT id, product_id, rating, comment FROM reviews;"),
        Q("B", "Which SQL data types are most common?",
          "Integers (`INT`, `BIGINT`, `SMALLINT`), exact decimals (`DECIMAL(p, s)`/`NUMERIC`, good for money), floats (`REAL`, `FLOAT`, `DOUBLE`), text (`VARCHAR(n)`, `TEXT`, `CHAR(n)`), `BOOLEAN`, `DATE`, `TIMESTAMP`, and semi-structured types like `JSON` and `VARIANT`.",
          "Never store money in FLOAT; use DECIMAL or integer paise/cents. SQLite simplifies everything to five storage classes (NULL, INTEGER, REAL, TEXT, BLOB).",
          "SELECT typeof(42), typeof(4.2), typeof('42'), typeof(NULL), typeof(x'00');"),
        Q("B", "What are NOT NULL, UNIQUE, CHECK and DEFAULT constraints?",
          "`NOT NULL` forbids missing values; `UNIQUE` forbids duplicates (NULLs are usually allowed); `CHECK (expr)` enforces a rule on every row; `DEFAULT value` fills a column when it isn't provided.",
          "Constraints are your last line of defence: the database guarantees them even when application code has bugs.",
          "INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (1, 3, 0, 4500);", error=True),
        Q("I", "How do you change a table's structure?",
          "`ALTER TABLE` can add, rename or drop columns, rename the table, and add constraints (support varies by database).",
          "Adding a NOT NULL column to a big table needs a DEFAULT, or a backfill in steps.",
          "ALTER TABLE products ADD COLUMN in_stock INTEGER NOT NULL DEFAULT 1;\nALTER TABLE products RENAME COLUMN in_stock TO available;\nSELECT id, name, available FROM products LIMIT 3;"),
        Q("I", "What is a view?",
          "A saved query that behaves like a virtual table. Querying the view runs its query, so it always shows current data. Views simplify complex joins, hide columns for security and give a stable interface.",
          "A materialised view stores the results physically and must be refreshed (PostgreSQL, Oracle, Snowflake).",
          "CREATE VIEW order_totals AS\nSELECT o.id, c.name AS customer, o.status, SUM(oi.quantity * oi.unit_price) AS total\nFROM orders o JOIN customers c ON c.id = o.customer_id JOIN order_items oi ON oi.order_id = o.id\nGROUP BY o.id;\nSELECT * FROM order_totals WHERE status = 'pending';"),
        Q("I", "What do ON DELETE CASCADE, SET NULL and RESTRICT mean?",
          "They say what happens to child rows when the referenced parent row is deleted: `CASCADE` deletes them too, `SET NULL` clears the foreign key, and `RESTRICT`/`NO ACTION` (the default) blocks the delete.",
          "Cascade deletes are convenient but dangerous on important data; many teams prefer soft deletes (`is_active = 0`).",
          "PRAGMA foreign_keys = ON;\nCREATE TABLE parent (id INTEGER PRIMARY KEY);\nCREATE TABLE child (id INTEGER PRIMARY KEY, parent_id INTEGER REFERENCES parent(id) ON DELETE CASCADE);\nINSERT INTO parent VALUES (1), (2);\nINSERT INTO child VALUES (10, 1), (11, 1), (12, 2);\nDELETE FROM parent WHERE id = 1;\nSELECT * FROM child;"),
        Q("I", "What is an auto-increment / identity column?",
          "A column whose value the database generates automatically for new rows: `INTEGER PRIMARY KEY` in SQLite, `SERIAL`/`GENERATED AS IDENTITY` in PostgreSQL, `AUTO_INCREMENT` in MySQL, `IDENTITY` in SQL Server and Snowflake.",
          "Ids can have gaps (rollbacks, deletes). Never assume they're consecutive.",
          "INSERT INTO customers (name, city, country) VALUES ('New Customer', 'Pune', 'India');\nSELECT id, name FROM customers ORDER BY id DESC LIMIT 1;"),
        Q("A", "CHAR vs VARCHAR vs TEXT: what's the difference?",
          "`CHAR(n)` is fixed length and padded with spaces; `VARCHAR(n)` is variable length with a maximum; `TEXT` is variable length without a declared limit. In PostgreSQL, VARCHAR and TEXT perform the same.",
          "Use CHAR only for truly fixed codes (country codes). A length limit is still useful as a data-quality rule.",
          None),
        Q("A", "What are generated (computed) columns?",
          "Columns whose value is calculated from other columns, either stored or computed on read: `total INTEGER GENERATED ALWAYS AS (quantity * unit_price)`.",
          "They keep derived values consistent and can be indexed in many databases.",
          "CREATE TABLE lines (qty INTEGER, price INTEGER, total INTEGER GENERATED ALWAYS AS (qty * price) STORED);\nINSERT INTO lines (qty, price) VALUES (3, 250), (2, 1200);\nSELECT * FROM lines;"),
    ]),

    S("Data Modeling & Normalization", "📐", "Module 10", [
        Q("I", "What is normalization?",
          "Organising tables to reduce redundancy and prevent update, insert and delete anomalies, by splitting data so each fact is stored once and tables link through keys.",
          "If a customer's city is stored on every order row, changing it means updating many rows, and missing one leaves inconsistent data.",
          None),
        Q("I", "What are 1NF, 2NF and 3NF?",
          "1NF: atomic values, with no repeating groups or lists in a column. 2NF: 1NF plus every non-key column depends on the *whole* primary key (matters for composite keys). 3NF: 2NF plus no non-key column depends on another non-key column (no transitive dependencies).",
          "The mnemonic: every non-key attribute depends on \"the key, the whole key, and nothing but the key\". BCNF is a stricter 3NF.",
          None),
        Q("I", "What is denormalization, and when is it OK?",
          "Deliberately duplicating data (storing a customer name on the order, or precomputed totals) to speed up reads and avoid joins. It's common in warehouses, caches and read-heavy systems.",
          "The cost is keeping copies in sync. Do it on purpose, with a refresh strategy, not by accident.",
          None),
        Q("I", "What are one-to-one, one-to-many and many-to-many relationships?",
          "One-to-many: a foreign key on the \"many\" side (one customer → many orders). Many-to-many: a junction (bridge) table with two foreign keys (orders ↔ products through `order_items`). One-to-one: a foreign key that is also unique (user → profile).",
          "`order_items` is MegaMart's junction table, and it also carries its own attributes (quantity, price).",
          "SELECT p.name, COUNT(DISTINCT oi.order_id) AS orders_containing\nFROM products p LEFT JOIN order_items oi ON oi.product_id = p.id\nGROUP BY p.id ORDER BY orders_containing DESC LIMIT 4;"),
        Q("I", "What is a star schema?",
          "A warehouse design with a central fact table (measurable events: sales lines, with foreign keys and numbers) surrounded by dimension tables (who, what, where, when: customer, product, store, date).",
          "It's easy for BI tools to query and fast for aggregation. A snowflake schema further normalises the dimensions.",
          None),
        Q("I", "What are fact and dimension tables?",
          "Facts hold measurements at a chosen grain (one row per order line) with keys to dimensions. Dimensions hold descriptive attributes used to filter and group (product category, customer city, calendar month).",
          "Decide the grain first; every fact row must be at the same grain.",
          "-- fact at order-line grain joined to its dimensions\nSELECT d.m AS month, p.category, SUM(f.quantity * f.unit_price) AS revenue\nFROM order_items f\nJOIN products p ON p.id = f.product_id\nJOIN (SELECT id, strftime('%Y-%m', order_date) AS m FROM orders) d ON d.id = f.order_id\nGROUP BY month, p.category ORDER BY month LIMIT 5;"),
        Q("I", "Surrogate key vs natural key: which should you use?",
          "A natural key has business meaning (email, PAN, ISBN); a surrogate key is a meaningless generated id. Surrogates are stable, compact and never change, so they're the usual primary key; still add a UNIQUE constraint on the natural key.",
          "Emails change and \"unique\" business codes get reused, which is exactly why surrogates win.",
          None),
        Q("A", "What are slowly changing dimensions (SCD)?",
          "Techniques for dimension attributes that change over time. Type 1 overwrites (no history); Type 2 adds a new row with valid-from/valid-to dates and a current flag (full history); Type 3 keeps the previous value in an extra column.",
          "Type 2 lets reports show sales by the customer's city *at the time of the sale*.",
          "CREATE TABLE dim_customer (sk INTEGER PRIMARY KEY, customer_id INTEGER, city TEXT, valid_from TEXT, valid_to TEXT, is_current INTEGER);\nINSERT INTO dim_customer VALUES (1, 1, 'Cuttack', '2023-01-05', '2024-06-30', 0), (2, 1, 'Bhubaneswar', '2024-07-01', '9999-12-31', 1);\nSELECT city FROM dim_customer WHERE customer_id = 1 AND '2024-03-15' BETWEEN valid_from AND valid_to;"),
        Q("B", "What is an ER diagram?",
          "An Entity-Relationship diagram shows entities (tables), their attributes (columns), keys and the relationships between them with cardinality (1:1, 1:N, M:N).",
          "Sketch one before creating tables; it's far cheaper to fix a box on a whiteboard than a production schema. The schema explorer in the playground is a mini ER view of MegaMart.",
          None),
    ]),

    S("Indexes & Performance", "⚡", "Module 11", [
        Q("I", "What is an index?",
          "A separate data structure (usually a B-tree) that keeps column values sorted with pointers to rows, so lookups, range scans, joins and sorts don't have to scan the whole table. It's like a book's index.",
          "Indexes speed up reads but slow down writes and use storage, since every insert and update must maintain them.",
          "CREATE INDEX idx_orders_customer ON orders(customer_id);\nEXPLAIN QUERY PLAN SELECT * FROM orders WHERE customer_id = 2;"),
        Q("I", "How do you see how a query will be executed?",
          "Use the query plan: `EXPLAIN QUERY PLAN` in SQLite, `EXPLAIN` / `EXPLAIN ANALYZE` in PostgreSQL and MySQL, the Query Profile in Snowflake. Look for full scans on big tables, the join methods and the estimated row counts.",
          "`SCAN` means reading every row; `SEARCH ... USING INDEX` means the index is used.",
          "EXPLAIN QUERY PLAN SELECT * FROM employees WHERE salary > 90000;"),
        Q("A", "How does a composite index work (the leftmost-prefix rule)?",
          "An index on `(a, b)` is sorted by `a`, then `b`. It helps queries filtering on `a` or on `a AND b`, but usually not on `b` alone.",
          "Put the most selective, equality-filtered column first, and range-filtered columns last.",
          "CREATE INDEX idx_orders_status_date ON orders(status, order_date);\nEXPLAIN QUERY PLAN SELECT id FROM orders WHERE status = 'delivered' AND order_date >= '2024-05-01';"),
        Q("A", "What is a covering index?",
          "An index that contains every column a query needs, so the database answers from the index alone without visiting the table (an \"index-only scan\").",
          "Some databases let you add non-key columns with `INCLUDE (...)`.",
          "CREATE INDEX idx_emp_dept_salary ON employees(dept_id, salary);\nEXPLAIN QUERY PLAN SELECT dept_id, MAX(salary) FROM employees GROUP BY dept_id;"),
        Q("A", "What is a SARGable query, and why does it matter?",
          "A condition the database can resolve with an index seek (\"Search ARGument-able\"). Wrapping the indexed column in a function or expression (`WHERE UPPER(email) = ...`, `WHERE salary * 12 > ...`, `WHERE strftime('%Y', date) = '2024'`) usually prevents index use.",
          "Rewrite as ranges on the bare column (`date >= '2024-01-01' AND date < '2025-01-01'`) or create an expression index.",
          "CREATE INDEX idx_orders_date ON orders(order_date);\nEXPLAIN QUERY PLAN SELECT id FROM orders WHERE strftime('%Y', order_date) = '2024';\nEXPLAIN QUERY PLAN SELECT id FROM orders WHERE order_date >= '2024-01-01' AND order_date < '2025-01-01';"),
        Q("I", "When should you NOT add an index?",
          "On small tables, on low-selectivity columns (a boolean flag) filtered alone, on columns that are rarely filtered or joined, and on write-heavy tables where the maintenance cost beats the read benefit.",
          "Every index is a trade-off: add them for real query patterns, and drop unused ones.",
          None),
        Q("I", "What are clustered and non-clustered indexes?",
          "A clustered index defines the physical order of the table's rows (one per table; the table *is* the index). A non-clustered index is a separate structure pointing to rows (many per table).",
          "In SQL Server and MySQL (InnoDB) the primary key is clustered by default. In SQLite, rowid tables are stored by rowid. Snowflake uses micro-partitions and clustering keys instead.",
          None),
        Q("A", "How would you speed up a slow query?",
          "Measure it (look at the plan and timings), then: filter early, select only needed columns, add or fix indexes for WHERE/JOIN/ORDER BY columns, make predicates SARGable, avoid row-by-row loops and N+1 queries, pre-aggregate before joining, and update table statistics.",
          "In a warehouse like Snowflake: prune partitions (filter on the clustering columns), size the warehouse and avoid spilling to disk.",
          None),
        Q("I", "What is the N+1 query problem?",
          "Application code runs 1 query to fetch a list and then N more queries, one per item, to fetch related data, so 101 round trips instead of 1 or 2. It's common with ORMs and lazy loading.",
          "Fix it with a JOIN, an `IN (...)` batch query, or the ORM's eager loading.",
          "-- instead of querying orders once per customer, do it in one go\nSELECT c.name, COUNT(o.id) AS orders FROM customers c LEFT JOIN orders o ON o.customer_id = c.id GROUP BY c.id LIMIT 5;"),
    ]),

    S("Transactions & Concurrency", "🔒", "Module 12", [
        Q("B", "What is a transaction?",
          "A group of statements executed as one unit: either all changes are committed, or all are rolled back. Start with `BEGIN`, finish with `COMMIT` (save) or `ROLLBACK` (undo).",
          "Without an explicit transaction, most databases auto-commit each statement on its own.",
          "BEGIN;\nDELETE FROM order_items;\nSELECT COUNT(*) AS during FROM order_items;\nROLLBACK;\nSELECT COUNT(*) AS after_rollback FROM order_items;"),
        Q("I", "What is a savepoint?",
          "A named point inside a transaction that you can roll back to without undoing the whole transaction: `SAVEPOINT s1; ... ROLLBACK TO s1;`.",
          "It's useful for \"try this step, undo just this step if it fails\" logic.",
          "BEGIN;\nUPDATE products SET price = 1 WHERE id = 6;\nSAVEPOINT before_mistake;\nDELETE FROM products WHERE id = 6;\nROLLBACK TO before_mistake;\nCOMMIT;\nSELECT id, name, price FROM products WHERE id = 6;"),
        Q("I", "What are dirty reads, non-repeatable reads and phantom reads?",
          "Dirty read: seeing another transaction's uncommitted change. Non-repeatable read: reading the same row twice and getting different values because someone committed in between. Phantom read: re-running a range query and seeing new or removed rows.",
          "Isolation levels decide which of these can happen.",
          None),
        Q("I", "What are the SQL isolation levels?",
          "READ UNCOMMITTED (dirty reads possible), READ COMMITTED (the default in PostgreSQL, Oracle, SQL Server and Snowflake), REPEATABLE READ (the default in MySQL InnoDB) and SERIALIZABLE (transactions behave as if run one after another).",
          "Higher isolation means fewer anomalies but more blocking or retries. Pick the lowest level that keeps your data correct.",
          "-- PostgreSQL\nBEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE;\nSELECT balance FROM accounts WHERE id = 1;\nUPDATE accounts SET balance = balance - 500 WHERE id = 1;\nCOMMIT;", run=False, play=False, lang="text"),
        Q("A", "What is a deadlock?",
          "Two (or more) transactions each hold a lock the other needs, so neither can proceed. The database detects the cycle and aborts one transaction (the \"victim\"), which must retry.",
          "Prevent deadlocks by always locking resources in the same order, keeping transactions short, and retrying on deadlock errors.",
          None),
        Q("A", "What is MVCC?",
          "Multi-Version Concurrency Control: instead of locking rows for reads, the database keeps several versions of a row so each transaction sees a consistent snapshot. Readers don't block writers and writers don't block readers.",
          "PostgreSQL, Oracle, MySQL InnoDB and Snowflake all use MVCC. It's why PostgreSQL needs VACUUM to clean up old row versions.",
          None),
        Q("I", "Optimistic vs pessimistic locking: what's the difference?",
          "Pessimistic: lock the row when you read it (`SELECT ... FOR UPDATE`) so nobody else can change it. Optimistic: don't lock, but check a version column when writing (`UPDATE ... WHERE id = ? AND version = ?`) and retry if someone else changed it first.",
          "Optimistic locking suits low-conflict web apps; pessimistic suits high-conflict critical updates like seat booking.",
          "CREATE TABLE seats (id INTEGER PRIMARY KEY, holder TEXT, version INTEGER DEFAULT 0);\nINSERT INTO seats (id) VALUES (1);\nUPDATE seats SET holder = 'Ananya', version = version + 1 WHERE id = 1 AND version = 0;\nUPDATE seats SET holder = 'Rohit', version = version + 1 WHERE id = 1 AND version = 0;   -- stale version: 0 rows\nSELECT * FROM seats;"),
        Q("A", "Why should transactions be short?",
          "Long transactions hold locks (blocking others), keep old row versions alive (bloat in MVCC databases), increase deadlock risk and make rollbacks expensive.",
          "Never wait for user input or call slow external APIs inside a database transaction.",
          None),
    ]),
]
