"""Sections 1-6: fundamentals, SELECT basics, functions, aggregation, joins, subqueries & CTEs."""
from schema import Q, S

SECTIONS = [
    S("Database Fundamentals", "🗄️", "Module 1", [
        Q("B", "What is a database?",
          "An organised collection of data stored so it can be efficiently read, updated and managed. The software that manages it is a DBMS (Database Management System), for example PostgreSQL, MySQL, SQLite, Oracle, SQL Server or Snowflake.",
          "A spreadsheet holds data too, but a DBMS adds concurrency (many users at once), integrity rules, security, recovery after crashes and a query language.",
          "SELECT name FROM sqlite_master WHERE type = 'table' ORDER BY name;"),
        Q("B", "What is a relational database?",
          "A database that stores data in tables (relations) made of rows and columns, where tables are linked by keys. It was introduced by E. F. Codd in 1970 and is queried with SQL.",
          "In MegaMart, `orders.customer_id` links each order to a row in `customers`: that link is the \"relation\" idea in practice.",
          "SELECT o.id AS order_id, c.name AS customer\nFROM orders o JOIN customers c ON c.id = o.customer_id\nLIMIT 3;"),
        Q("B", "What are tables, rows and columns?",
          "A table stores one kind of thing (customers). Each row (record, tuple) is one instance of it (one customer), and each column (field, attribute) is one property with a data type (name, city).",
          "Good tables describe exactly one entity; mixing customers and orders in one table causes duplication and update problems.",
          "SELECT * FROM departments;"),
        Q("B", "What is SQL?",
          "Structured Query Language: the standard language for relational databases. It's declarative: you describe *what* result you want and the database's query optimizer decides *how* to get it.",
          "SQL is split into sub-languages: DQL (`SELECT`), DML (`INSERT`, `UPDATE`, `DELETE`), DDL (`CREATE`, `ALTER`, `DROP`), DCL (`GRANT`, `REVOKE`) and TCL (`COMMIT`, `ROLLBACK`).",
          "SELECT COUNT(*) AS customers, (SELECT COUNT(*) FROM orders) AS orders FROM customers;"),
        Q("B", "What are DDL, DML, DQL, DCL and TCL?",
          "DDL defines structure (`CREATE`, `ALTER`, `DROP`, `TRUNCATE`); DML changes data (`INSERT`, `UPDATE`, `DELETE`, `MERGE`); DQL queries data (`SELECT`); DCL controls access (`GRANT`, `REVOKE`); TCL manages transactions (`BEGIN`, `COMMIT`, `ROLLBACK`, `SAVEPOINT`).",
          "Interviewers love this classification. In many databases DDL commits automatically, so it can't be rolled back (PostgreSQL and SQLite are exceptions).",
          "-- DDL\nCREATE TABLE notes (id INTEGER PRIMARY KEY, body TEXT);\n-- DML\nINSERT INTO notes (body) VALUES ('first'), ('second');\n-- DQL\nSELECT * FROM notes;"),
        Q("B", "What is a primary key?",
          "A column (or set of columns) that uniquely identifies each row. It can't be NULL and there's only one per table. `order_items` uses a composite key `(order_id, product_id)`.",
          "Other tables refer to a row through its primary key, so it should never change. That's why surrogate keys (auto-numbered ids) are popular.",
          "INSERT INTO departments (id, name) VALUES (1, 'Duplicate id');", error=True),
        Q("B", "What is a foreign key?",
          "A column that references the primary key of another (or the same) table, enforcing referential integrity: you can't point at a row that doesn't exist. `orders.customer_id` references `customers.id`.",
          "SQLite only enforces foreign keys after `PRAGMA foreign_keys = ON`; most other databases enforce them by default.",
          "PRAGMA foreign_keys = ON;\nINSERT INTO orders (customer_id, order_date, status) VALUES (999, '2024-09-01', 'pending');", error=True),
        Q("I", "OLTP vs OLAP: what's the difference?",
          "OLTP (Online Transaction Processing) runs the business: many small, fast reads and writes of individual rows (placing an order). OLAP (Online Analytical Processing) analyses it: fewer, large queries that scan and aggregate millions of rows (sales by month).",
          "OLTP databases (PostgreSQL, MySQL) are row-oriented and normalised; OLAP warehouses (Snowflake, BigQuery, Redshift) are column-oriented and often use star schemas.",
          "-- OLTP-style: touch one row\nSELECT * FROM orders WHERE id = 7;\n-- OLAP-style: scan and aggregate\nSELECT substr(order_date, 1, 7) AS month, COUNT(*) AS orders FROM orders GROUP BY month;"),
        Q("I", "What are the ACID properties?",
          "Atomicity (a transaction happens completely or not at all), Consistency (it moves the database from one valid state to another), Isolation (concurrent transactions don't see each other's half-done work) and Durability (once committed, it survives crashes).",
          "The classic example is a bank transfer: debit and credit must both happen, or neither.",
          "BEGIN;\nUPDATE products SET price = price - 100 WHERE id = 1;\nUPDATE products SET price = price + 100 WHERE id = 2;\nCOMMIT;\nSELECT id, price FROM products WHERE id IN (1, 2);"),
        Q("B", "SQL vs NoSQL: when do you use which?",
          "SQL (relational) databases suit structured data with relationships and strong consistency: orders, payments, inventory. NoSQL databases (document, key-value, wide-column, graph) suit flexible schemas, massive horizontal scale or special access patterns: user sessions, catalogues, social graphs.",
          "It isn't either-or: many systems use PostgreSQL for transactions, Redis for caching and a warehouse like Snowflake for analytics.",
          None),
        Q("I", "What is a schema?",
          "The structure of a database: its tables, columns, data types, keys, constraints, views and indexes. The word also means a namespace that groups objects (`sales.orders` vs `hr.employees`) in PostgreSQL, SQL Server and Snowflake.",
          "SQLite keeps its schema in the `sqlite_master` table; other databases expose `information_schema` views.",
          "SELECT sql FROM sqlite_master WHERE name = 'order_items';"),
    ]),

    S("SELECT Basics", "🔎", "Module 2", [
        Q("B", "How do you select specific columns from a table?",
          "List them after `SELECT` and name the table after `FROM`: `SELECT name, city FROM customers;`. `SELECT *` returns every column.",
          "Avoid `SELECT *` in production code: it fetches data you don't need and breaks when columns are added or reordered.",
          "SELECT name, city, country FROM customers LIMIT 5;"),
        Q("B", "How do you filter rows with WHERE?",
          "`WHERE` keeps only rows where the condition is true. Combine conditions with `AND`, `OR` and `NOT`, and use parentheses to make precedence explicit (`AND` binds tighter than `OR`).",
          "Filtering early reduces the rows every later step has to process.",
          "SELECT name, salary FROM employees\nWHERE dept_id = 2 AND salary > 100000;"),
        Q("B", "How do you sort results?",
          "`ORDER BY column [ASC|DESC]`, with several columns as tie-breakers: `ORDER BY salary DESC, name`. Without `ORDER BY`, row order is not guaranteed.",
          "Never rely on the \"natural\" order of a table: it can change after updates, deletes or a new query plan.",
          "SELECT name, salary FROM employees ORDER BY salary DESC, name LIMIT 5;"),
        Q("B", "How do you limit the number of rows returned?",
          "`LIMIT n` (SQLite, PostgreSQL, MySQL, Snowflake), `FETCH FIRST n ROWS ONLY` (standard SQL, Oracle) or `TOP n` (SQL Server). `OFFSET m` skips rows, which is used for paging.",
          "Always pair `LIMIT` with `ORDER BY`, otherwise \"the top 3\" is just 3 arbitrary rows.",
          "SELECT name, price FROM products ORDER BY price DESC LIMIT 3 OFFSET 1;"),
        Q("B", "What does DISTINCT do?",
          "It removes duplicate rows from the result. With several columns it removes duplicate *combinations*.",
          "`DISTINCT` often hides a join that produced duplicates by mistake. Fix the join instead of papering over it.",
          "SELECT DISTINCT country FROM customers ORDER BY country;"),
        Q("B", "How do you rename columns with aliases?",
          "`AS` gives a column or table a new name in the query: `SELECT price * 1.18 AS price_with_gst`. Table aliases shorten joins: `FROM customers AS c`.",
          "In most databases you can't use a column alias in `WHERE` (it's evaluated before `SELECT`), but you can in `ORDER BY`.",
          "SELECT name AS product, price, price * 1.18 AS price_with_gst\nFROM products ORDER BY price_with_gst DESC LIMIT 3;"),
        Q("B", "How do IN and BETWEEN work?",
          "`col IN (a, b, c)` matches any value in the list (shorthand for several `OR`s). `col BETWEEN low AND high` is inclusive on both ends.",
          "`BETWEEN` on dates stored with times can miss the last day's rows; `>= start AND < next_day` is safer.",
          "SELECT id, status, order_date FROM orders\nWHERE status IN ('pending', 'shipped')\n  AND order_date BETWEEN '2024-03-01' AND '2024-06-30';"),
        Q("B", "How does LIKE pattern matching work?",
          "`%` matches any number of characters and `_` matches exactly one: `name LIKE 'A%'` finds names starting with A. `NOT LIKE` inverts the match.",
          "In SQLite `LIKE` is case-insensitive for ASCII; in PostgreSQL it's case-sensitive (use `ILIKE`). A leading `%` usually prevents index use.",
          "SELECT name FROM customers WHERE name LIKE '%a' OR name LIKE '_m%';"),
        Q("I", "Why doesn't `WHERE email = NULL` work?",
          "NULL means \"unknown\", so any comparison with NULL (`=`, `<>`, `<`) is unknown, not true, and the row is filtered out. Use `IS NULL` or `IS NOT NULL`.",
          "This is SQL's three-valued logic: TRUE, FALSE and UNKNOWN. `WHERE` keeps only TRUE.",
          "SELECT COUNT(*) AS eq_null FROM employees WHERE email = NULL;\nSELECT name FROM employees WHERE email IS NULL;"),
        Q("I", "Why does `NOT IN` with a NULL in the list return no rows?",
          "`x NOT IN (1, NULL)` means `x <> 1 AND x <> NULL`, and `x <> NULL` is UNKNOWN, so the whole condition is never TRUE. A single NULL in a `NOT IN` subquery empties the result.",
          "Use `NOT EXISTS` (or filter NULLs out of the subquery) for anti-joins. This is a classic interview trap.",
          "SELECT COUNT(*) AS not_in_count\nFROM employees WHERE dept_id NOT IN (SELECT dept_id FROM employees WHERE id > 9);\n"),
        Q("I", "In what order is a SELECT statement logically evaluated?",
          "`FROM` (and `JOIN`s) → `WHERE` → `GROUP BY` → `HAVING` → `SELECT` (expressions, aliases, window functions) → `DISTINCT` → `ORDER BY` → `LIMIT`/`OFFSET`.",
          "This explains why a `SELECT` alias can't be used in `WHERE`, and why aggregates can't appear in `WHERE` (use `HAVING`).",
          "SELECT dept_id, COUNT(*) AS n        -- 5. select\nFROM employees                        -- 1. from\nWHERE salary > 55000                  -- 2. where\nGROUP BY dept_id                      -- 3. group by\nHAVING COUNT(*) >= 2                  -- 4. having\nORDER BY n DESC;                      -- 6. order by"),
    ]),

    S("Functions & Expressions", "🧮", "Module 3", [
        Q("B", "Which string functions are used most?",
          "`UPPER`/`LOWER`, `LENGTH`, `TRIM`, `SUBSTR`/`SUBSTRING`, `REPLACE`, `INSTR`/`POSITION`, and concatenation with `||` (standard, SQLite, PostgreSQL, Snowflake) or `CONCAT()`.",
          "Names differ slightly between databases (`LEN` in SQL Server, `SUBSTRING` vs `SUBSTR`), but the ideas are identical.",
          "SELECT UPPER(name) AS upper_name, LENGTH(name) AS len,\n       SUBSTR(name, 1, INSTR(name, ' ') - 1) AS first_name,\n       name || ' (' || city || ')' AS label\nFROM customers LIMIT 3;"),
        Q("B", "Which numeric functions are common?",
          "`ROUND(x, d)`, `ABS`, `CEIL`/`FLOOR` (`CEILING` in some databases), `MOD` or `%`, `POWER`, and arithmetic `+ - * /`.",
          "Integer division truncates in SQLite, PostgreSQL and SQL Server: `7 / 2` is 3. Multiply by 1.0 or `CAST` to get decimals.",
          "SELECT 7 / 2 AS int_div, 7 / 2.0 AS real_div, 7 % 3 AS remainder,\n       ROUND(1234.5678, 2) AS rounded, ABS(-42) AS absolute;"),
        Q("I", "How does a CASE expression work?",
          "`CASE WHEN cond THEN value ... ELSE default END` returns the value of the first true condition, like if/else inside a query. It works in `SELECT`, `WHERE`, `ORDER BY` and inside aggregates.",
          "Without `ELSE`, unmatched rows get NULL.",
          "SELECT name, price,\n  CASE WHEN price >= 20000 THEN 'premium'\n       WHEN price >= 2000  THEN 'mid'\n       ELSE 'budget' END AS tier\nFROM products ORDER BY price DESC LIMIT 5;"),
        Q("I", "What do COALESCE and NULLIF do?",
          "`COALESCE(a, b, c)` returns the first non-NULL argument, which is great for defaults. `NULLIF(a, b)` returns NULL if `a = b`, else `a`; a common use is avoiding division by zero with `x / NULLIF(y, 0)`.",
          "`IFNULL`, `NVL` and `ISNULL` are two-argument, database-specific versions of `COALESCE`.",
          "SELECT name, COALESCE(email, 'no email') AS email FROM employees WHERE id IN (4, 5);\nSELECT 100 / NULLIF(0, 0) AS safe_division;"),
        Q("I", "How do you convert between data types?",
          "`CAST(expr AS type)` is standard SQL; PostgreSQL and Snowflake also accept `expr::type`. Converting text to numbers or dates can fail, so some databases offer `TRY_CAST` which returns NULL instead.",
          "SQLite uses flexible \"type affinity\", so `CAST('42abc' AS INTEGER)` gives 42 rather than an error; stricter databases reject it.",
          "SELECT CAST('42' AS INTEGER) + 1 AS n, CAST(7 AS REAL) / 2 AS half, typeof(CAST(3.9 AS INTEGER)) AS t, CAST(3.9 AS INTEGER) AS truncated;"),
        Q("I", "How do you work with dates in SQL?",
          "Store dates as a proper DATE/TIMESTAMP type (or ISO-8601 text in SQLite). Common functions: current date (`CURRENT_DATE`), extracting parts (`EXTRACT(YEAR FROM d)`, `strftime('%Y', d)` in SQLite), adding intervals, and differences between dates.",
          "ISO format (`YYYY-MM-DD`) sorts correctly as text, which is why SQLite recommends it.",
          "SELECT order_date,\n       strftime('%Y', order_date) AS year,\n       strftime('%m', order_date) AS month,\n       date(order_date, '+30 days') AS due,\n       julianday('2024-12-31') - julianday(order_date) AS days_to_year_end\nFROM orders LIMIT 3;"),
        Q("B", "Can you do calculations in the SELECT list?",
          "Yes. Any expression works: arithmetic on columns, function calls, string building, CASE. The database computes it for every row.",
          "Name computed columns with `AS`, otherwise the result column is called something like `quantity * unit_price`.",
          "SELECT order_id, product_id, quantity, unit_price, quantity * unit_price AS line_total\nFROM order_items WHERE order_id = 3;"),
        Q("I", "How do you put a CASE inside an aggregate (conditional aggregation)?",
          "Wrap a CASE in `SUM` or `COUNT`: `SUM(CASE WHEN status = 'delivered' THEN 1 ELSE 0 END)`. Many databases also support `COUNT(*) FILTER (WHERE ...)`.",
          "This is how you pivot rows into columns without a PIVOT keyword.",
          "SELECT\n  SUM(CASE WHEN status = 'delivered' THEN 1 ELSE 0 END) AS delivered,\n  SUM(CASE WHEN status = 'pending' THEN 1 ELSE 0 END)   AS pending,\n  SUM(CASE WHEN status = 'cancelled' THEN 1 ELSE 0 END) AS cancelled\nFROM orders;"),
        Q("A", "How do NULLs behave in expressions and functions?",
          "Almost any operation with NULL gives NULL: `NULL + 1`, `'a' || NULL` and `NULL = NULL` all produce NULL/unknown. Aggregates like `SUM` and `AVG` skip NULLs; `COUNT(*)` counts rows but `COUNT(col)` skips NULLs.",
          "Use `COALESCE` to supply defaults and `IS [NOT] DISTINCT FROM` (or `IS` in SQLite) for NULL-safe comparisons.",
          "SELECT NULL + 1 AS plus, 'a' || NULL AS concat, NULL = NULL AS eq, NULL IS NULL AS is_null,\n       COUNT(*) AS all_rows, COUNT(email) AS with_email FROM employees;"),
        Q("I", "How do you extract year and month for reporting?",
          "Use date-part functions: `strftime('%Y-%m', d)` in SQLite, `DATE_TRUNC('month', d)` in PostgreSQL/Snowflake, `FORMAT(d, 'yyyy-MM')` in SQL Server. Then `GROUP BY` the result.",
          "`DATE_TRUNC` keeps a real date (the first of the month), which sorts and joins better than text.",
          "SELECT strftime('%Y-%m', order_date) AS month, COUNT(*) AS orders\nFROM orders GROUP BY month ORDER BY month;"),
    ]),

    S("Aggregation & GROUP BY", "📊", "Module 4", [
        Q("B", "What are aggregate functions?",
          "Functions that turn many rows into one value: `COUNT`, `SUM`, `AVG`, `MIN`, `MAX` (plus `GROUP_CONCAT`/`STRING_AGG`/`LISTAGG`, `STDDEV` and others).",
          "Without `GROUP BY` they summarise the whole table into one row.",
          "SELECT COUNT(*) AS employees, SUM(salary) AS payroll, AVG(salary) AS avg_salary,\n       MIN(salary) AS lowest, MAX(salary) AS highest\nFROM employees;"),
        Q("B", "What's the difference between COUNT(*), COUNT(column) and COUNT(DISTINCT column)?",
          "`COUNT(*)` counts rows. `COUNT(col)` counts rows where `col` is not NULL. `COUNT(DISTINCT col)` counts unique non-NULL values.",
          "Divya has no department and Priya has no email, so the three counts differ in MegaMart.",
          "SELECT COUNT(*) AS rows_, COUNT(dept_id) AS with_dept, COUNT(DISTINCT dept_id) AS departments,\n       COUNT(email) AS with_email\nFROM employees;"),
        Q("B", "How does GROUP BY work?",
          "It splits rows into groups that share the same values in the GROUP BY columns, and aggregates are computed per group, giving one output row per group.",
          "Every non-aggregated column in `SELECT` must be in `GROUP BY` (SQLite and MySQL are lenient, but relying on that is a bug).",
          "SELECT category, COUNT(*) AS products, MIN(price) AS cheapest, MAX(price) AS priciest\nFROM products GROUP BY category ORDER BY products DESC, category;"),
        Q("I", "WHERE vs HAVING: what's the difference?",
          "`WHERE` filters rows *before* grouping and can't use aggregates. `HAVING` filters groups *after* aggregation and can.",
          "Put everything you can in `WHERE`; it shrinks the data before the expensive grouping step.",
          "SELECT customer_id, COUNT(*) AS orders\nFROM orders\nWHERE status <> 'cancelled'\nGROUP BY customer_id\nHAVING COUNT(*) >= 2\nORDER BY orders DESC, customer_id;"),
        Q("I", "How do you calculate revenue per order?",
          "Aggregate the order lines: `SUM(quantity * unit_price)` grouped by `order_id`. Joining to `orders` lets you filter by status or date.",
          "Store the price at the time of sale (`unit_price`) in the order line, not just a link to `products.price`, because prices change.",
          "SELECT o.id, o.status, SUM(oi.quantity * oi.unit_price) AS revenue\nFROM orders o JOIN order_items oi ON oi.order_id = o.id\nGROUP BY o.id, o.status\nORDER BY revenue DESC LIMIT 5;"),
        Q("I", "Can you GROUP BY several columns or expressions?",
          "Yes. Groups are formed per unique combination: `GROUP BY country, city`, or by an expression like `strftime('%Y-%m', order_date)`.",
          "Many databases allow `GROUP BY 1, 2` (column positions), which is handy but fragile if the SELECT list changes.",
          "SELECT country, COUNT(*) AS customers\nFROM customers GROUP BY country HAVING COUNT(*) > 1;"),
        Q("I", "How do you concatenate values within a group?",
          "`GROUP_CONCAT(col, sep)` in SQLite and MySQL, `STRING_AGG(col, sep)` in PostgreSQL and SQL Server, `LISTAGG(col, sep)` in Oracle and Snowflake.",
          "Order inside the aggregate isn't guaranteed unless the database supports `WITHIN GROUP (ORDER BY ...)` or `ORDER BY` inside the call.",
          "SELECT d.name AS department, GROUP_CONCAT(e.name, ', ') AS people\nFROM departments d JOIN employees e ON e.dept_id = d.id\nGROUP BY d.name ORDER BY d.name;"),
        Q("A", "Why does AVG sometimes give a surprising result with NULLs?",
          "`AVG` ignores NULLs, so it divides by the number of non-NULL values, not the number of rows. If NULL should count as 0, use `AVG(COALESCE(col, 0))`.",
          "Decide deliberately: is a missing value \"zero\" or \"unknown\"? The two give different averages.",
          "WITH scores(v) AS (VALUES (10), (20), (NULL))\nSELECT AVG(v) AS avg_ignoring_null, AVG(COALESCE(v, 0)) AS avg_null_as_zero FROM scores;"),
        Q("I", "What happens to NULL values in GROUP BY?",
          "All NULLs are grouped together into a single group, even though `NULL = NULL` isn't true in comparisons.",
          "In MegaMart, Divya (no department) forms her own `dept_id = NULL` group.",
          "SELECT dept_id, COUNT(*) AS people FROM employees GROUP BY dept_id ORDER BY dept_id;"),
        Q("A", "What are ROLLUP, CUBE and GROUPING SETS?",
          "Extensions that compute several levels of grouping in one query. `ROLLUP(a, b)` adds subtotals per `a` and a grand total; `CUBE(a, b)` adds every combination; `GROUPING SETS` lists exactly which groupings you want.",
          "SQLite doesn't have them, but PostgreSQL, SQL Server, Oracle and Snowflake do. You can emulate a grand total with `UNION ALL`.",
          "-- PostgreSQL / Snowflake\nSELECT category, name, SUM(price) AS total\nFROM products\nGROUP BY ROLLUP (category, name);", run=False, play=False, lang="text"),
    ]),

    S("Joins", "🔗", "Module 5", [
        Q("B", "What is an INNER JOIN?",
          "It returns only rows that have a match in both tables according to the `ON` condition. Rows without a partner disappear.",
          "Customers who never ordered (Neha, Omar) don't appear when you inner-join customers to orders.",
          "SELECT c.name, o.id AS order_id, o.status\nFROM customers c\nINNER JOIN orders o ON o.customer_id = c.id\nORDER BY o.id LIMIT 5;"),
        Q("B", "What is a LEFT JOIN?",
          "It keeps every row of the left table; where there's no match in the right table, the right-hand columns are NULL.",
          "It's the go-to join for \"all X, with their Y if any\".",
          "SELECT c.name, COUNT(o.id) AS orders\nFROM customers c\nLEFT JOIN orders o ON o.customer_id = c.id\nGROUP BY c.id, c.name\nORDER BY orders, c.name LIMIT 4;"),
        Q("I", "How do RIGHT JOIN and FULL OUTER JOIN work?",
          "`RIGHT JOIN` keeps every row of the right table (a mirror of `LEFT JOIN`). `FULL OUTER JOIN` keeps unmatched rows from both sides, with NULLs where there's no partner.",
          "Most people rewrite `RIGHT JOIN` as a `LEFT JOIN` with the tables swapped, for readability. SQLite supports both since version 3.39.",
          "SELECT e.name AS employee, d.name AS department\nFROM employees e\nFULL OUTER JOIN departments d ON d.id = e.dept_id\nWHERE e.id IS NULL OR d.id IS NULL;"),
        Q("I", "What is a CROSS JOIN?",
          "The Cartesian product: every row of one table combined with every row of the other (m × n rows), with no join condition.",
          "Useful for generating combinations (every product × every month), and dangerous by accident: forgetting a join condition on two big tables explodes the row count.",
          "SELECT COUNT(*) AS combinations FROM departments CROSS JOIN products;"),
        Q("I", "What is a self join?",
          "Joining a table to itself with two aliases, typically for hierarchies or comparing rows. For example, employees joined to employees gives each person's manager.",
          "Use a LEFT JOIN so the CEO (no manager) isn't dropped.",
          "SELECT e.name AS employee, m.name AS manager\nFROM employees e\nLEFT JOIN employees m ON m.id = e.manager_id\nORDER BY e.id LIMIT 5;"),
        Q("I", "How do you find rows with no match (an anti-join)?",
          "`LEFT JOIN ... WHERE right.id IS NULL`, or `WHERE NOT EXISTS (SELECT 1 FROM ... WHERE ...)`. Both return left rows that have no partner.",
          "Prefer `NOT EXISTS` over `NOT IN`, which breaks when the subquery contains NULLs.",
          "SELECT c.name FROM customers c\nWHERE NOT EXISTS (SELECT 1 FROM orders o WHERE o.customer_id = c.id);"),
        Q("I", "How do you join three or more tables?",
          "Chain joins, each with its own `ON` condition: orders → customers, orders → order_items → products. The database optimises the join order for you.",
          "Draw the relationships first; every join should follow a foreign key (or a clearly intended key).",
          "SELECT c.name AS customer, p.name AS product, oi.quantity\nFROM orders o\nJOIN customers c    ON c.id = o.customer_id\nJOIN order_items oi ON oi.order_id = o.id\nJOIN products p     ON p.id = oi.product_id\nWHERE o.id = 5;"),
        Q("A", "Why can a join produce more rows than you expect?",
          "Joining on a column that isn't unique on at least one side multiplies rows: each left row matches every right row with the same key. Summing after such a join double-counts.",
          "Aggregate each side first (or join on unique keys) before joining. `DISTINCT` hides the symptom, not the cause.",
          "-- each customer's orders x each of their order lines -> revenue counted once per line, order count inflated\nSELECT c.name, COUNT(o.id) AS inflated_order_count, COUNT(DISTINCT o.id) AS real_orders\nFROM customers c JOIN orders o ON o.customer_id = c.id JOIN order_items oi ON oi.order_id = o.id\nGROUP BY c.name ORDER BY real_orders DESC LIMIT 3;"),
        Q("A", "Filtering a LEFT JOIN in ON vs WHERE: what's the difference?",
          "A condition in `ON` decides which right rows match, so left rows are still kept. The same condition in `WHERE` runs after the join and removes rows where the right side is NULL, silently turning the LEFT JOIN into an INNER JOIN.",
          "Put filters on the *right* table in the `ON` clause when you want to keep all left rows.",
          "SELECT COUNT(*) AS in_on\nFROM customers c LEFT JOIN orders o ON o.customer_id = c.id AND o.status = 'pending';\nSELECT COUNT(*) AS in_where\nFROM customers c LEFT JOIN orders o ON o.customer_id = c.id WHERE o.status = 'pending';"),
        Q("I", "What are UNION and UNION ALL?",
          "They stack the results of two queries with the same number and types of columns. `UNION` removes duplicates (extra work); `UNION ALL` keeps everything and is faster.",
          "`INTERSECT` returns rows in both results and `EXCEPT` (`MINUS` in Oracle) returns rows in the first but not the second.",
          "SELECT city FROM customers WHERE country = 'India'\nUNION\nSELECT location FROM departments\nORDER BY 1;"),
    ]),

    S("Subqueries & CTEs", "🧩", "Module 6", [
        Q("I", "What is a scalar subquery?",
          "A subquery that returns exactly one value, usable anywhere a value is: in `SELECT`, `WHERE` or a calculation.",
          "If it accidentally returns more than one row, most databases raise an error (SQLite just takes the first).",
          "SELECT name, salary, salary - (SELECT AVG(salary) FROM employees) AS vs_average\nFROM employees ORDER BY vs_average DESC LIMIT 3;"),
        Q("I", "How do IN and EXISTS subqueries differ?",
          "`IN (subquery)` compares a value with the set the subquery returns. `EXISTS (subquery)` is true if the subquery returns at least one row, and is usually correlated to the outer row.",
          "Modern optimisers often run both the same way. The real difference is NULL handling with `NOT IN`.",
          "SELECT name FROM products\nWHERE id IN (SELECT product_id FROM order_items WHERE quantity >= 5);\nSELECT name FROM products p\nWHERE EXISTS (SELECT 1 FROM order_items oi WHERE oi.product_id = p.id AND oi.quantity >= 5);"),
        Q("A", "What is a correlated subquery?",
          "A subquery that references columns from the outer query, so it's logically evaluated once per outer row. For example, \"employees earning more than their department's average\".",
          "They're clear but can be slow on large tables; rewriting with a join to an aggregated subquery or a window function is often faster.",
          "SELECT e.name, e.salary, e.dept_id\nFROM employees e\nWHERE e.salary > (SELECT AVG(salary) FROM employees x WHERE x.dept_id = e.dept_id)\nORDER BY e.dept_id;"),
        Q("I", "What is a CTE (WITH clause)?",
          "A Common Table Expression: a named temporary result defined with `WITH name AS (...)` that the main query can use like a table. You can chain several CTEs.",
          "CTEs make complex queries readable step by step, like variables in code.",
          "WITH revenue AS (\n  SELECT order_id, SUM(quantity * unit_price) AS total FROM order_items GROUP BY order_id\n)\nSELECT o.customer_id, SUM(r.total) AS spent\nFROM orders o JOIN revenue r ON r.order_id = o.id\nGROUP BY o.customer_id ORDER BY spent DESC LIMIT 3;"),
        Q("A", "What is a recursive CTE?",
          "A CTE that refers to itself: an anchor query produces the starting rows, then a recursive part joins back to the CTE until no new rows appear. It's used for hierarchies (org charts, categories) and series.",
          "Always make sure the recursion ends; a missing stop condition loops until the database's limit is hit.",
          "WITH RECURSIVE chain(id, name, manager_id, depth) AS (\n  SELECT id, name, manager_id, 0 FROM employees WHERE id = 8\n  UNION ALL\n  SELECT e.id, e.name, e.manager_id, c.depth + 1\n  FROM employees e JOIN chain c ON e.id = c.manager_id\n)\nSELECT depth, name FROM chain;"),
        Q("I", "What is a derived table (subquery in FROM)?",
          "A subquery in the `FROM` clause that acts as a temporary table and must have an alias. It's the older equivalent of a CTE.",
          "Use it to aggregate first and then filter or join the aggregated result.",
          "SELECT category, avg_price FROM (\n  SELECT category, AVG(price) AS avg_price FROM products GROUP BY category\n) AS t\nWHERE avg_price > 5000 ORDER BY avg_price DESC;"),
        Q("I", "How do you generate a series of numbers or dates?",
          "Use a recursive CTE counting up, or built-ins like `generate_series()` (PostgreSQL, SQLite with the series extension) and `GENERATOR` (Snowflake).",
          "Joining a date series to your data reveals missing days, since days with no orders still appear with 0.",
          "WITH RECURSIVE months(m) AS (\n  SELECT '2024-01-01' UNION ALL SELECT date(m, '+1 month') FROM months WHERE m < '2024-08-01'\n)\nSELECT strftime('%Y-%m', m) AS month,\n       (SELECT COUNT(*) FROM orders WHERE strftime('%Y-%m', order_date) = strftime('%Y-%m', m)) AS orders\nFROM months;"),
        Q("A", "Subquery, CTE, temp table or view: when do you use which?",
          "Subquery or CTE: for one query, to keep logic readable. Temp table: when an intermediate result is reused many times or is big enough to benefit from indexes. View: to reuse a query across many queries and users. Materialised view: to store precomputed results of expensive queries.",
          "CTEs may be inlined or materialised depending on the database; check the plan when performance matters.",
          None),
        Q("I", "How do you find the maximum per group with a subquery?",
          "Join each row to its group's maximum: `WHERE (dept_id, salary) IN (SELECT dept_id, MAX(salary) ...)`, or a correlated subquery. Ties return several rows.",
          "Window functions (`RANK()` / `ROW_NUMBER()`) are the modern and more flexible way; see the next module.",
          "SELECT e.dept_id, e.name, e.salary\nFROM employees e\nWHERE e.salary = (SELECT MAX(salary) FROM employees x WHERE x.dept_id = e.dept_id)\nORDER BY e.dept_id;"),
    ]),
]
