"""Sections 13-16: security & administration, NoSQL, SQL for analytics, interview questions."""
from schema import Q, S

SECTIONS = [
    S("Security & Administration", "🛡️", "Module 13", [
        Q("I", "What is SQL injection, and how do you prevent it?",
          "An attack where user input is concatenated into SQL and changes the query, for example `' OR '1'='1` logging in without a password or `'; DROP TABLE users; --`. Prevent it with parameterised queries (bind variables), never string-building SQL from input.",
          "Also apply least privilege, validate input and use ORM or query builders safely. Parameterisation is the real fix.",
          "import sqlite3\ncon = sqlite3.connect(':memory:')\ncon.execute('CREATE TABLE users (name TEXT, pw TEXT)')\ncon.execute(\"INSERT INTO users VALUES ('ada', 's3cret')\")\nattack = \"x' OR '1'='1\"\n# UNSAFE: f\"SELECT * FROM users WHERE pw = '{attack}'\" returns every user\nprint(con.execute('SELECT * FROM users WHERE pw = ?', (attack,)).fetchall())   # []", lang="python"),
        Q("I", "What do GRANT and REVOKE do?",
          "They give or remove privileges (SELECT, INSERT, UPDATE, DELETE, CREATE, USAGE, …) on objects to users or roles: `GRANT SELECT ON orders TO analyst_role;`.",
          "Grant to roles, not individual users, then assign roles to people. That's role-based access control (RBAC).",
          "CREATE ROLE analyst;\nGRANT SELECT ON ALL TABLES IN SCHEMA sales TO analyst;\nGRANT analyst TO priya;\nREVOKE SELECT ON sales.salaries FROM analyst;", run=False, play=False, lang="text"),
        Q("I", "What is the principle of least privilege?",
          "Every user, role and application gets only the permissions it needs, and nothing more. Reporting tools get read-only access, and apps don't connect as an admin.",
          "If credentials leak, the damage is limited to what that account could do.",
          None),
        Q("I", "How can views improve security?",
          "Grant access to a view that exposes only safe columns or rows (for example, employees without salaries, or only the user's region) instead of the base table. Secure views in Snowflake also hide the view definition.",
          "Row-level security policies (PostgreSQL RLS, Snowflake row access policies) do this more flexibly.",
          "CREATE VIEW employee_directory AS SELECT id, name, dept_id, email FROM employees;\nSELECT * FROM employee_directory LIMIT 3;"),
        Q("I", "Why back up databases, and what are the common strategies?",
          "To recover from hardware failure, bugs, accidental deletes and ransomware. Strategies: full, incremental and differential backups, continuous WAL/log archiving for point-in-time recovery, and replicas (which are not backups on their own).",
          "A backup you've never restored is a hope, not a backup. Test restores regularly and define RPO/RTO targets.",
          None),
        Q("I", "What is data masking?",
          "Hiding sensitive values (PAN, phone, email, salary) from users who don't need them, statically (in copied test data) or dynamically at query time based on the user's role.",
          "Snowflake's masking policies and SQL Server's dynamic data masking apply rules without changing the stored data.",
          "SELECT name, substr(email, 1, 2) || '***' || substr(email, instr(email, '@')) AS masked_email\nFROM employees WHERE email IS NOT NULL LIMIT 3;"),
        Q("A", "What are stored procedures and triggers?",
          "A stored procedure is named, reusable code stored in the database and called explicitly (`CALL proc()`). A trigger runs automatically on an event (INSERT, UPDATE or DELETE on a table), for example audit logging or keeping a column in sync.",
          "Triggers are powerful but \"invisible\", so document them well. Heavy business logic usually lives better in application code.",
          "CREATE TABLE price_log (product_id INTEGER, old_price INTEGER, new_price INTEGER);\nCREATE TRIGGER log_price AFTER UPDATE OF price ON products\nBEGIN INSERT INTO price_log VALUES (OLD.id, OLD.price, NEW.price); END;\nUPDATE products SET price = 999 WHERE id = 2;\nSELECT * FROM price_log;"),
    ]),

    S("NoSQL & Modern Databases", "🌐", "Module 14", [
        Q("I", "What are the main types of NoSQL databases?",
          "Document (MongoDB, Couchbase: JSON-like documents), key-value (Redis, DynamoDB: fast lookups by key), wide-column (Cassandra, HBase: huge write-heavy tables) and graph (Neo4j: nodes and relationships).",
          "Choose based on the access pattern: lookups by key, flexible documents, massive writes or relationship traversal.",
          None),
        Q("A", "What is the CAP theorem?",
          "A distributed data store can't guarantee all three of Consistency (every read sees the latest write), Availability (every request gets a response) and Partition tolerance (it keeps working despite network splits) at the same time. Since partitions happen, systems choose CP or AP behaviour during one.",
          "PACELC extends it: even without partitions, there's a trade-off between latency and consistency.",
          None),
        Q("I", "What are replication and sharding?",
          "Replication copies the same data to several servers for availability and read scaling (primary-replica). Sharding splits data across servers by a shard key (for example customer_id ranges or hashes) so each holds a part, which scales writes and storage.",
          "A bad shard key creates hot spots; cross-shard joins and transactions are hard.",
          None),
        Q("I", "What is a data warehouse, data lake and lakehouse?",
          "A warehouse (Snowflake, BigQuery, Redshift) stores cleaned, structured data optimised for SQL analytics. A lake (S3, ADLS) stores raw files of any format cheaply. A lakehouse (Databricks, Snowflake with Iceberg tables) adds warehouse features (ACID tables, SQL, governance) on top of lake storage.",
          "A typical flow: land raw data in the lake, transform it with ELT (for example dbt), and serve curated tables from the warehouse.",
          None),
        Q("I", "Row-oriented vs column-oriented storage: what's the difference?",
          "Row stores keep each row's values together, which makes single-row reads and writes fast (OLTP). Column stores keep each column's values together, so they read only the needed columns and compress well, which is great for scanning and aggregating (OLAP).",
          "That's why `SELECT *` is especially wasteful in a warehouse: you pay to read every column.",
          None),
        Q("I", "How do databases store semi-structured JSON?",
          "Relational databases now have JSON types and functions: PostgreSQL `jsonb` with `->>`, MySQL `JSON`, SQLite's `json_extract`, and Snowflake's `VARIANT` with `col:path` and `FLATTEN`.",
          "Use JSON for truly variable attributes; keep core, frequently filtered fields as real columns.",
          "SELECT json_extract('{\"sku\": \"LP14\", \"specs\": {\"ram\": 16, \"ssd\": 512}}', '$.specs.ram') AS ram_gb,\n       json_array_length('[1, 2, 3]') AS items;"),
        Q("I", "What is ETL vs ELT?",
          "ETL: Extract, Transform (outside the database, in an ETL tool), then Load the result. ELT: Extract, Load raw data into the warehouse, then Transform inside it with SQL. ELT dominates in cloud warehouses, which have cheap, scalable compute.",
          "dbt is the popular tool for the \"T\" in ELT: versioned, tested SQL models.",
          None),
    ]),

    S("SQL for Analytics", "📈", "Module 15", [
        Q("I", "How do you pivot rows into columns?",
          "Use conditional aggregation, `SUM(CASE WHEN category = 'X' THEN value END) AS x`, one expression per output column. Some databases also have a `PIVOT` operator (SQL Server, Oracle, Snowflake).",
          "Conditional aggregation works everywhere and makes the output columns explicit.",
          "SELECT strftime('%Y-%m', o.order_date) AS month,\n  SUM(CASE WHEN p.category = 'Electronics' THEN oi.quantity * oi.unit_price ELSE 0 END) AS electronics,\n  SUM(CASE WHEN p.category = 'Furniture'   THEN oi.quantity * oi.unit_price ELSE 0 END) AS furniture\nFROM orders o JOIN order_items oi ON oi.order_id = o.id JOIN products p ON p.id = oi.product_id\nGROUP BY month ORDER BY month;"),
        Q("I", "How do you calculate month-over-month growth?",
          "Aggregate per month, then use `LAG(revenue) OVER (ORDER BY month)` to get the previous month and compute `(current - previous) * 100.0 / previous`.",
          "Use `NULLIF(previous, 0)` to avoid dividing by zero for new products or months.",
          "WITH m AS (\n  SELECT strftime('%Y-%m', o.order_date) AS month, SUM(oi.quantity * oi.unit_price) AS revenue\n  FROM orders o JOIN order_items oi ON oi.order_id = o.id WHERE o.status <> 'cancelled' GROUP BY month\n)\nSELECT month, revenue,\n       ROUND((revenue - LAG(revenue) OVER (ORDER BY month)) * 100.0 / NULLIF(LAG(revenue) OVER (ORDER BY month), 0), 1) AS growth_pct\nFROM m;"),
        Q("A", "How do you do a cohort (signup month) analysis?",
          "Assign each customer to a cohort (their signup or first-order month), then count how many are active in each later period, grouped by cohort.",
          "It's the standard way to measure retention.",
          "WITH firsts AS (\n  SELECT customer_id, MIN(strftime('%Y-%m', order_date)) AS cohort FROM orders GROUP BY customer_id\n)\nSELECT f.cohort, COUNT(DISTINCT f.customer_id) AS customers,\n       COUNT(DISTINCT CASE WHEN strftime('%Y-%m', o.order_date) > f.cohort THEN o.customer_id END) AS came_back\nFROM firsts f JOIN orders o ON o.customer_id = f.customer_id\nGROUP BY f.cohort ORDER BY f.cohort;"),
        Q("I", "How do you find each customer's first (or latest) order?",
          "`ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY order_date)` and keep row 1 (use `DESC` for the latest). `MIN(order_date)` works if you only need the date.",
          "The ROW_NUMBER pattern also returns the other columns of that row, which MIN can't.",
          "SELECT customer_id, id AS first_order, order_date FROM (\n  SELECT o.*, ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY order_date) AS rn FROM orders o\n) WHERE rn = 1 ORDER BY customer_id LIMIT 5;"),
        Q("I", "How do you bucket values into ranges (histogram)?",
          "Use CASE for custom bands, or integer arithmetic for equal-width buckets: `(price / 10000) * 10000`, then GROUP BY the bucket.",
          "Always label buckets clearly and include open-ended ones (\"50k+\").",
          "SELECT CASE WHEN salary < 60000 THEN '< 60k' WHEN salary < 90000 THEN '60k - 90k' ELSE '90k+' END AS band,\n       COUNT(*) AS people\nFROM employees GROUP BY band ORDER BY MIN(salary);"),
        Q("A", "How do you calculate a 3-month moving average?",
          "`AVG(value) OVER (ORDER BY month ROWS BETWEEN 2 PRECEDING AND CURRENT ROW)` averages the current and previous two rows.",
          "The first rows average fewer values; filter them out or mark them if that's misleading.",
          "WITH m AS (\n  SELECT strftime('%Y-%m', order_date) AS month, COUNT(*) AS orders FROM orders GROUP BY month\n)\nSELECT month, orders, ROUND(AVG(orders) OVER (ORDER BY month ROWS BETWEEN 2 PRECEDING AND CURRENT ROW), 2) AS moving_avg_3\nFROM m;"),
        Q("I", "How does SQL analytics work in Snowflake?",
          "It's standard SQL plus warehouse extras: `QUALIFY` to filter window results, `VARIANT` + `FLATTEN` for JSON, `DATE_TRUNC`, Time Travel (`AT(OFFSET => -3600)`) and zero-copy `CLONE`. Compute (virtual warehouses) is separate from storage.",
          "See MegaByte's Snowflake Academy for 338 questions on it.",
          "-- Snowflake: latest order per customer without a subquery\nSELECT customer_id, id, order_date\nFROM orders\nQUALIFY ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY order_date DESC) = 1;", run=False, play=False, lang="text"),
        Q("I", "How do you compare NULLs safely?",
          "`a = b` is unknown when either side is NULL. Use `a IS NOT DISTINCT FROM b` (standard, PostgreSQL, Snowflake), `a IS b` (SQLite) or `a <=> b` (MySQL), which treat two NULLs as equal.",
          "Important when joining or de-duplicating on nullable columns.",
          "SELECT NULL = NULL AS equals, NULL IS NULL AS is_op, 1 IS NOT DISTINCT FROM 1 AS not_distinct;"),
    ]),

    S("Interview & Scenario Questions", "🎯", "Whole course", [
        Q("A", "How do you find the second-highest salary?",
          "`DENSE_RANK()` in a subquery and pick rank 2. That handles ties and generalises to the Nth highest. Alternatives: `MAX(salary) WHERE salary < (SELECT MAX(salary))`, or `DISTINCT ... ORDER BY DESC LIMIT 1 OFFSET 1`.",
          "State how you handle ties, because interviewers want to hear it.",
          "SELECT DISTINCT salary FROM (\n  SELECT salary, DENSE_RANK() OVER (ORDER BY salary DESC) AS r FROM employees\n) WHERE r = 2;"),
        Q("A", "How do you find employees who earn more than their manager?",
          "Self-join employees (e) to employees (m) on `e.manager_id = m.id` and filter on `e.salary > m.salary`.",
          "A classic self-join question. If nobody qualifies you get an empty result, which is a correct answer.",
          "SELECT e.name AS employee, e.salary, m.name AS manager, m.salary AS manager_salary\nFROM employees e JOIN employees m ON m.id = e.manager_id\nWHERE e.salary > m.salary;"),
        Q("A", "How do you find duplicate values?",
          "`GROUP BY` the column(s) and `HAVING COUNT(*) > 1`. To see the full duplicate rows, join back or use `COUNT(*) OVER (PARTITION BY ...)`.",
          "Then fix the root cause with a UNIQUE constraint.",
          "SELECT salary, COUNT(*) AS people, GROUP_CONCAT(name, ', ') AS who\nFROM employees GROUP BY salary HAVING COUNT(*) > 1;"),
        Q("A", "How do you find the department with the highest average salary?",
          "Group by department, compute AVG, then order descending and take 1, or use `RANK()` to include ties.",
          "Join to departments for the name, and decide whether employees without a department should count.",
          "SELECT d.name, ROUND(AVG(e.salary)) AS avg_salary\nFROM employees e JOIN departments d ON d.id = e.dept_id\nGROUP BY d.name ORDER BY avg_salary DESC LIMIT 1;"),
        Q("A", "How do you find customers who ordered in at least N different months?",
          "Filter orders to the period, count `DISTINCT` months per customer, and keep customers with `HAVING COUNT(DISTINCT month) >= N`.",
          "Set N to the total number of months and it becomes relational division: \"customers who ordered in *every* month\".",
          "SELECT customer_id, COUNT(DISTINCT strftime('%m', order_date)) AS months\nFROM orders WHERE order_date BETWEEN '2024-01-01' AND '2024-06-30'\nGROUP BY customer_id HAVING months >= 2 ORDER BY months DESC, customer_id;"),
        Q("A", "How do you find gaps in a sequence of ids?",
          "Use `LEAD(id) OVER (ORDER BY id)` and report places where the next id isn't `id + 1`. Or anti-join against a generated series.",
          "Gaps are normal in auto-increment ids; this matters for things like invoice numbers.",
          "WITH ids(id) AS (VALUES (1), (2), (3), (5), (6), (9))\nSELECT id + 1 AS gap_starts, next_id - 1 AS gap_ends FROM (\n  SELECT id, LEAD(id) OVER (ORDER BY id) AS next_id FROM ids\n) WHERE next_id - id > 1;"),
        Q("A", "How do you find the top-selling product in each category?",
          "Aggregate quantity sold per product, rank within category with `RANK() OVER (PARTITION BY category ORDER BY sold DESC)`, and keep rank 1.",
          "\"Aggregate, then rank, then filter\" solves most top-N-per-group questions.",
          "WITH sold AS (\n  SELECT p.category, p.name, SUM(oi.quantity) AS units\n  FROM products p JOIN order_items oi ON oi.product_id = p.id GROUP BY p.id\n), ranked AS (\n  SELECT *, RANK() OVER (PARTITION BY category ORDER BY units DESC) AS r FROM sold\n)\nSELECT category, name, units FROM ranked WHERE r = 1 ORDER BY category;"),
        Q("A", "Scenario: a report query on a huge orders table takes minutes. What do you check?",
          "1) The query plan: full scans, bad join order, row estimates. 2) Filters: SARGable and indexed (or clustering/partition columns in a warehouse). 3) Select only needed columns, and aggregate before joining. 4) Missing or outdated statistics. 5) Locks or concurrent load. 6) For recurring reports, a summary table or materialised view.",
          "Explain it as measure → hypothesise → change one thing → measure again.",
          None),
        Q("A", "Scenario: the same customer appears twice with different ids. How do you fix and prevent it?",
          "Find duplicates by a normalised natural key (lower-cased trimmed email or phone), pick a survivor, re-point child rows (orders) to the survivor in a transaction, delete the extras, and add a UNIQUE constraint (on a normalised column) to prevent recurrence.",
          "Log the merge so it can be audited and reversed.",
          None),
        Q("A", "How do you calculate each employee's salary rank within their department and overall?",
          "Use two window functions in the same SELECT: one partitioned by department and one over the whole table.",
          "Windows with different PARTITION BY clauses can sit side by side.",
          "SELECT name, dept_id, salary,\n       RANK() OVER (PARTITION BY dept_id ORDER BY salary DESC) AS dept_rank,\n       RANK() OVER (ORDER BY salary DESC) AS company_rank\nFROM employees WHERE dept_id IS NOT NULL ORDER BY company_rank LIMIT 6;"),
        Q("A", "How do you get the cumulative percentage of revenue by customer (Pareto)?",
          "Aggregate revenue per customer, order descending, and compute a running `SUM` divided by the grand total `SUM() OVER ()`.",
          "This shows how few customers make up most of the revenue (the 80/20 rule).",
          "WITH spend AS (\n  SELECT o.customer_id, SUM(oi.quantity * oi.unit_price) AS revenue\n  FROM orders o JOIN order_items oi ON oi.order_id = o.id GROUP BY o.customer_id\n)\nSELECT customer_id, revenue,\n       ROUND(SUM(revenue) OVER (ORDER BY revenue DESC ROWS UNBOUNDED PRECEDING) * 100.0 / SUM(revenue) OVER (), 1) AS cumulative_pct\nFROM spend ORDER BY revenue DESC;"),
    ]),
]
