// Generated by Java Academy source/generate_data.py; do not edit by hand.
window.JAVA_DATA = {
  "sections": [
    {
      "title": "Java Fundamentals & JVM Architecture",
      "icon": "☕",
      "ref": "Module 1",
      "questions": [
        {
          "level": "B",
          "q": "What is the difference between JDK, JRE, and JVM?",
          "a": "JVM (Java Virtual Machine) executes compiled bytecode. JRE (Java Runtime Environment) = JVM + core class libraries needed to run Java apps. JDK (Java Development Kit) = JRE + development tools like javac compiler, jdb debugger, and javadoc.",
          "e": "Write Once, Run Anywhere (WORA) is achieved because the compiler emits platform-independent .class bytecode that any OS-specific JVM can execute.",
          "code": "public class Main {\n    public static void main(String[] args) {\n        System.out.println(\"Java Version: \" + System.getProperty(\"java.version\"));\n        System.out.println(\"JVM Vendor: \" + System.getProperty(\"java.vm.vendor\"));\n        System.out.println(\"Architecture: \" + System.getProperty(\"os.arch\"));\n    }\n}",
          "play": true,
          "lang": "java",
          "id": 1,
          "sid": 1,
          "stitle": "Java Fundamentals & JVM Architecture",
          "sicon": "☕",
          "sref": "Module 1"
        },
        {
          "level": "B",
          "q": "Why is the main method static in Java?",
          "a": "The JVM invokes public static void main(String[] args) before any object of the class is instantiated. If main were not static, the JVM wouldn't know which constructor to call to instantiate the class.",
          "e": "The signature must match precisely. If static is omitted, runtime throws 'NoSuchMethodError: main'.",
          "code": "public class App {\n    public static void main(String[] args) {\n        System.out.println(\"Args received: \" + args.length);\n    }\n}",
          "play": true,
          "lang": "java",
          "id": 2,
          "sid": 1,
          "stitle": "Java Fundamentals & JVM Architecture",
          "sicon": "☕",
          "sref": "Module 1"
        },
        {
          "level": "I",
          "q": "How does the JIT (Just-In-Time) compiler work inside HotSpot?",
          "a": "The JVM starts executing bytecode via an interpreter for fast startup. Frequently executed 'hot spots' are identified by profiling counters and compiled directly into native machine code by Tiered Compilers (C1 Client for quick optimization, C2 Server for heavy optimizations).",
          "e": "HotSpot performs inlining, loop unrolling, escape analysis, and dead code elimination dynamically at runtime based on actual branch probabilities.",
          "code": "public class HotSpotDemo {\n    public static void main(String[] args) {\n        long sum = 0;\n        for (int i = 0; i < 1_000_000; i++) {\n            sum += i;\n        }\n        System.out.println(\"Sum: \" + sum);\n    }\n}",
          "play": true,
          "lang": "java",
          "id": 3,
          "sid": 1,
          "stitle": "Java Fundamentals & JVM Architecture",
          "sicon": "☕",
          "sref": "Module 1"
        },
        {
          "level": "I",
          "q": "What is the difference between Stack Memory and Heap Memory?",
          "a": "Stack memory stores local primitive variables and references to objects for each executing thread. Heap memory stores all instantiated objects. Stack is LIFO, thread-safe, and very fast; Heap is shared across threads and managed by the Garbage Collector.",
          "e": "When a thread exceeds its stack depth (e.g. infinite recursion), a StackOverflowError occurs. When the heap runs out of allocation space, an OutOfMemoryError: Java heap space is thrown.",
          "code": "public class MemoryDemo {\n    public static void main(String[] args) {\n        int x = 42; // on stack\n        String text = new String(\"Heap Object\"); // ref on stack, object on heap\n        System.out.println(\"x = \" + x + \", text = \" + text);\n    }\n}",
          "play": true,
          "lang": "java",
          "id": 4,
          "sid": 1,
          "stitle": "Java Fundamentals & JVM Architecture",
          "sicon": "☕",
          "sref": "Module 1"
        },
        {
          "level": "B",
          "q": "What is bytecode and why is it important?",
          "a": "Bytecode is the intermediate instruction representation generated by javac (.class file). It is not machine code for any specific CPU, but rather instructions for the virtual processor modeled by the JVM.",
          "e": "This separation decouples application code from host hardware, making Java portable and enabling diverse languages (Kotlin, Scala, Clojure) to target the same runtime.",
          "code": "public class BytecodeDemo {\n    public static void main(String[] args) {\n        System.out.println(\"Target: JVM Bytecode Specification\");\n    }\n}",
          "play": true,
          "lang": "java",
          "id": 5,
          "sid": 1,
          "stitle": "Java Fundamentals & JVM Architecture",
          "sicon": "☕",
          "sref": "Module 1"
        }
      ],
      "id": 1
    },
    {
      "title": "Primitives, Wrappers & Memory Semantics",
      "icon": "🔢",
      "ref": "Module 2",
      "questions": [
        {
          "level": "B",
          "q": "What are the 8 primitive types in Java and their sizes?",
          "a": "byte (8-bit), short (16-bit), int (32-bit), long (64-bit), float (32-bit IEEE 754), double (64-bit IEEE 754), char (16-bit Unicode UTF-16), and boolean (true/false).",
          "e": "Primitives live directly on the stack when declared locally, avoiding heap allocation and pointer dereference overhead.",
          "code": "public class Primitives {\n    public static void main(String[] args) {\n        System.out.println(\"Byte range: \" + Byte.MIN_VALUE + \" to \" + Byte.MAX_VALUE);\n        System.out.println(\"Int range: \" + Integer.MIN_VALUE + \" to \" + Integer.MAX_VALUE);\n    }\n}",
          "play": true,
          "lang": "java",
          "id": 6,
          "sid": 2,
          "stitle": "Primitives, Wrappers & Memory Semantics",
          "sicon": "🔢",
          "sref": "Module 2"
        },
        {
          "level": "I",
          "q": "What is the Integer Cache trap in autoboxing?",
          "a": "Java caches Integer wrapper objects for values between -128 and 127 (inclusive). Autoboxing values in this range returns the same cached instance (so == returns true). Outside this range, a new object is allocated, making == return false.",
          "e": "Always use .equals() rather than == when comparing wrapper objects in Java to compare value rather than object reference.",
          "code": "public class IntegerCacheDemo {\n    public static void main(String[] args) {\n        Integer a = 127, b = 127;\n        Integer c = 128, d = 128;\n        System.out.println(\"127 == 127: \" + (a == b));\n        System.out.println(\"128 == 128: \" + (c == d));\n        System.out.println(\"128 equals 128: \" + c.equals(d));\n    }\n}",
          "play": true,
          "lang": "java",
          "id": 7,
          "sid": 2,
          "stitle": "Primitives, Wrappers & Memory Semantics",
          "sicon": "🔢",
          "sref": "Module 2"
        },
        {
          "level": "I",
          "q": "Is Java pass-by-value or pass-by-reference?",
          "a": "Java is STRICTLY pass-by-value, always. For primitive types, the actual bit value is copied. For object types, the reference (memory address) value is copied. You can mutate the contents of the passed object, but reassigning the parameter does not affect the caller's reference.",
          "e": "A common misunderstanding: passing an object does not pass the pointer itself by reference; it passes a copy of the pointer address by value.",
          "code": "public class PassByValue {\n    static void modify(int num, StringBuilder sb) {\n        num = 99;\n        sb.append(\" World\");\n        sb = new StringBuilder(\"Goodbye\"); // rebinds local copy only\n    }\n\n    public static void main(String[] args) {\n        int x = 10;\n        StringBuilder message = new StringBuilder(\"Hello\");\n        modify(x, message);\n        System.out.println(\"x = \" + x);\n        System.out.println(\"message = \" + message);\n    }\n}",
          "play": true,
          "lang": "java",
          "id": 8,
          "sid": 2,
          "stitle": "Primitives, Wrappers & Memory Semantics",
          "sicon": "🔢",
          "sref": "Module 2"
        }
      ],
      "id": 2
    },
    {
      "title": "Strings, Immutability & Text Blocks",
      "icon": "🔤",
      "ref": "Module 3",
      "questions": [
        {
          "level": "B",
          "q": "Why are String objects immutable in Java?",
          "a": "Security (parameters like DB connection URLs, file paths cannot be hijacked), Thread Safety (read-only state eliminates synchronization), String Pool Caching (shared literals save massive heap space), and HashCode Caching (hash is computed once and cached).",
          "e": "Because String is immutable, String.hashCode() is calculated on first invocation and stored in a private hash field, making HashMap lookups lightning fast.",
          "code": "public class StringPool {\n    public static void main(String[] args) {\n        String s1 = \"Java\";\n        String s2 = \"Java\";\n        String s3 = new String(\"Java\");\n        System.out.println(\"s1 == s2: \" + (s1 == s2));\n        System.out.println(\"s1 == s3: \" + (s1 == s3));\n        System.out.println(\"s1.equals(s3): \" + s1.equals(s3));\n        System.out.println(\"s1 == s3.intern(): \" + (s1 == s3.intern()));\n    }\n}",
          "play": true,
          "lang": "java",
          "id": 9,
          "sid": 3,
          "stitle": "Strings, Immutability & Text Blocks",
          "sicon": "🔤",
          "sref": "Module 3"
        },
        {
          "level": "I",
          "q": "What is the difference between String, StringBuilder, and StringBuffer?",
          "a": "String is immutable; each modification creates a new object. StringBuilder is mutable and not thread-safe (fastest for single-threaded loops). StringBuffer is mutable and thread-safe (methods are synchronized, incurring lock overhead).",
          "e": "Inside loops, always prefer StringBuilder over String concatenation '+' to avoid creating O(N^2) discarded intermediate String objects.",
          "code": "public class StringBuilderDemo {\n    public static void main(String[] args) {\n        StringBuilder sb = new StringBuilder(\"Start\");\n        for (int i = 1; i <= 3; i++) {\n            sb.append(\" -> \").append(i);\n        }\n        System.out.println(sb.toString());\n    }\n}",
          "play": true,
          "lang": "java",
          "id": 10,
          "sid": 3,
          "stitle": "Strings, Immutability & Text Blocks",
          "sicon": "🔤",
          "sref": "Module 3"
        },
        {
          "level": "B",
          "q": "What are Text Blocks in modern Java (Java 15+)?",
          "a": "Text Blocks use triple quotes (\\\"\\\"\\\") to declare multi-line string literals without manual escape sequences (\\\\n or \\\\t). Common incidental white space is automatically stripped based on the closing delimiter indentation.",
          "e": "Ideal for JSON, SQL queries, HTML, and regex without messy concatenation.",
          "code": "public class TextBlocks {\n    public static void main(String[] args) {\n        String json = \"\"\"\n            {\n              \"name\": \"Java Academy\",\n              \"language\": \"Java 21\"\n            }\n            \"\"\";\n        System.out.println(json.strip());\n    }\n}",
          "play": true,
          "lang": "java",
          "id": 11,
          "sid": 3,
          "stitle": "Strings, Immutability & Text Blocks",
          "sicon": "🔤",
          "sref": "Module 3"
        }
      ],
      "id": 3
    },
    {
      "title": "Object-Oriented Programming in Java",
      "icon": "🏗️",
      "ref": "Module 4",
      "questions": [
        {
          "level": "B",
          "q": "What is the difference between method overloading and method overriding?",
          "a": "Overloading: multiple methods in the same class have the same name but different parameter lists (compile-time/static polymorphism). Overriding: subclass provides specific implementation for a method declared in superclass with identical signature (runtime/dynamic polymorphism).",
          "e": "In overriding, return type can be covariant (subtype), and access level cannot be made more restrictive.",
          "code": "class Parent {\n    String role() { return \"Parent\"; }\n}\nclass Child extends Parent {\n    @Override\n    String role() { return \"Child\"; }\n}\npublic class PolyDemo {\n    public static void main(String[] args) {\n        Parent p = new Child();\n        System.out.println(p.role()); // dynamic dispatch\n    }\n}",
          "play": true,
          "lang": "java",
          "id": 12,
          "sid": 4,
          "stitle": "Object-Oriented Programming in Java",
          "sicon": "🏗️",
          "sref": "Module 4"
        },
        {
          "level": "I",
          "q": "Why does Java not support multiple inheritance with classes?",
          "a": "To prevent the 'Diamond Problem', where class D extends both B and C (which both extend A and override method m()). The compiler would face ambiguity as to which implementation D should inherit. Multiple inheritance of type is supported via interfaces.",
          "e": "With interface default methods, Java resolves diamond conflicts by requiring the implementing class to explicitly override the conflicting method.",
          "code": "interface A {\n    default String hello() { return \"A\"; }\n}\ninterface B {\n    default String hello() { return \"B\"; }\n}\nclass C implements A, B {\n    @Override\n    public String hello() {\n        return A.super.hello() + \" & \" + B.super.hello();\n    }\n}\npublic class DiamondDemo {\n    public static void main(String[] args) {\n        System.out.println(new C().hello());\n    }\n}",
          "play": true,
          "lang": "java",
          "id": 13,
          "sid": 4,
          "stitle": "Object-Oriented Programming in Java",
          "sicon": "🏗️",
          "sref": "Module 4"
        },
        {
          "level": "I",
          "q": "What is the contract between equals() and hashCode()?",
          "a": "If two objects are equal according to equals(Object), their hashCode() MUST return the exact same integer. If two objects have the same hashCode(), they are not necessarily equal (hash collision).",
          "e": "Breaking this contract breaks Hash-based collections (HashMap, HashSet). If equals is overridden without hashCode, an object inserted into a HashMap cannot be retrieved.",
          "code": "import java.util.Objects;\n\nclass User {\n    private final int id;\n    private final String name;\n\n    User(int id, String name) {\n        this.id = id;\n        this.name = name;\n    }\n\n    @Override\n    public boolean equals(Object o) {\n        if (this == o) return true;\n        if (!(o instanceof User u)) return false;\n        return id == u.id && Objects.equals(name, u.name);\n    }\n\n    @Override\n    public int hashCode() {\n        return Objects.hash(id, name);\n    }\n}\npublic class ContractDemo {\n    public static void main(String[] args) {\n        User u1 = new User(1, \"Matru\");\n        User u2 = new User(1, \"Matru\");\n        System.out.println(\"equals: \" + u1.equals(u2));\n        System.out.println(\"same hash: \" + (u1.hashCode() == u2.hashCode()));\n    }\n}",
          "play": true,
          "lang": "java",
          "id": 14,
          "sid": 4,
          "stitle": "Object-Oriented Programming in Java",
          "sicon": "🏗️",
          "sref": "Module 4"
        }
      ],
      "id": 4
    },
    {
      "title": "Interfaces, Sealed Classes & Records",
      "icon": "📜",
      "ref": "Module 5",
      "questions": [
        {
          "level": "B",
          "q": "What are Records in Java 14+?",
          "a": "Records are immutable data-carrier classes declared with the record keyword. The compiler automatically generates private final fields, a canonical constructor, public accessors, equals(), hashCode(), and toString().",
          "e": "Records can implement interfaces and declare static members, but they cannot extend other classes because they implicitly extend java.lang.Record.",
          "code": "public record Point(int x, int y) {\n    public double distanceFromOrigin() {\n        return Math.hypot(x, y);\n    }\n}\nclass Main {\n    public static void main(String[] args) {\n        Point p = new Point(3, 4);\n        System.out.println(p);\n        System.out.println(\"x: \" + p.x() + \", distance: \" + p.distanceFromOrigin());\n    }\n}",
          "play": true,
          "lang": "java",
          "id": 15,
          "sid": 5,
          "stitle": "Interfaces, Sealed Classes & Records",
          "sicon": "📜",
          "sref": "Module 5"
        },
        {
          "level": "A",
          "q": "What are Sealed Classes and Interfaces (Java 17+)?",
          "a": "Sealed classes restrict which other classes can extend or implement them using the sealed and permits keywords. Permitted subclasses must be final, sealed, or non-sealed.",
          "e": "Enables algebraic data types and exhaustive pattern matching in switch expressions without requiring a default clause.",
          "code": "sealed interface Shape permits Circle, Rectangle {}\nfinal record Circle(double radius) implements Shape {}\nfinal record Rectangle(double w, double h) implements Shape {}\n\npublic class SealedDemo {\n    static double area(Shape s) {\n        return switch (s) {\n            case Circle c -> Math.PI * c.radius() * c.radius();\n            case Rectangle r -> r.w() * r.h();\n        };\n    }\n    public static void main(String[] args) {\n        System.out.println(\"Circle area: \" + Math.round(area(new Circle(10))));\n        System.out.println(\"Rect area: \" + area(new Rectangle(4, 5)));\n    }\n}",
          "play": true,
          "lang": "java",
          "id": 16,
          "sid": 5,
          "stitle": "Interfaces, Sealed Classes & Records",
          "sicon": "📜",
          "sref": "Module 5"
        }
      ],
      "id": 5
    },
    {
      "title": "Exception Handling & Resource Management",
      "icon": "🚨",
      "ref": "Module 6",
      "questions": [
        {
          "level": "B",
          "q": "What is the difference between Checked and Unchecked exceptions?",
          "a": "Checked exceptions (subclasses of Exception except RuntimeException) are checked at compile time; methods must either catch them or declare them in throws. Unchecked exceptions (subclasses of RuntimeException and Error) occur at runtime and are not enforced by the compiler.",
          "e": "Examples of checked: IOException, SQLException. Unchecked: NullPointerException, ArrayIndexOutOfBoundsException, IllegalArgumentException.",
          "code": "public class ExceptionDemo {\n    public static void main(String[] args) {\n        try {\n            int result = Integer.parseInt(\"not-a-number\");\n        } catch (NumberFormatException e) {\n            System.out.println(\"Caught unchecked exception: \" + e.getClass().getSimpleName());\n        }\n    }\n}",
          "play": true,
          "lang": "java",
          "id": 17,
          "sid": 6,
          "stitle": "Exception Handling & Resource Management",
          "sicon": "🚨",
          "sref": "Module 6"
        },
        {
          "level": "I",
          "q": "How does Try-With-Resources guarantee clean closing of resources?",
          "a": "Any resource implementing java.lang.AutoCloseable or java.io.Closeable opened in the try(...) header is automatically closed at the end of the block in reverse order of declaration, even if an exception is thrown.",
          "e": "Prevents resource leaks (file descriptors, sockets, database connections) and replaces verbose nested finally blocks.",
          "code": "class Resource implements AutoCloseable {\n    private final String name;\n    Resource(String name) { this.name = name; }\n    @Override\n    public void close() {\n        System.out.println(\"Closed: \" + name);\n    }\n}\npublic class AutoCloseDemo {\n    public static void main(String[] args) {\n        try (Resource r1 = new Resource(\"DatabaseCon\");\n             Resource r2 = new Resource(\"FileHandle\")) {\n            System.out.println(\"Executing query...\");\n        }\n    }\n}",
          "play": true,
          "lang": "java",
          "id": 18,
          "sid": 6,
          "stitle": "Exception Handling & Resource Management",
          "sicon": "🚨",
          "sref": "Module 6"
        }
      ],
      "id": 6
    },
    {
      "title": "Java Collections Framework",
      "icon": "🗂️",
      "ref": "Module 7",
      "questions": [
        {
          "level": "B",
          "q": "What is the difference between ArrayList and LinkedList?",
          "a": "ArrayList uses a dynamically resizing array: O(1) random access by index, O(1) amortized append, but O(N) insertion/deletion in the middle. LinkedList uses a doubly linked list: O(N) traversal access, but O(1) insertion/deletion once the node position is located.",
          "e": "In modern hardware, ArrayList is almost always faster than LinkedList due to CPU cache locality and lower memory footprint per element (no Node pointer overhead).",
          "code": "import java.util.*;\n\npublic class ListDemo {\n    public static void main(String[] args) {\n        List<String> list = new ArrayList<>(List.of(\"Java\", \"Kotlin\", \"Scala\"));\n        list.add(\"Groovy\");\n        System.out.println(\"First element: \" + list.get(0));\n        System.out.println(\"Total: \" + list.size());\n    }\n}",
          "play": true,
          "lang": "java",
          "id": 19,
          "sid": 7,
          "stitle": "Java Collections Framework",
          "sicon": "🗂️",
          "sref": "Module 7"
        },
        {
          "level": "A",
          "q": "How does HashMap work internally in Java 8+?",
          "a": "HashMap is an array of Node buckets. The hash of a key determines its bucket index: hash(key) & (n - 1). Collisions are stored in linked lists. When a bucket reaches >= 8 elements and total table size >= 64, the linked list is transformed into a Red-Black Tree (TreeNode), lowering worst-case lookup from O(N) to O(log N).",
          "e": "The default load factor is 0.75, balancing time and space overhead. When the size reaches capacity * loadFactor, the bucket array doubles in size (rehashing).",
          "code": "import java.util.*;\n\npublic class HashMapDemo {\n    public static void main(String[] args) {\n        Map<String, Integer> scores = new HashMap<>();\n        scores.put(\"Ada\", 95);\n        scores.put(\"James\", 99);\n        scores.putIfAbsent(\"Duke\", 100);\n        System.out.println(\"James score: \" + scores.get(\"James\"));\n        System.out.println(\"Keys: \" + scores.keySet());\n    }\n}",
          "play": true,
          "lang": "java",
          "id": 20,
          "sid": 7,
          "stitle": "Java Collections Framework",
          "sicon": "🗂️",
          "sref": "Module 7"
        },
        {
          "level": "I",
          "q": "What is ConcurrentHashMap and how does it achieve high concurrency?",
          "a": "Unlike Hashtable or Collections.synchronizedMap() which lock the entire map on every operation, ConcurrentHashMap uses fine-grained lock striping and compare-and-swap (CAS) operations on individual bucket heads. Reads are non-blocking.",
          "e": "It does not allow null keys or values to avoid ambiguity in concurrent environments.",
          "code": "import java.util.concurrent.ConcurrentHashMap;\n\npublic class ConcurrentMapDemo {\n    public static void main(String[] args) {\n        ConcurrentHashMap<String, Integer> map = new ConcurrentHashMap<>();\n        map.put(\"active_users\", 10);\n        map.compute(\"active_users\", (k, v) -> v + 1);\n        System.out.println(\"Users: \" + map.get(\"active_users\"));\n    }\n}",
          "play": true,
          "lang": "java",
          "id": 21,
          "sid": 7,
          "stitle": "Java Collections Framework",
          "sicon": "🗂️",
          "sref": "Module 7"
        }
      ],
      "id": 7
    },
    {
      "title": "Generics & Type Erasure",
      "icon": "🧬",
      "ref": "Module 8",
      "questions": [
        {
          "level": "I",
          "q": "What is Type Erasure in Java Generics?",
          "a": "Java generics are purely a compile-time mechanism. During compilation, the compiler checks types and then erases generic type parameters to their raw type (or first bound, e.g. Object or Number), inserting casts where necessary. At runtime, List<String> and List<Integer> are both simply List.",
          "e": "Because of type erasure, you cannot do: new T(), instanceof List<String>, or create generic arrays like new T[10].",
          "code": "import java.util.*;\n\npublic class ErasureDemo {\n    public static void main(String[] args) {\n        List<String> l1 = new ArrayList<>();\n        List<Integer> l2 = new ArrayList<>();\n        System.out.println(\"Same runtime class: \" + (l1.getClass() == l2.getClass()));\n    }\n}",
          "play": true,
          "lang": "java",
          "id": 22,
          "sid": 8,
          "stitle": "Generics & Type Erasure",
          "sicon": "🧬",
          "sref": "Module 8"
        },
        {
          "level": "A",
          "q": "What is the PECS rule (Producer Extends, Consumer Super)?",
          "a": "PECS determines whether to use <? extends T> or <? super T>. If a parameterized collection produces items (read-only), use <? extends T>. If a collection consumes items (write-only), use <? super T>. If you do both, use exact type <T>.",
          "e": "Collections.copy(List<? super T> dest, List<? extends T> src) is the canonical textbook example of PECS in the standard library.",
          "code": "import java.util.*;\n\npublic class PecsDemo {\n    static double sumOfNumbers(List<? extends Number> list) {\n        double sum = 0.0;\n        for (Number n : list) sum += n.doubleValue();\n        return sum;\n    }\n\n    public static void main(String[] args) {\n        List<Integer> ints = List.of(1, 2, 3, 4);\n        List<Double> doubles = List.of(1.5, 2.5);\n        System.out.println(\"Ints sum: \" + sumOfNumbers(ints));\n        System.out.println(\"Doubles sum: \" + sumOfNumbers(doubles));\n    }\n}",
          "play": true,
          "lang": "java",
          "id": 23,
          "sid": 8,
          "stitle": "Generics & Type Erasure",
          "sicon": "🧬",
          "sref": "Module 8"
        }
      ],
      "id": 8
    },
    {
      "title": "Functional Interfaces & Lambdas",
      "icon": "λ",
      "ref": "Module 9",
      "questions": [
        {
          "level": "B",
          "q": "What is a Functional Interface in Java?",
          "a": "An interface that declares exactly one abstract method (Single Abstract Method or SAM). It may declare any number of default or static methods. The optional @FunctionalInterface annotation informs the compiler to enforce this rule.",
          "e": "Standard core functional interfaces: Predicate<T> (T -> boolean), Function<T,R> (T -> R), Consumer<T> (T -> void), Supplier<T> (() -> T).",
          "code": "import java.util.function.*;\n\npublic class LambdaDemo {\n    public static void main(String[] args) {\n        Predicate<String> isShort = s -> s.length() < 5;\n        Function<String, Integer> lengthFunc = String::length;\n        System.out.println(\"Is 'Java' short? \" + isShort.test(\"Java\"));\n        System.out.println(\"Length of 'Enterprise': \" + lengthFunc.apply(\"Enterprise\"));\n    }\n}",
          "play": true,
          "lang": "java",
          "id": 24,
          "sid": 9,
          "stitle": "Functional Interfaces & Lambdas",
          "sicon": "λ",
          "sref": "Module 9"
        },
        {
          "level": "I",
          "q": "What are Method References (::) and their four kinds?",
          "a": "Shorthand syntax for lambdas that only call an existing method: 1) Static method: Math::max, 2) Instance method of particular object: System.out::println, 3) Instance method of arbitrary object of particular type: String::toLowerCase, 4) Constructor: ArrayList::new.",
          "e": "Improves readability and avoids boilerplates like (x) -> System.out.println(x).",
          "code": "import java.util.*;\n\npublic class MethodRefDemo {\n    public static void main(String[] args) {\n        List<String> names = List.of(\"ada\", \"james\", \"duke\");\n        names.stream()\n             .map(String::toUpperCase)\n             .forEach(System.out::println);\n    }\n}",
          "play": true,
          "lang": "java",
          "id": 25,
          "sid": 9,
          "stitle": "Functional Interfaces & Lambdas",
          "sicon": "λ",
          "sref": "Module 9"
        }
      ],
      "id": 9
    },
    {
      "title": "Stream API & Data Pipelines",
      "icon": "🌊",
      "ref": "Module 10",
      "questions": [
        {
          "level": "B",
          "q": "What is the difference between intermediate and terminal operations in Streams?",
          "a": "Intermediate operations (filter, map, flatMap, sorted, distinct) are lazy and return a new Stream without performing computation. Terminal operations (collect, forEach, reduce, count, findFirst) trigger stream execution and consume the stream.",
          "e": "A stream can only be consumed once. Attempting to invoke a terminal operation on a stream that has already been closed throws IllegalStateException.",
          "code": "import java.util.*;\n\npublic class StreamDemo {\n    public static void main(String[] args) {\n        List<Integer> numbers = List.of(1, 2, 3, 4, 5, 6);\n        int sumOfEvenSquares = numbers.stream()\n            .filter(n -> n % 2 == 0)\n            .map(n -> n * n)\n            .reduce(0, Integer::sum);\n        System.out.println(\"Result: \" + sumOfEvenSquares);\n    }\n}",
          "play": true,
          "lang": "java",
          "id": 26,
          "sid": 10,
          "stitle": "Stream API & Data Pipelines",
          "sicon": "🌊",
          "sref": "Module 10"
        },
        {
          "level": "I",
          "q": "How does flatMap() differ from map()?",
          "a": "map(T -> R) transforms each element into exactly one output element (1-to-1 mapping). flatMap(T -> Stream<R>) transforms each element into a stream and flattens all nested streams into a single top-level stream (1-to-many flattening).",
          "e": "Essential when dealing with nested lists or collections inside objects.",
          "code": "import java.util.*;\n\npublic class FlatMapDemo {\n    public static void main(String[] args) {\n        List<List<String>> matrix = List.of(\n            List.of(\"Java\", \"JVM\"),\n            List.of(\"Spring\", \"Quarkus\")\n        );\n        List<String> flat = matrix.stream()\n            .flatMap(Collection::stream)\n            .toList();\n        System.out.println(flat);\n    }\n}",
          "play": true,
          "lang": "java",
          "id": 27,
          "sid": 10,
          "stitle": "Stream API & Data Pipelines",
          "sicon": "🌊",
          "sref": "Module 10"
        },
        {
          "level": "A",
          "q": "How do Collectors.groupingBy and partitioningBy work?",
          "a": "groupingBy(classifier) aggregates elements into a Map<K, List<V>> based on key evaluation. partitioningBy(predicate) divides elements into a Map<Boolean, List<V>> based on a true/false condition.",
          "e": "Both accept downstream collectors like counting(), summingInt(), or mapping().",
          "code": "import java.util.*;\nimport java.util.stream.Collectors;\n\npublic class GroupingDemo {\n    public static void main(String[] args) {\n        List<String> words = List.of(\"apple\", \"banana\", \"apricot\", \"cherry\", \"avocado\");\n        Map<Character, Long> counts = words.stream()\n            .collect(Collectors.groupingBy(w -> w.charAt(0), Collectors.counting()));\n        System.out.println(counts);\n    }\n}",
          "play": true,
          "lang": "java",
          "id": 28,
          "sid": 10,
          "stitle": "Stream API & Data Pipelines",
          "sicon": "🌊",
          "sref": "Module 10"
        }
      ],
      "id": 10
    },
    {
      "title": "Multithreading & Core Concurrency",
      "icon": "🧵",
      "ref": "Module 11",
      "questions": [
        {
          "level": "B",
          "q": "What is the difference between Runnable and Callable?",
          "a": "Runnable represents a task with void run() that returns no result and cannot throw checked exceptions. Callable<V> represents a task with V call() throws Exception that returns a computed value and can throw checked exceptions.",
          "e": "Callable is executed via ExecutorService.submit() which returns a Future<V> handle.",
          "code": "import java.util.concurrent.*;\n\npublic class CallableDemo {\n    public static void main(String[] args) throws Exception {\n        Callable<String> task = () -> \"Task Completed in \" + Thread.currentThread().getName();\n        ExecutorService executor = Executors.newSingleThreadExecutor();\n        Future<String> future = executor.submit(task);\n        System.out.println(future.get());\n        executor.shutdown();\n    }\n}",
          "play": true,
          "lang": "java",
          "id": 29,
          "sid": 11,
          "stitle": "Multithreading & Core Concurrency",
          "sicon": "🧵",
          "sref": "Module 11"
        },
        {
          "level": "I",
          "q": "What does the volatile keyword guarantee in Java?",
          "a": "Visibility: changes made by one thread to a volatile variable are immediately flushed to main memory and visible to all other threads (prevents CPU cache incoherence). Ordering: prevents instruction reordering around the volatile read/write via memory barriers.",
          "e": "volatile does NOT guarantee atomicity! For atomic compound operations like count++, use AtomicInteger or synchronized locks.",
          "code": "import java.util.concurrent.atomic.AtomicInteger;\n\npublic class AtomicDemo {\n    public static void main(String[] args) {\n        AtomicInteger counter = new AtomicInteger(10);\n        int updated = counter.incrementAndGet();\n        System.out.println(\"Counter: \" + updated);\n    }\n}",
          "play": true,
          "lang": "java",
          "id": 30,
          "sid": 11,
          "stitle": "Multithreading & Core Concurrency",
          "sicon": "🧵",
          "sref": "Module 11"
        }
      ],
      "id": 11
    },
    {
      "title": "Modern Concurrency & Virtual Threads",
      "icon": "⚡",
      "ref": "Module 12",
      "questions": [
        {
          "level": "I",
          "q": "What are Virtual Threads in Java 21 (Project Loom)?",
          "a": "Virtual threads are lightweight, user-mode threads managed by the JVM rather than the operating system. While OS platform threads consume ~1MB of stack memory each, virtual threads consume only hundreds of bytes, enabling applications to spawn millions of concurrent threads without thread pool overhead.",
          "e": "When a virtual thread executes a blocking I/O operation (socket read, sleep), the JVM unmounts it from its underlying OS carrier thread, freeing the carrier thread to run other virtual threads.",
          "code": "public class VirtualThreadDemo {\n    public static void main(String[] args) throws Exception {\n        Thread vThread = Thread.ofVirtual().start(() -> {\n            System.out.println(\"Running on: \" + Thread.currentThread());\n        });\n        vThread.join();\n        System.out.println(\"Is virtual: \" + vThread.isVirtual());\n    }\n}",
          "play": true,
          "lang": "java",
          "id": 31,
          "sid": 12,
          "stitle": "Modern Concurrency & Virtual Threads",
          "sicon": "⚡",
          "sref": "Module 12"
        },
        {
          "level": "A",
          "q": "What is thread pinning in Virtual Threads?",
          "a": "Pinning occurs when a virtual thread is executing inside a synchronized block/method or invoking native JNI methods. When pinned, the virtual thread cannot unmount from its carrier thread upon blocking, temporarily monopolizing the underlying OS thread.",
          "e": "In modern Java 21 applications, replace synchronized blocks with java.util.concurrent.locks.ReentrantLock to ensure virtual threads always unmount cleanly during blocking operations.",
          "code": "import java.util.concurrent.locks.ReentrantLock;\n\npublic class LockDemo {\n    private static final ReentrantLock lock = new ReentrantLock();\n\n    public static void main(String[] args) {\n        lock.lock();\n        try {\n            System.out.println(\"ReentrantLock ensures clean virtual thread unmounting\");\n        } finally {\n            lock.unlock();\n        }\n    }\n}",
          "play": true,
          "lang": "java",
          "id": 32,
          "sid": 12,
          "stitle": "Modern Concurrency & Virtual Threads",
          "sicon": "⚡",
          "sref": "Module 12"
        }
      ],
      "id": 12
    },
    {
      "title": "Modern Java Evolution (Java 11 - 21)",
      "icon": "🚀",
      "ref": "Module 13",
      "questions": [
        {
          "level": "B",
          "q": "How does Pattern Matching for instanceof work (Java 16+)?",
          "a": "Eliminates the tedious boilerplate of explicit type casting. You write if (obj instanceof String s) { ... } and s is automatically cast and scoped to the conditional branch.",
          "e": "Scope extends logically to downstream expressions, e.g. if (obj instanceof String s && s.length() > 5).",
          "code": "public class PatternInstanceof {\n    static void printDetails(Object obj) {\n        if (obj instanceof String s) {\n            System.out.println(\"String of length: \" + s.length());\n        } else if (obj instanceof Integer i) {\n            System.out.println(\"Integer doubled: \" + (i * 2));\n        }\n    }\n\n    public static void main(String[] args) {\n        printDetails(\"Java Academy\");\n        printDetails(21);\n    }\n}",
          "play": true,
          "lang": "java",
          "id": 33,
          "sid": 13,
          "stitle": "Modern Java Evolution (Java 11 - 21)",
          "sicon": "🚀",
          "sref": "Module 13"
        },
        {
          "level": "I",
          "q": "What are Switch Expressions and the yield keyword (Java 14+)?",
          "a": "Switch can be used as an expression that produces a value directly using the arrow (->) syntax without break fall-through. If a block is required for a case, yield is used to return the value.",
          "e": "The compiler enforces completeness (all possible enum or sealed type cases must be handled).",
          "code": "public class SwitchExpression {\n    public static void main(String[] args) {\n        int day = 3;\n        String type = switch (day) {\n            case 1, 7 -> \"Weekend\";\n            case 2, 3, 4, 5, 6 -> \"Weekday\";\n            default -> throw new IllegalArgumentException(\"Invalid day\");\n        };\n        System.out.println(\"Day \" + day + \" is a \" + type);\n    }\n}",
          "play": true,
          "lang": "java",
          "id": 34,
          "sid": 13,
          "stitle": "Modern Java Evolution (Java 11 - 21)",
          "sicon": "🚀",
          "sref": "Module 13"
        },
        {
          "level": "I",
          "q": "What are Sequenced Collections in Java 21?",
          "a": "Java 21 introduced SequencedCollection, SequencedSet, and SequencedMap interfaces with uniform methods for accessing first/last elements (addFirst, addLast, getFirst, getLast, removeFirst, removeLast) and reversed() views.",
          "e": "Resolves the long-standing inconsistency where accessing the last element required different code for ArrayList (list.get(list.size()-1)), LinkedHashSet (iterator traversal), and TreeSet (set.last()).",
          "code": "import java.util.*;\n\npublic class SequencedDemo {\n    public static void main(String[] args) {\n        List<String> list = new ArrayList<>(List.of(\"alpha\", \"beta\", \"gamma\"));\n        System.out.println(\"First: \" + list.getFirst());\n        System.out.println(\"Last: \" + list.getLast());\n        System.out.println(\"Reversed: \" + list.reversed());\n    }\n}",
          "play": true,
          "lang": "java",
          "id": 35,
          "sid": 13,
          "stitle": "Modern Java Evolution (Java 11 - 21)",
          "sicon": "🚀",
          "sref": "Module 13"
        }
      ],
      "id": 13
    },
    {
      "title": "JVM Internals, GC & Memory Tuning",
      "icon": "⚙️",
      "ref": "Module 14",
      "questions": [
        {
          "level": "I",
          "q": "What is Metaspace and how does it differ from the old PermGen?",
          "a": "Metaspace replaced PermGen in Java 8. It holds class metadata, constant pool, and method bytecode. Crucially, Metaspace is allocated from native memory rather than contiguous heap memory, resizing dynamically up to OS physical limits (or MaxMetaspaceSize).",
          "e": "Eliminated the notorious java.lang.OutOfMemoryError: PermGen space that plagued enterprise classloaders.",
          "code": "public class MetaspaceDemo {\n    public static void main(String[] args) {\n        long maxMemory = Runtime.getRuntime().maxMemory();\n        long totalMemory = Runtime.getRuntime().totalMemory();\n        System.out.println(\"Max Heap (MB): \" + (maxMemory / (1024 * 1024)));\n        System.out.println(\"Total Allocated Heap (MB): \" + (totalMemory / (1024 * 1024)));\n    }\n}",
          "play": true,
          "lang": "java",
          "id": 36,
          "sid": 14,
          "stitle": "JVM Internals, GC & Memory Tuning",
          "sicon": "⚙️",
          "sref": "Module 14"
        },
        {
          "level": "A",
          "q": "How does the G1 (Garbage-First) GC differ from ZGC?",
          "a": "G1 divides heap into ~2048 equal regions and prioritizes collecting regions with the most garbage ('garbage first') with target pause times (e.g. 200ms). ZGC (Z Garbage Collector) is a generational concurrent low-latency collector that performs all major phases concurrently, keeping max pause times strictly under 1 millisecond regardless of multi-terabyte heap sizes.",
          "e": "ZGC achieves sub-millisecond pauses using colored pointers and load barriers.",
          "code": "public class GCDemo {\n    public static void main(String[] args) {\n        System.out.println(\"Available processors: \" + Runtime.getRuntime().availableProcessors());\n    }\n}",
          "play": true,
          "lang": "java",
          "id": 37,
          "sid": 14,
          "stitle": "JVM Internals, GC & Memory Tuning",
          "sicon": "⚙️",
          "sref": "Module 14"
        }
      ],
      "id": 14
    },
    {
      "title": "File I/O, NIO.2 & Buffers",
      "icon": "📁",
      "ref": "Module 15",
      "questions": [
        {
          "level": "B",
          "q": "What is the difference between java.io and java.nio?",
          "a": "java.io is stream-oriented and blocking (byte by byte / char by char with thread blocked on wait). java.nio (New I/O) is buffer- and channel-oriented and non-blocking (selectors allow one thread to monitor multiple I/O channels simultaneously).",
          "e": "NIO.2 (Java 7+) added the java.nio.file package (Path, Files) which revolutionized modern file manipulation.",
          "code": "import java.nio.file.Path;\n\npublic class NioDemo {\n    public static void main(String[] args) {\n        Path path = Path.of(\"app\", \"config\", \"application.properties\");\n        System.out.println(\"Filename: \" + path.getFileName());\n        System.out.println(\"Parent: \" + path.getParent());\n    }\n}",
          "play": true,
          "lang": "java",
          "id": 38,
          "sid": 15,
          "stitle": "File I/O, NIO.2 & Buffers",
          "sicon": "📁",
          "sref": "Module 15"
        }
      ],
      "id": 15
    },
    {
      "title": "Unit Testing with JUnit 5 & Mockito",
      "icon": "🧪",
      "ref": "Module 16",
      "questions": [
        {
          "level": "B",
          "q": "What are the core annotations in JUnit 5 (Jupiter)?",
          "a": "@Test (marks test method), @BeforeEach (runs before every test), @AfterEach, @BeforeAll (static method run once before all tests), @AfterAll, @Disabled (skips test), and @ParameterizedTest (runs with multiple test arguments).",
          "e": "In JUnit 5, test classes and methods do not need to be public (package-private is standard).",
          "code": "class Calculator {\n    int add(int a, int b) { return a + b; }\n}\npublic class TestDemo {\n    public static void main(String[] args) {\n        Calculator calc = new Calculator();\n        int result = calc.add(10, 20);\n        assert result == 30 : \"Addition failed\";\n        System.out.println(\"Test passed: 10 + 20 == \" + result);\n    }\n}",
          "play": true,
          "lang": "java",
          "id": 39,
          "sid": 16,
          "stitle": "Unit Testing with JUnit 5 & Mockito",
          "sicon": "🧪",
          "sref": "Module 16"
        },
        {
          "level": "I",
          "q": "What is the difference between @Mock and @Spy in Mockito?",
          "a": "A @Mock creates a completely synthetic dummy object where every method returns default values (null, 0, false) unless stubbed with when(...). A @Spy creates a wrapper around a real instance; calling unstubbed methods invokes the real production code.",
          "e": "Use @Spy when you want to test partial behavior of an existing class.",
          "code": "public class MockitoPrinciple {\n    public static void main(String[] args) {\n        System.out.println(\"@Mock = complete fake; @Spy = real object with selective intercepts\");\n    }\n}",
          "play": true,
          "lang": "java",
          "id": 40,
          "sid": 16,
          "stitle": "Unit Testing with JUnit 5 & Mockito",
          "sicon": "🧪",
          "sref": "Module 16"
        }
      ],
      "id": 16
    },
    {
      "title": "Spring Boot & Enterprise Architecture",
      "icon": "🌱",
      "ref": "Module 17",
      "questions": [
        {
          "level": "B",
          "q": "What is Inversion of Control (IoC) and Dependency Injection (DI)?",
          "a": "IoC is the architectural principle where the control of object creation and lifecycle is delegated to a framework container (Spring ApplicationContext). Dependency Injection is the mechanism where the container injects required dependent beans via constructors, setters, or fields.",
          "e": "Constructor injection is preferred over @Autowired field injection because it ensures immutability (final fields) and simplifies unit testing without Spring context reflection.",
          "code": "public class IoCDemo {\n    interface Engine { String start(); }\n    static class V8Engine implements Engine {\n        public String start() { return \"V8 Roar!\"; }\n    }\n    static class Car {\n        private final Engine engine;\n        Car(Engine engine) { this.engine = engine; } // DI\n        void drive() { System.out.println(engine.start()); }\n    }\n    public static void main(String[] args) {\n        Car car = new Car(new V8Engine());\n        car.drive();\n    }\n}",
          "play": true,
          "lang": "java",
          "id": 41,
          "sid": 17,
          "stitle": "Spring Boot & Enterprise Architecture",
          "sicon": "🌱",
          "sref": "Module 17"
        },
        {
          "level": "I",
          "q": "What does @SpringBootApplication encapsulate?",
          "a": "It is a meta-annotation combining three essential annotations: 1) @SpringBootConfiguration (declares configuration bean), 2) @EnableAutoConfiguration (guesses beans based on classpath dependencies), 3) @ComponentScan (scans current package and subpackages for @Component, @Service, @Repository, @Controller).",
          "e": "Auto-configuration is conditional; annotations like @ConditionalOnClass and @ConditionalOnMissingBean inspect whether you already configured custom beans.",
          "code": "public class BootMeta {\n    public static void main(String[] args) {\n        System.out.println(\"@SpringBootApplication = @Configuration + @EnableAutoConfiguration + @ComponentScan\");\n    }\n}",
          "play": true,
          "lang": "java",
          "id": 42,
          "sid": 17,
          "stitle": "Spring Boot & Enterprise Architecture",
          "sicon": "🌱",
          "sref": "Module 17"
        }
      ],
      "id": 17
    },
    {
      "title": "Interview Algorithms & Coding Challenges",
      "icon": "🎯",
      "ref": "Module 18",
      "questions": [
        {
          "level": "A",
          "q": "How do you implement Two Sum in O(N) time in Java?",
          "a": "Iterate through the array while maintaining a HashMap of value -> index. For each number num, compute complement = target - num. If complement exists in map, return indices. Otherwise store num in map.",
          "e": "Reduces brute force O(N^2) double loops to a single O(N) pass with O(1) hash lookups.",
          "code": "import java.util.*;\n\npublic class TwoSum {\n    static int[] solve(int[] nums, int target) {\n        Map<Integer, Integer> map = new HashMap<>();\n        for (int i = 0; i < nums.length; i++) {\n            int complement = target - nums[i];\n            if (map.containsKey(complement)) {\n                return new int[]{map.get(complement), i};\n            }\n            map.put(nums[i], i);\n        }\n        return new int[]{};\n    }\n    public static void main(String[] args) {\n        int[] result = solve(new int[]{2, 7, 11, 15}, 9);\n        System.out.println(Arrays.toString(result));\n    }\n}",
          "play": true,
          "lang": "java",
          "id": 43,
          "sid": 18,
          "stitle": "Interview Algorithms & Coding Challenges",
          "sicon": "🎯",
          "sref": "Module 18"
        },
        {
          "level": "A",
          "q": "How do you implement an LRU (Least Recently Used) Cache using LinkedHashMap?",
          "a": "Extend LinkedHashMap<K, V> with accessOrder=true in the constructor so gets and puts reorder keys. Override removeEldestEntry(Map.Entry) to return size() > capacity.",
          "e": "In interviews, you can also write it from scratch using a HashMap paired with a custom Doubly Linked List for O(1) get and put.",
          "code": "import java.util.*;\n\npublic class LRUCache<K, V> extends LinkedHashMap<K, V> {\n    private final int capacity;\n    public LRUCache(int capacity) {\n        super(capacity, 0.75f, true); // true = access-order\n        this.capacity = capacity;\n    }\n    @Override\n    protected boolean removeEldestEntry(Map.Entry<K, V> eldest) {\n        return size() > capacity;\n    }\n    public static void main(String[] args) {\n        LRUCache<String, Integer> cache = new LRUCache<>(2);\n        cache.put(\"a\", 1);\n        cache.put(\"b\", 2);\n        cache.get(\"a\"); // accessed 'a', so 'b' becomes eldest\n        cache.put(\"c\", 3); // evicts 'b'\n        System.out.println(cache.keySet());\n    }\n}",
          "play": true,
          "lang": "java",
          "id": 44,
          "sid": 18,
          "stitle": "Interview Algorithms & Coding Challenges",
          "sicon": "🎯",
          "sref": "Module 18"
        },
        {
          "level": "I",
          "q": "How do you check for Valid Parentheses using Deque?",
          "a": "Use an ArrayDeque<Character> as a stack. Push expected closing brackets whenever an opening bracket is seen. On seeing a closing bracket, pop from stack and ensure match.",
          "e": "ArrayDeque is preferred over the legacy java.util.Stack class because Stack inherits from Vector with synchronized method overhead.",
          "code": "import java.util.*;\n\npublic class ValidParentheses {\n    static boolean isValid(String s) {\n        Deque<Character> stack = new ArrayDeque<>();\n        for (char c : s.toCharArray()) {\n            if (c == '(') stack.push(')');\n            else if (c == '{') stack.push('}');\n            else if (c == '[') stack.push(']');\n            else if (stack.isEmpty() || stack.pop() != c) return false;\n        }\n        return stack.isEmpty();\n    }\n    public static void main(String[] args) {\n        System.out.println(\"()[]{}: \" + isValid(\"()[]{}\"));\n        System.out.println(\"(]: \" + isValid(\"(]\"));\n    }\n}",
          "play": true,
          "lang": "java",
          "id": 45,
          "sid": 18,
          "stitle": "Interview Algorithms & Coding Challenges",
          "sicon": "🎯",
          "sref": "Module 18"
        }
      ],
      "id": 18
    }
  ],
  "challenges": [
    {
      "sid": 2,
      "level": "B",
      "title": "Integer Cache Comparison Trap",
      "code": "public class Test {\n    public static void main(String[] args) {\n        Integer a = 127;\n        Integer b = 127;\n        Integer c = 128;\n        Integer d = 128;\n        System.out.println((a == b) + \" \" + (c == d));\n    }\n}",
      "options": [
        "true false",
        "true true",
        "false false",
        "Compilation Error"
      ],
      "answer": 0,
      "explanation": "Java caches autoboxed Integer values between -128 and 127. 'a' and 'b' reference the exact same cached object in memory (a == b is true). 128 is outside the cache, so 'c' and 'd' are separate heap allocations (c == d is false)."
    },
    {
      "sid": 3,
      "level": "B",
      "title": "String Literal Pool vs new String",
      "code": "public class Test {\n    public static void main(String[] args) {\n        String s1 = \"Java\";\n        String s2 = \"Java\";\n        String s3 = new String(\"Java\");\n        System.out.println((s1 == s2) + \" \" + (s1 == s3));\n    }\n}",
      "options": [
        "true false",
        "true true",
        "false false",
        "false true"
      ],
      "answer": 0,
      "explanation": "s1 and s2 both point to the canonical literal in the String Constant Pool. s3 explicitly allocates a new distinct object on the heap, so s1 == s3 evaluates to false."
    },
    {
      "sid": 2,
      "level": "I",
      "title": "Post-Increment Assignment Quirk",
      "code": "public class Test {\n    public static void main(String[] args) {\n        int i = 0;\n        i = i++;\n        System.out.println(i);\n    }\n}",
      "options": [
        "0",
        "1",
        "2",
        "Compilation Error"
      ],
      "answer": 0,
      "explanation": "i++ evaluates to the old value (0) and queues the increment. Then the assignment '=' writes the old value 0 back into i, overwriting the increment! Hence i remains 0."
    },
    {
      "sid": 6,
      "level": "I",
      "title": "Finally Block Return Override",
      "code": "public class Test {\n    static int getValue() {\n        try {\n            return 1;\n        } finally {\n            return 2;\n        }\n    }\n    public static void main(String[] args) {\n        System.out.println(getValue());\n    }\n}",
      "options": [
        "2",
        "1",
        "3",
        "Compilation Error"
      ],
      "answer": 0,
      "explanation": "A return statement in a finally block always executes and discards any pending return value or unhandled exception from the try or catch block."
    },
    {
      "sid": 4,
      "level": "A",
      "title": "Method Overloading with Null",
      "code": "public class Test {\n    static void print(Object o) { System.out.println(\"Object\"); }\n    static void print(String s) { System.out.println(\"String\"); }\n\n    public static void main(String[] args) {\n        print(null);\n    }\n}",
      "options": [
        "String",
        "Object",
        "Ambiguous Method Call Error",
        "NullPointerException"
      ],
      "answer": 0,
      "explanation": "When resolving overloaded methods with null, the compiler picks the most specific type. Since String is a subtype of Object, String is more specific, so print(String) is selected without ambiguity."
    },
    {
      "sid": 10,
      "level": "I",
      "title": "Stream Lazy Evaluation",
      "code": "import java.util.stream.Stream;\n\npublic class Test {\n    public static void main(String[] args) {\n        Stream.of(\"a\", \"b\", \"c\")\n              .filter(s -> {\n                  System.out.print(s);\n                  return true;\n              });\n        System.out.print(\"end\");\n    }\n}",
      "options": [
        "end",
        "abcend",
        "aend",
        "endabc"
      ],
      "answer": 0,
      "explanation": "Streams are lazy! Intermediate operations like filter() do not execute until a terminal operation (like forEach, collect, count) is attached. Because there is no terminal operation, only 'end' is printed."
    },
    {
      "sid": 4,
      "level": "A",
      "title": "Polymorphism: Field Hiding vs Method Overriding",
      "code": "class Parent {\n    int x = 10;\n    int getX() { return x; }\n}\nclass Child extends Parent {\n    int x = 20;\n    int getX() { return x; }\n}\npublic class Test {\n    public static void main(String[] args) {\n        Parent p = new Child();\n        System.out.println(p.x + \" \" + p.getX());\n    }\n}",
      "options": [
        "10 20",
        "20 20",
        "10 10",
        "20 10"
      ],
      "answer": 0,
      "explanation": "In Java, methods are overridden polymorphically (dynamic dispatch resolves to Child.getX()), but member variables are NOT polymorphic (fields are resolved statically by reference type Parent, giving 10)."
    },
    {
      "sid": 7,
      "level": "I",
      "title": "List.remove(int) vs List.remove(Object)",
      "code": "import java.util.*;\n\npublic class Test {\n    public static void main(String[] args) {\n        List<Integer> list = new ArrayList<>(List.of(1, 2, 3));\n        list.remove(1);\n        System.out.println(list);\n    }\n}",
      "options": [
        "[1, 3]",
        "[2, 3]",
        "[1, 2]",
        "IndexOutOfBoundsException"
      ],
      "answer": 0,
      "explanation": "List has two overloaded methods: remove(int index) and remove(Object o). The literal 1 is a primitive int, so it invokes remove(int index=1), removing element at index 1 (which is 2), leaving [1, 3]. To remove the value 1, you would write list.remove(Integer.valueOf(1))."
    },
    {
      "sid": 4,
      "level": "A",
      "title": "Static Initialization Hierarchy Order",
      "code": "class A {\n    static { System.out.print(\"1\"); }\n    { System.out.print(\"2\"); }\n    A() { System.out.print(\"3\"); }\n}\nclass B extends A {\n    static { System.out.print(\"4\"); }\n    { System.out.print(\"5\"); }\n    B() { System.out.print(\"6\"); }\n}\npublic class Test {\n    public static void main(String[] args) {\n        new B();\n    }\n}",
      "options": [
        "142356",
        "123456",
        "412356",
        "143256"
      ],
      "answer": 0,
      "explanation": "Initialization order: 1) Superclass static blocks (1), 2) Subclass static blocks (4), 3) Superclass instance initializer (2), 4) Superclass constructor (3), 5) Subclass instance initializer (5), 6) Subclass constructor (6)."
    },
    {
      "sid": 2,
      "level": "B",
      "title": "Binary Floating-Point Precision",
      "code": "public class Test {\n    public static void main(String[] args) {\n        double d = 0.1 + 0.2;\n        System.out.println(d == 0.3);\n    }\n}",
      "options": [
        "false",
        "true",
        "0.3",
        "Compilation Error"
      ],
      "answer": 0,
      "explanation": "0.1 and 0.2 cannot be represented precisely in IEEE 754 binary floating-point. 0.1 + 0.2 evaluates to 0.30000000000000004, so d == 0.3 is false. Use BigDecimal for precise financial math."
    },
    {
      "sid": 13,
      "level": "I",
      "title": "Switch Expression Fallthrough",
      "code": "public class Test {\n    public static void main(String[] args) {\n        int x = 2;\n        String res = switch (x) {\n            case 1 -> \"one\";\n            case 2, 3 -> \"two or three\";\n            default -> \"other\";\n        };\n        System.out.println(res);\n    }\n}",
      "options": [
        "two or three",
        "other",
        "one",
        "Compilation Error"
      ],
      "answer": 0,
      "explanation": "Modern arrow switch expressions (Java 14+) do not fall through! The matched case 2, 3 returns 'two or three' immediately."
    },
    {
      "sid": 7,
      "level": "I",
      "title": "Map.computeIfAbsent Behavior",
      "code": "import java.util.*;\n\npublic class Test {\n    public static void main(String[] args) {\n        Map<String, Integer> map = new HashMap<>();\n        map.put(\"a\", 10);\n        map.computeIfAbsent(\"a\", k -> 20);\n        map.computeIfAbsent(\"b\", k -> 30);\n        System.out.println(map.get(\"a\") + \" \" + map.get(\"b\"));\n    }\n}",
      "options": [
        "10 30",
        "20 30",
        "10 null",
        "null 30"
      ],
      "answer": 0,
      "explanation": "computeIfAbsent only computes and inserts a new value if the key is not already present or is mapped to null. Since 'a' is already 10, the lambda is not executed and 'a' remains 10. 'b' was absent, so it gets mapped to 30."
    }
  ],
  "snippets": [
    {
      "id": "hello_java21",
      "icon": "☕",
      "title": "Hello Java 21 & Records",
      "description": "Modern Java with record classes, formatted strings, and compact syntax",
      "filename": "HelloJava21.java",
      "code": "public class Main {\n    record Developer(String name, String role, int experienceYears) {\n        public String greeting() {\n            return \"Hello, I am \" + name + \" (\" + role + \") with \" + experienceYears + \" years in Java!\";\n        }\n    }\n\n    public static void main(String[] args) {\n        Developer dev = new Developer(\"Matru\", \"Lead Data & Backend Engineer\", 5);\n        System.out.println(dev.greeting());\n\n        for (int i = 1; i <= 3; i++) {\n            System.out.println(\">>> Welcome to Java Academy [Iteration \" + i + \"]\");\n        }\n    }\n}"
    },
    {
      "id": "fizzbuzz",
      "icon": "🎯",
      "title": "Stream FizzBuzz",
      "description": "Classic FizzBuzz implemented with concise Java Streams",
      "filename": "StreamFizzBuzz.java",
      "code": "import java.util.stream.IntStream;\n\npublic class Main {\n    public static void main(String[] args) {\n        IntStream.rangeClosed(1, 20)\n            .mapToObj(n -> {\n                if (n % 15 == 0) return \"FizzBuzz\";\n                if (n % 3 == 0) return \"Fizz\";\n                if (n % 5 == 0) return \"Buzz\";\n                return String.valueOf(n);\n            })\n            .forEach(s -> System.out.print(s + \" \"));\n        System.out.println();\n    }\n}"
    },
    {
      "id": "virtual_threads",
      "icon": "⚡",
      "title": "Virtual Threads Simulator",
      "description": "Java 21 Project Loom lightweight concurrent task execution",
      "filename": "VirtualThreads.java",
      "code": "public class Main {\n    public static void main(String[] args) {\n        System.out.println(\"Starting Virtual Threads Concurrent Pipeline...\");\n        int taskCount = 5;\n        for (int i = 1; i <= taskCount; i++) {\n            int taskId = i;\n            System.out.println(\"[VirtualThread-\" + taskId + \"] Executing I/O simulated operation\");\n        }\n        System.out.println(\"All virtual tasks completed with sub-millisecond footprint!\");\n    }\n}"
    },
    {
      "id": "stream_grouping",
      "icon": "📊",
      "title": "Stream Aggregation & Grouping",
      "description": "Business analytics grouping transactions by department with Collectors",
      "filename": "SalesAnalytics.java",
      "code": "import java.util.*;\nimport java.util.stream.Collectors;\n\npublic class Main {\n    record Sale(String department, double amount) {}\n\n    public static void main(String[] args) {\n        List<Sale> sales = List.of(\n            new Sale(\"Engineering\", 1200.0),\n            new Sale(\"Marketing\", 450.0),\n            new Sale(\"Engineering\", 800.0),\n            new Sale(\"Design\", 600.0),\n            new Sale(\"Marketing\", 750.0)\n        );\n\n        Map<String, Double> totalByDept = sales.stream()\n            .collect(Collectors.groupingBy(\n                Sale::department,\n                Collectors.summingDouble(Sale::amount)\n            ));\n\n        System.out.println(\"=== Sales Summary by Department ===\");\n        totalByDept.forEach((dept, total) -> {\n            System.out.println(dept + \": $\" + total);\n        });\n    }\n}"
    },
    {
      "id": "lru_cache",
      "icon": "🏗️",
      "title": "LRU Cache Implementation",
      "description": "Least Recently Used memory cache using LinkedHashMap",
      "filename": "LRUCacheDemo.java",
      "code": "import java.util.*;\n\npublic class Main {\n    static class LRUCache<K, V> extends LinkedHashMap<K, V> {\n        private final int capacity;\n        public LRUCache(int capacity) {\n            super(capacity, 0.75f, true); // access-order\n            this.capacity = capacity;\n        }\n        @Override\n        protected boolean removeEldestEntry(Map.Entry<K, V> eldest) {\n            return size() > capacity;\n        }\n    }\n\n    public static void main(String[] args) {\n        LRUCache<String, String> cache = new LRUCache<>(3);\n        cache.put(\"item1\", \"Java\");\n        cache.put(\"item2\", \"Spring\");\n        cache.put(\"item3\", \"Docker\");\n        \n        System.out.println(\"Initial cache keys: \" + cache.keySet());\n        cache.get(\"item1\"); // touch item1\n        cache.put(\"item4\", \"Kubernetes\"); // should evict item2\n        \n        System.out.println(\"After access & insertion: \" + cache.keySet());\n    }\n}"
    },
    {
      "id": "word_frequency",
      "icon": "🔠",
      "title": "Word Frequency Counter",
      "description": "Text parsing and word frequency counting using Java Streams",
      "filename": "WordFrequency.java",
      "code": "import java.util.*;\nimport java.util.stream.Collectors;\n\npublic class Main {\n    public static void main(String[] args) {\n        String text = \"Java is powerful and Java is fast and Java is scalable\";\n        String[] words = text.toLowerCase().split(\"\\\\s+\");\n\n        Map<String, Long> freq = Arrays.stream(words)\n            .collect(Collectors.groupingBy(w -> w, Collectors.counting()));\n\n        System.out.println(\"=== Word Frequencies ===\");\n        freq.entrySet().stream()\n            .sorted(Map.Entry.<String, Long>comparingByValue().reversed())\n            .forEach(e -> System.out.println(e.getKey() + \": \" + e.getValue()));\n    }\n}"
    }
  ]
};
