"""Sections 1-6: Java Fundamentals, Primitives & Memory, Strings, OOP, Interfaces & Records, Exceptions."""
from schema import Q, S

SECTIONS = [
    S("Java Fundamentals & JVM Architecture", "☕", "Module 1", [
        Q("B", "What is the difference between JDK, JRE, and JVM?",
          "JVM (Java Virtual Machine) executes compiled bytecode. JRE (Java Runtime Environment) = JVM + core class libraries needed to run Java apps. JDK (Java Development Kit) = JRE + development tools like javac compiler, jdb debugger, and javadoc.",
          "Write Once, Run Anywhere (WORA) is achieved because the compiler emits platform-independent .class bytecode that any OS-specific JVM can execute.",
          '''public class Main {
    public static void main(String[] args) {
        System.out.println("Java Version: " + System.getProperty("java.version"));
        System.out.println("JVM Vendor: " + System.getProperty("java.vm.vendor"));
        System.out.println("Architecture: " + System.getProperty("os.arch"));
    }
}'''),
        Q("B", "Why is the main method static in Java?",
          "The JVM invokes public static void main(String[] args) before any object of the class is instantiated. If main were not static, the JVM wouldn't know which constructor to call to instantiate the class.",
          "The signature must match precisely. If static is omitted, runtime throws 'NoSuchMethodError: main'.",
          '''public class App {
    public static void main(String[] args) {
        System.out.println("Args received: " + args.length);
    }
}'''),
        Q("I", "How does the JIT (Just-In-Time) compiler work inside HotSpot?",
          "The JVM starts executing bytecode via an interpreter for fast startup. Frequently executed 'hot spots' are identified by profiling counters and compiled directly into native machine code by Tiered Compilers (C1 Client for quick optimization, C2 Server for heavy optimizations).",
          "HotSpot performs inlining, loop unrolling, escape analysis, and dead code elimination dynamically at runtime based on actual branch probabilities.",
          '''public class HotSpotDemo {
    public static void main(String[] args) {
        long sum = 0;
        for (int i = 0; i < 1_000_000; i++) {
            sum += i;
        }
        System.out.println("Sum: " + sum);
    }
}'''),
        Q("I", "What is the difference between Stack Memory and Heap Memory?",
          "Stack memory stores local primitive variables and references to objects for each executing thread. Heap memory stores all instantiated objects. Stack is LIFO, thread-safe, and very fast; Heap is shared across threads and managed by the Garbage Collector.",
          "When a thread exceeds its stack depth (e.g. infinite recursion), a StackOverflowError occurs. When the heap runs out of allocation space, an OutOfMemoryError: Java heap space is thrown.",
          '''public class MemoryDemo {
    public static void main(String[] args) {
        int x = 42; // on stack
        String text = new String("Heap Object"); // ref on stack, object on heap
        System.out.println("x = " + x + ", text = " + text);
    }
}'''),
        Q("B", "What is bytecode and why is it important?",
          "Bytecode is the intermediate instruction representation generated by javac (.class file). It is not machine code for any specific CPU, but rather instructions for the virtual processor modeled by the JVM.",
          "This separation decouples application code from host hardware, making Java portable and enabling diverse languages (Kotlin, Scala, Clojure) to target the same runtime.",
          '''public class BytecodeDemo {
    public static void main(String[] args) {
        System.out.println("Target: JVM Bytecode Specification");
    }
}''')
    ]),

    S("Primitives, Wrappers & Memory Semantics", "🔢", "Module 2", [
        Q("B", "What are the 8 primitive types in Java and their sizes?",
          "byte (8-bit), short (16-bit), int (32-bit), long (64-bit), float (32-bit IEEE 754), double (64-bit IEEE 754), char (16-bit Unicode UTF-16), and boolean (true/false).",
          "Primitives live directly on the stack when declared locally, avoiding heap allocation and pointer dereference overhead.",
          '''public class Primitives {
    public static void main(String[] args) {
        System.out.println("Byte range: " + Byte.MIN_VALUE + " to " + Byte.MAX_VALUE);
        System.out.println("Int range: " + Integer.MIN_VALUE + " to " + Integer.MAX_VALUE);
    }
}'''),
        Q("I", "What is the Integer Cache trap in autoboxing?",
          "Java caches Integer wrapper objects for values between -128 and 127 (inclusive). Autoboxing values in this range returns the same cached instance (so == returns true). Outside this range, a new object is allocated, making == return false.",
          "Always use .equals() rather than == when comparing wrapper objects in Java to compare value rather than object reference.",
          '''public class IntegerCacheDemo {
    public static void main(String[] args) {
        Integer a = 127, b = 127;
        Integer c = 128, d = 128;
        System.out.println("127 == 127: " + (a == b));
        System.out.println("128 == 128: " + (c == d));
        System.out.println("128 equals 128: " + c.equals(d));
    }
}'''),
        Q("I", "Is Java pass-by-value or pass-by-reference?",
          "Java is STRICTLY pass-by-value, always. For primitive types, the actual bit value is copied. For object types, the reference (memory address) value is copied. You can mutate the contents of the passed object, but reassigning the parameter does not affect the caller's reference.",
          "A common misunderstanding: passing an object does not pass the pointer itself by reference; it passes a copy of the pointer address by value.",
          '''public class PassByValue {
    static void modify(int num, StringBuilder sb) {
        num = 99;
        sb.append(" World");
        sb = new StringBuilder("Goodbye"); // rebinds local copy only
    }

    public static void main(String[] args) {
        int x = 10;
        StringBuilder message = new StringBuilder("Hello");
        modify(x, message);
        System.out.println("x = " + x);
        System.out.println("message = " + message);
    }
}''')
    ]),

    S("Strings, Immutability & Text Blocks", "🔤", "Module 3", [
        Q("B", "Why are String objects immutable in Java?",
          "Security (parameters like DB connection URLs, file paths cannot be hijacked), Thread Safety (read-only state eliminates synchronization), String Pool Caching (shared literals save massive heap space), and HashCode Caching (hash is computed once and cached).",
          "Because String is immutable, String.hashCode() is calculated on first invocation and stored in a private hash field, making HashMap lookups lightning fast.",
          '''public class StringPool {
    public static void main(String[] args) {
        String s1 = "Java";
        String s2 = "Java";
        String s3 = new String("Java");
        System.out.println("s1 == s2: " + (s1 == s2));
        System.out.println("s1 == s3: " + (s1 == s3));
        System.out.println("s1.equals(s3): " + s1.equals(s3));
        System.out.println("s1 == s3.intern(): " + (s1 == s3.intern()));
    }
}'''),
        Q("I", "What is the difference between String, StringBuilder, and StringBuffer?",
          "String is immutable; each modification creates a new object. StringBuilder is mutable and not thread-safe (fastest for single-threaded loops). StringBuffer is mutable and thread-safe (methods are synchronized, incurring lock overhead).",
          "Inside loops, always prefer StringBuilder over String concatenation '+' to avoid creating O(N^2) discarded intermediate String objects.",
          '''public class StringBuilderDemo {
    public static void main(String[] args) {
        StringBuilder sb = new StringBuilder("Start");
        for (int i = 1; i <= 3; i++) {
            sb.append(" -> ").append(i);
        }
        System.out.println(sb.toString());
    }
}'''),
        Q("B", "What are Text Blocks in modern Java (Java 15+)?",
          "Text Blocks use triple quotes (\\\"\\\"\\\") to declare multi-line string literals without manual escape sequences (\\\\n or \\\\t). Common incidental white space is automatically stripped based on the closing delimiter indentation.",
          "Ideal for JSON, SQL queries, HTML, and regex without messy concatenation.",
          '''public class TextBlocks {
    public static void main(String[] args) {
        String json = """
            {
              "name": "Java Academy",
              "language": "Java 21"
            }
            """;
        System.out.println(json.strip());
    }
}''')
    ]),

    S("Object-Oriented Programming in Java", "🏗️", "Module 4", [
        Q("B", "What is the difference between method overloading and method overriding?",
          "Overloading: multiple methods in the same class have the same name but different parameter lists (compile-time/static polymorphism). Overriding: subclass provides specific implementation for a method declared in superclass with identical signature (runtime/dynamic polymorphism).",
          "In overriding, return type can be covariant (subtype), and access level cannot be made more restrictive.",
          '''class Parent {
    String role() { return "Parent"; }
}
class Child extends Parent {
    @Override
    String role() { return "Child"; }
}
public class PolyDemo {
    public static void main(String[] args) {
        Parent p = new Child();
        System.out.println(p.role()); // dynamic dispatch
    }
}'''),
        Q("I", "Why does Java not support multiple inheritance with classes?",
          "To prevent the 'Diamond Problem', where class D extends both B and C (which both extend A and override method m()). The compiler would face ambiguity as to which implementation D should inherit. Multiple inheritance of type is supported via interfaces.",
          "With interface default methods, Java resolves diamond conflicts by requiring the implementing class to explicitly override the conflicting method.",
          '''interface A {
    default String hello() { return "A"; }
}
interface B {
    default String hello() { return "B"; }
}
class C implements A, B {
    @Override
    public String hello() {
        return A.super.hello() + " & " + B.super.hello();
    }
}
public class DiamondDemo {
    public static void main(String[] args) {
        System.out.println(new C().hello());
    }
}'''),
        Q("I", "What is the contract between equals() and hashCode()?",
          "If two objects are equal according to equals(Object), their hashCode() MUST return the exact same integer. If two objects have the same hashCode(), they are not necessarily equal (hash collision).",
          "Breaking this contract breaks Hash-based collections (HashMap, HashSet). If equals is overridden without hashCode, an object inserted into a HashMap cannot be retrieved.",
          '''import java.util.Objects;

class User {
    private final int id;
    private final String name;

    User(int id, String name) {
        this.id = id;
        this.name = name;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof User u)) return false;
        return id == u.id && Objects.equals(name, u.name);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name);
    }
}
public class ContractDemo {
    public static void main(String[] args) {
        User u1 = new User(1, "Matru");
        User u2 = new User(1, "Matru");
        System.out.println("equals: " + u1.equals(u2));
        System.out.println("same hash: " + (u1.hashCode() == u2.hashCode()));
    }
}''')
    ]),

    S("Interfaces, Sealed Classes & Records", "📜", "Module 5", [
        Q("B", "What are Records in Java 14+?",
          "Records are immutable data-carrier classes declared with the record keyword. The compiler automatically generates private final fields, a canonical constructor, public accessors, equals(), hashCode(), and toString().",
          "Records can implement interfaces and declare static members, but they cannot extend other classes because they implicitly extend java.lang.Record.",
          '''public record Point(int x, int y) {
    public double distanceFromOrigin() {
        return Math.hypot(x, y);
    }
}
class Main {
    public static void main(String[] args) {
        Point p = new Point(3, 4);
        System.out.println(p);
        System.out.println("x: " + p.x() + ", distance: " + p.distanceFromOrigin());
    }
}'''),
        Q("A", "What are Sealed Classes and Interfaces (Java 17+)?",
          "Sealed classes restrict which other classes can extend or implement them using the sealed and permits keywords. Permitted subclasses must be final, sealed, or non-sealed.",
          "Enables algebraic data types and exhaustive pattern matching in switch expressions without requiring a default clause.",
          '''sealed interface Shape permits Circle, Rectangle {}
final record Circle(double radius) implements Shape {}
final record Rectangle(double w, double h) implements Shape {}

public class SealedDemo {
    static double area(Shape s) {
        return switch (s) {
            case Circle c -> Math.PI * c.radius() * c.radius();
            case Rectangle r -> r.w() * r.h();
        };
    }
    public static void main(String[] args) {
        System.out.println("Circle area: " + Math.round(area(new Circle(10))));
        System.out.println("Rect area: " + area(new Rectangle(4, 5)));
    }
}''')
    ]),

    S("Exception Handling & Resource Management", "🚨", "Module 6", [
        Q("B", "What is the difference between Checked and Unchecked exceptions?",
          "Checked exceptions (subclasses of Exception except RuntimeException) are checked at compile time; methods must either catch them or declare them in throws. Unchecked exceptions (subclasses of RuntimeException and Error) occur at runtime and are not enforced by the compiler.",
          "Examples of checked: IOException, SQLException. Unchecked: NullPointerException, ArrayIndexOutOfBoundsException, IllegalArgumentException.",
          '''public class ExceptionDemo {
    public static void main(String[] args) {
        try {
            int result = Integer.parseInt("not-a-number");
        } catch (NumberFormatException e) {
            System.out.println("Caught unchecked exception: " + e.getClass().getSimpleName());
        }
    }
}'''),
        Q("I", "How does Try-With-Resources guarantee clean closing of resources?",
          "Any resource implementing java.lang.AutoCloseable or java.io.Closeable opened in the try(...) header is automatically closed at the end of the block in reverse order of declaration, even if an exception is thrown.",
          "Prevents resource leaks (file descriptors, sockets, database connections) and replaces verbose nested finally blocks.",
          '''class Resource implements AutoCloseable {
    private final String name;
    Resource(String name) { this.name = name; }
    @Override
    public void close() {
        System.out.println("Closed: " + name);
    }
}
public class AutoCloseDemo {
    public static void main(String[] args) {
        try (Resource r1 = new Resource("DatabaseCon");
             Resource r2 = new Resource("FileHandle")) {
            System.out.println("Executing query...");
        }
    }
}''')
    ])
]
