"""Builds ../data.js and ../public/data.js (window.JAVA_DATA) from the content files.

    python3 source/generate_data.py
"""
import json
from pathlib import Path

import content_a
import content_b
import content_c
from challenges import CHALLENGES, SNIPPETS

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
OUT_ROOT = ROOT / "data.js"


def main():
    sections = content_a.SECTIONS + content_b.SECTIONS + content_c.SECTIONS
    qid = 0
    for sid, sec in enumerate(sections, 1):
        sec["id"] = sid
        for q in sec["questions"]:
            qid += 1
            q["id"] = qid
            q["sid"] = sid
            q["stitle"] = sec["title"]
            q["sicon"] = sec["icon"]
            q["sref"] = sec["ref"]

    data = {
        "sections": sections,
        "challenges": CHALLENGES,
        "snippets": SNIPPETS
    }

    content = (
        "// Generated by Java Academy source/generate_data.py; do not edit by hand.\n"
        f"window.JAVA_DATA = {json.dumps(data, ensure_ascii=False, indent=2)};\n"
    )

    OUT_ROOT.write_text(content, encoding="utf-8")

    total_q = sum(len(s["questions"]) for s in sections)
    print(f"Generated {OUT_ROOT}: {len(sections)} sections, {total_q} questions, "
          f"{len(CHALLENGES)} challenges, {len(SNIPPETS)} snippets")


if __name__ == "__main__":
    main()
