"""Builds ../website/data.js (window.PY_DATA) from the content files.

Every runnable code example is executed in a fresh interpreter (inside a temporary folder) and
its real output is stored next to it, and every "predict the output" challenge takes its correct
answer from actually running the code. If any example raises, the build fails.

    python3 generate_data.py
"""
import json
import random
import subprocess
import sys
import tempfile
from pathlib import Path

import content_a
import content_b
import content_c
from challenges import CHALLENGES, SNIPPETS

HERE = Path(__file__).resolve().parent
OUT = HERE.parent / "website" / "data.js"
MAX_OUT = 1500


def run(code, cwd):
    p = subprocess.run([sys.executable, "-c", code], cwd=cwd, capture_output=True, text=True, timeout=60)
    if p.returncode != 0:
        raise RuntimeError(p.stderr.strip().splitlines()[-1] if p.stderr.strip() else f"exit {p.returncode}")
    out = p.stdout.rstrip()
    return out if len(out) <= MAX_OUT else out[:MAX_OUT] + "\n…"


def main():
    sections = content_a.SECTIONS + content_b.SECTIONS + content_c.SECTIONS
    qid, failures, ran = 0, [], 0
    for sid, sec in enumerate(sections, 1):
        sec["id"] = sid
        for q in sec["questions"]:
            qid += 1
            q["id"] = qid
            if q["run"]:
                with tempfile.TemporaryDirectory() as tmp:
                    try:
                        q["out"] = run(q["code"], tmp)
                        ran += 1
                    except Exception as err:
                        failures.append(f"Q{qid} ({sec['title']}): {err}")
            del q["run"]
            if not q["code"]:
                for k in ("code", "lang", "play"):
                    q.pop(k)

    rng = random.Random(2026)                       # stable option order between builds
    challenges = []
    for cid, c in enumerate(CHALLENGES, 1):
        with tempfile.TemporaryDirectory() as tmp:
            try:
                answer = run(c["code"], tmp)
            except Exception as err:
                failures.append(f"Challenge {cid}: {err}")
                continue
        if answer in c["wrong"] or len(set(c["wrong"])) != 3:
            failures.append(f"Challenge {cid}: a distractor equals the real output {answer!r}")
            continue
        options = [answer, *c["wrong"]]
        rng.shuffle(options)
        challenges.append({"id": cid, "sid": c["sid"], "level": c["level"], "code": c["code"],
                           "options": options, "answer": options.index(answer), "e": c["e"]})

    if failures:
        print("Build failed:\n  " + "\n  ".join(failures))
        sys.exit(1)

    data = {"sections": sections, "challenges": challenges, "snippets": SNIPPETS}
    OUT.write_text("// Generated by PY_PRJ/source/generate_data.py; do not edit by hand.\n"
                   f"window.PY_DATA = {json.dumps(data, ensure_ascii=False, indent=1)};\n", encoding="utf-8")
    total = sum(len(s["questions"]) for s in sections)
    print(f"Wrote {OUT.relative_to(HERE.parent.parent)}: {len(sections)} sections, {total} questions "
          f"({ran} examples executed), {len(challenges)} challenges, {len(SNIPPETS)} snippets")


if __name__ == "__main__":
    main()
