window.ETL_ACADEMY_DATA = {
  modules: [
    { id: "foundations", title: "Data pipeline foundations", category: "Foundations", level: "Beginner", minutes: 12, icon: "🧭", summary: "Understand how data moves from a source to a useful destination.", lessons: ["A data pipeline is a repeatable path that extracts data, applies agreed rules, and delivers it to a system where people or applications can use it.", "A production pipeline also needs schedules or triggers, validation, retries, monitoring, access control, and a clear recovery plan.", "Separate the source, processing steps, and destination. This makes ownership and failures easier to reason about."], task: "Sketch one source, two transformation steps, and one destination for a daily sales report." },
    { id: "etl-elt", title: "ETL and ELT compared", category: "Core concepts", level: "Beginner", minutes: 14, icon: "🔀", summary: "Choose where transformation should happen and why.", lessons: ["ETL extracts, transforms before loading, then writes prepared data to the target. It suits constrained targets and cases where sensitive fields must be filtered before arrival.", "ELT extracts and loads raw data first, then transforms inside a scalable destination such as a cloud warehouse or lakehouse.", "The choice depends on target compute, governance, latency, cost, tooling, and how much raw history you need to retain. Many platforms use both patterns."], task: "For a cloud warehouse with elastic compute and replayable raw files, explain why ELT may be a good fit." },
    { id: "sources", title: "Sources and extraction", category: "Ingestion", level: "Beginner", minutes: 13, icon: "📥", summary: "Read from databases, files, APIs, and event streams safely.", lessons: ["Common sources include relational databases, REST APIs, object storage, SaaS tools, and message brokers.", "A full extract reads all available data. An incremental extract reads only new or changed records, often using a timestamp, sequence, or change data capture (CDC).", "Record the extraction window, source watermark, schema version, and run identifier so a load can be audited and resumed."], task: "Pick a reliable watermark for a table that receives late updates. State how you would handle records updated after the last run." },
    { id: "batch-stream", title: "Batch and streaming", category: "Ingestion", level: "Beginner", minutes: 15, icon: "⏱️", summary: "Match processing cadence to freshness and volume needs.", lessons: ["Batch jobs process bounded groups on a schedule or trigger. They are straightforward to retry and work well for periodic reporting.", "Streaming systems process events continuously or in small windows. They reduce latency but require careful handling of ordering, duplicates, and late events.", "Micro-batch systems sit between the two. Pick the simplest cadence that meets the business freshness target."], task: "A finance dashboard refreshes every morning. Compare a nightly batch with a stream for this use case." },
    { id: "modeling", title: "Staging and data modeling", category: "Transformation", level: "Intermediate", minutes: 16, icon: "🧱", summary: "Shape raw records into trusted, understandable datasets.", lessons: ["A common warehouse flow separates raw, cleaned or staged, and curated data. Keep raw inputs immutable when retention and policy allow.", "Normalize types and names in staging. Build curated tables around business entities and questions, not around one dashboard's temporary needs.", "Facts describe measurable events; dimensions provide descriptive context. Define grain explicitly before joining or aggregating."], task: "Define the grain and two dimensions for an order-line fact table." },
    { id: "sql-transform", title: "SQL transformations", category: "Transformation", level: "Intermediate", minutes: 17, icon: "🧮", summary: "Use clear, modular SQL to build reliable models.", lessons: ["Break transformations into named steps or models with one clear responsibility. Avoid repeating business logic across reports.", "Use explicit column lists, deliberate casts, and readable joins. Check join cardinality before trusting aggregates.", "Treat model changes like code: version them, review them, and run tests before promotion."], task: "List three checks you would make before joining customer records to order records." },
    { id: "quality", title: "Data quality and contracts", category: "Trust & safety", level: "Intermediate", minutes: 15, icon: "✅", summary: "Catch invalid, missing, duplicated, or unexpected data early.", lessons: ["Useful checks include not-null, uniqueness, accepted values, referential integrity, freshness, and volume bounds.", "A schema or data contract makes expectations explicit between producers and consumers. A change can be breaking even when a job still succeeds.", "Choose severity by impact. Block critical violations, quarantine recoverable bad records, and make every exception visible."], task: "Write a quality contract for an events table with a unique event id and required event timestamp." },
    { id: "orchestration", title: "Orchestration and dependencies", category: "Orchestration", level: "Intermediate", minutes: 16, icon: "🕸️", summary: "Coordinate tasks, dependencies, retries, and schedules.", lessons: ["An orchestrator coordinates work and records state. A DAG represents tasks and their dependency order without cycles.", "Make tasks idempotent where possible so a retry does not create duplicate or inconsistent output.", "Use bounded retries with backoff for transient failures. Route persistent failures to an alert and a documented recovery path."], task: "Design a three-task DAG for ingesting, validating, and publishing a daily customer snapshot." },
    { id: "incremental", title: "Incremental loads and CDC", category: "Ingestion", level: "Intermediate", minutes: 18, icon: "♻️", summary: "Load changes efficiently while preserving correctness.", lessons: ["An upsert matches incoming records to target keys, then inserts new records and updates changed ones.", "CDC captures inserts, updates, and deletes from a source change log. Consumers need a stable ordering key and a strategy for replay.", "Late-arriving changes, duplicate delivery, and delete propagation must be designed explicitly. Store and advance watermarks only after successful processing."], task: "Explain how you would make a replayed CDC batch safe to process twice." },
    { id: "observability", title: "Observability and operations", category: "Operations", level: "Intermediate", minutes: 14, icon: "📡", summary: "Know when pipelines are healthy and diagnose failures quickly.", lessons: ["Track freshness, success rate, duration, row counts, rejected records, and cost. A green process exit alone does not prove the data is correct.", "Attach run ids and source windows to logs and metrics. Alerts should state what failed, who owns it, and what the first useful action is.", "Keep runbooks for reruns, backfills, credential rotation, and downstream communication."], task: "Choose one service-level objective for a daily reporting pipeline and define how to measure it." },
    { id: "security", title: "Security and governance", category: "Trust & safety", level: "Intermediate", minutes: 13, icon: "🔐", summary: "Protect data throughout extraction, storage, and access.", lessons: ["Use least-privilege identities, managed secrets, encrypted transport, and encrypted storage. Avoid credentials embedded in code or logs.", "Classify sensitive fields and apply masking, tokenization, or removal as required by policy.", "Document lineage, retention, ownership, and access rules so teams can understand where data came from and who may use it."], task: "Describe how a pipeline should treat an unnecessary personal identifier from source through reporting." },
    { id: "lakehouse", title: "Warehouses, lakes, and lakehouses", category: "Platforms", level: "Intermediate", minutes: 16, icon: "🏞️", summary: "Understand storage and compute choices for modern analytics.", lessons: ["Object stores hold durable files at scale. Warehouses offer managed analytical SQL and structured workloads.", "Lakehouse designs add table metadata and transactional behavior over open file storage, combining flexible storage with table-like management.", "Separate storage and compute where possible, and monitor both query cost and data layout choices such as partitioning."], task: "Choose a destination for raw clickstream files and a destination for governed finance reporting. Explain your trade-offs." },
    { id: "performance", title: "Performance and cost", category: "Optimization", level: "Advanced", minutes: 15, icon: "⚡", summary: "Scale throughput while controlling compute and storage costs.", lessons: ["Measure before tuning. Find whether time is spent reading, shuffling, transforming, waiting on an API, or writing output.", "Partitioning and clustering can reduce scans when they match common filters. Too many tiny files or too many partitions can make performance worse.", "Right-size compute, use incremental work, and set budgets or alerts. Track cost per successful run and per unit of useful data."], task: "A query scans a full year of data for a one-day report. Name two layout or query changes to investigate." },
    { id: "backfills", title: "Backfills and recovery", category: "Operations", level: "Advanced", minutes: 14, icon: "🧯", summary: "Repair history and recover safely after incidents.", lessons: ["A backfill recomputes an earlier time range. Bound the range and isolate outputs so it does not overwrite good data unexpectedly.", "Before replay, understand idempotency, downstream dependencies, capacity, and whether consumers need a notice.", "Preserve run metadata and compare row counts and quality checks after recovery. Record the incident and prevention work."], task: "Outline a safe plan to rebuild seven days of a partitioned events table after a transformation bug." },
    { id: "capstone", title: "Capstone: dependable pipeline", category: "Capstone", level: "Advanced", minutes: 22, icon: "🏁", summary: "Design a complete pipeline from source contract to monitored output.", lessons: ["Start with consumers, required freshness, data grain, and access constraints. Then choose the source extraction and target architecture.", "Specify transformations, quality gates, orchestration, retries, lineage, monitoring, and recovery before implementation.", "A reliable pipeline is an owned product: publish its contract, service expectations, runbook, and cost profile."], task: "Design a daily orders pipeline. Include ingestion, raw retention, transformations, tests, orchestration, monitoring, and recovery." }
  ],
  quiz: [
    { q: "In a typical ELT design, where do most transformations run?", options: ["Inside the source application", "In the target analytics platform", "Only on a developer laptop", "Before the data is extracted"], answer: 1, why: "ELT loads source data into the target first, then uses target-side compute to transform it." },
    { q: "What is the main purpose of a watermark in an incremental load?", options: ["Encrypt the source table", "Record how far successful extraction has progressed", "Count the number of target columns", "Schedule a dashboard"], answer: 1, why: "A watermark tracks the source position or time through which data has been successfully processed." },
    { q: "Why should retryable pipeline tasks be idempotent?", options: ["So rerunning them does not create incorrect duplicates", "So they never need monitoring", "So SQL is not required", "So the source schema cannot change"], answer: 0, why: "Idempotency makes a repeated execution produce the same intended state, which is vital for safe retries and replays." },
    { q: "Which check verifies that an identifier appears only once in a dataset?", options: ["Freshness", "Uniqueness", "Accepted values", "Volume"], answer: 1, why: "A uniqueness test catches duplicate keys where one row per identifier is expected." },
    { q: "What is a DAG used for in orchestration?", options: ["Defining task dependencies", "Encrypting records", "Compressing files", "Creating a database index"], answer: 0, why: "A directed acyclic graph defines tasks and the dependency order in which an orchestrator can run them." },
    { q: "What is a common risk of using a full refresh for a very large dataset?", options: ["It cannot be scheduled", "It may waste time and compute reprocessing unchanged data", "It prevents schema validation", "It always loses historical data"], answer: 1, why: "A full refresh can be simple, but it repeatedly processes unchanged history and can increase runtime and cost." },
    { q: "What does CDC commonly capture?", options: ["Only a table's initial snapshot", "Inserts, updates, and deletes from a source change stream", "Only failed API calls", "Dashboard filter clicks"], answer: 1, why: "Change data capture records source changes so downstream systems can apply them incrementally." },
    { q: "What is the grain of a fact table?", options: ["Its storage region", "The meaning of one row", "Its compression level", "The schedule of its refresh"], answer: 1, why: "Declaring grain states precisely what each fact row represents, such as one order line." },
    { q: "Which metric best indicates whether a daily dataset is arriving on time?", options: ["Freshness or time since last successful update", "Number of code comments", "Dashboard color", "File name length"], answer: 0, why: "Freshness measures how current the data is against the expected delivery time." },
    { q: "Why keep raw data immutable when policy allows?", options: ["It makes all transformations unnecessary", "It preserves a replayable source of truth for new models and recovery", "It prevents data quality checks", "It guarantees zero storage cost"], answer: 1, why: "An immutable raw layer lets teams rebuild downstream models and investigate past runs." },
    { q: "What should happen to a critical quality violation?", options: ["Be hidden from consumers", "Be handled according to severity, often blocking publication and raising an alert", "Be counted as a successful run", "Be deleted from monitoring"], answer: 1, why: "Critical contract failures should stop untrusted data from being published and surface an actionable alert." },
    { q: "Which practice best protects a pipeline credential?", options: ["Commit it to a private repository", "Store it in a managed secret store and grant least privilege", "Print it in debug logs", "Reuse a personal password"], answer: 1, why: "Managed secrets and least-privilege identities reduce exposure and simplify rotation." }
  ]
};
