"""Sections 1-6: getting started, data types, strings, lists & tuples, dicts & sets, control flow."""
from schema import Q, S

SECTIONS = [
    S("Getting Started", "🐍", "Module 1", [
        Q("B", "What is Python?",
          "A high-level, general-purpose, interpreted and dynamically typed programming language created by Guido van Rossum and first released in 1991. It is famous for its readable syntax.",
          "Python is used for web back ends, automation, data engineering, data science, machine learning and scripting. Its \"batteries included\" standard library means a lot works without installing anything.",
          'print("Hello, World!")\nprint("Python is", 2026 - 1991, "years old")'),
        Q("B", "What does it mean that Python is \"interpreted\"?",
          "You run the source directly (`python app.py`). CPython first compiles it to bytecode and then its virtual machine executes that bytecode. There is no separate compile-and-link step like in C or Java.",
          "The bytecode is cached in `__pycache__/*.pyc` so the next run starts faster. The `dis` module shows the bytecode a function compiles to.",
          'import dis\n\ndef add(a, b):\n    return a + b\n\nprint(add(2, 3))\nprint([i.opname for i in dis.get_instructions(add)][-2:])'),
        Q("B", "What is CPython, and what other Python implementations exist?",
          "CPython is the reference implementation, written in C, that you get from python.org. Others include PyPy (a fast JIT compiler), MicroPython (microcontrollers), Jython (JVM) and Pyodide (CPython compiled to WebAssembly for the browser).",
          "This site's playground runs Pyodide, which is real CPython compiled to WebAssembly, so your code runs in the browser without any server.",
          'import sys, platform\nprint(platform.python_implementation())\nprint(sys.version_info.major)'),
        Q("B", "What is the REPL?",
          "The Read-Eval-Print Loop: the interactive prompt (`>>>`) you get by running `python` with no arguments. It evaluates each line and prints the result.",
          "It's perfect for quick experiments. In the REPL, `_` holds the last result, and `help(obj)` / `dir(obj)` let you explore any object.",
          'help_text = "Type help(len) in a REPL to read the docs for len"\nprint(help_text)\nprint(len.__doc__.splitlines()[0])'),
        Q("B", "Why does indentation matter in Python?",
          "Indentation defines code blocks (the body of `if`, `for`, `def`, `class`…) instead of braces. Inconsistent indentation raises an `IndentationError`. PEP 8 recommends 4 spaces per level.",
          "Everything indented under the `if` belongs to it; the first line back at the outer level ends the block.",
          'temperature = 30\nif temperature > 25:\n    print("hot")\n    print("still inside the if")\nprint("outside the if")'),
        Q("B", "What is PEP 8?",
          "Python's official style guide: 4-space indentation, `snake_case` for functions and variables, `PascalCase` for classes, `UPPER_CASE` for constants, spaces around operators and a recommended line length of 79 characters.",
          "Consistent style makes code easier to read and review. Tools like `black` and `ruff format` format code automatically, and `ruff`/`flake8` flag style issues.",
          'MAX_RETRIES = 3            # constant\n\nclass OrderLoader:         # class\n    def load_orders(self):  # method\n        return "loaded"\n\nprint(OrderLoader().load_orders(), MAX_RETRIES)'),
        Q("B", "How do you write comments and docstrings?",
          "`#` starts a comment that runs to the end of the line. A string literal as the first statement of a module, function or class is its docstring, available as `obj.__doc__` and through `help()`.",
          "Comments explain *why* code does something; docstrings document *what* a function does and how to call it.",
          'def area(width, height):\n    """Return the area of a rectangle."""\n    # multiplication is enough for rectangles\n    return width * height\n\nprint(area(3, 4))\nprint(area.__doc__)'),
        Q("I", "What is a virtual environment and why should you use one?",
          "An isolated Python environment with its own interpreter link and `site-packages`. Create it with `python -m venv .venv`, activate it, then `pip install` only affects that project.",
          "Without one, every project shares the same global packages, and project A needing `pandas 1.x` while project B needs `pandas 2.x` becomes a conflict.",
          'python -m venv .venv\nsource .venv/bin/activate      # Windows: .venv\\Scripts\\activate\npip install requests pandas\npip freeze > requirements.txt\ndeactivate', lang="bash"),
        Q("B", "What is pip?",
          "The standard package installer. It downloads packages from PyPI (the Python Package Index): `pip install requests`, `pip install -r requirements.txt`, `pip list`, `pip uninstall`.",
          "Run it as `python -m pip …` to be sure you're installing into the same interpreter you run your code with.",
          'python -m pip install --upgrade pip\npython -m pip install "requests>=2.31"\npython -m pip show requests', lang="bash"),
        Q("I", "Python is dynamically but strongly typed. What does that mean?",
          "Dynamic: types belong to objects, not variable names, and are checked at runtime, so the same name can later hold a different type. Strong: Python won't silently convert unrelated types, so `\"1\" + 1` raises `TypeError`.",
          "JavaScript is dynamic *and* weak (`\"1\" + 1` gives `\"11\"`). Python makes you convert explicitly: `int(\"1\") + 1`.",
          'x = 5\nprint(type(x).__name__)\nx = "five"\nprint(type(x).__name__)\ntry:\n    "1" + 1\nexcept TypeError as err:\n    print("TypeError:", err)'),
        Q("B", "How do you read input and print output?",
          "`input(prompt)` reads a line from the user as a `str`; `print()` writes to standard output and accepts `sep=` and `end=` to control separators and line endings.",
          "`input()` always returns text, so convert it: `age = int(input(\"Age? \"))`.",
          'print("a", "b", "c", sep="-")\nprint("no newline", end=" | ")\nprint("next")'),
        Q("I", "What is the Zen of Python?",
          "A set of 19 guiding principles by Tim Peters, shown by `import this`. Examples: \"Beautiful is better than ugly\", \"Explicit is better than implicit\", \"Readability counts\", \"There should be one obvious way to do it\".",
          "It explains why Python favours clear, readable code over clever one-liners. Interviewers sometimes ask for your favourite line and why.",
          'import io, contextlib\nbuf = io.StringIO()\nwith contextlib.redirect_stdout(buf):\n    import this\nprint(buf.getvalue().splitlines()[2])'),
    ]),

    S("Variables & Data Types", "🔢", "Module 2", [
        Q("B", "What are Python's core built-in data types?",
          "Numbers: `int`, `float`, `complex`. Text: `str`. Boolean: `bool`. Nothing: `None`. Collections: `list`, `tuple`, `dict`, `set`, `frozenset`. Binary: `bytes`, `bytearray`.",
          "Knowing which types are mutable (list, dict, set) and which are immutable (int, str, tuple) explains most of Python's surprising behaviour.",
          'values = [42, 3.14, 2 + 3j, "hi", True, None, [1], (1,), {"k": 1}, {1}]\nfor v in values:\n    print(type(v).__name__, end=" ")'),
        Q("B", "How do you check the type of a value?",
          "`type(x)` returns its exact class. `isinstance(x, SomeType)` checks the type *including subclasses* and accepts a tuple of types. Prefer `isinstance` in real code.",
          "`bool` is a subclass of `int`, so `isinstance(True, int)` is `True` while `type(True) is int` is `False`.",
          'print(type(3.14))\nprint(isinstance(True, int), type(True) is int)\nprint(isinstance(3, (int, float)))'),
        Q("B", "What is a variable in Python, really?",
          "A name bound to an object: a label, not a box. Assignment never copies; it makes a name point at an object. Two names can refer to the same object.",
          "That's why changing a list through one name is visible through the other. To get an independent list, copy it (`b = a.copy()`).",
          'a = [1, 2]\nb = a          # same list, two names\nb.append(3)\nprint(a)\nprint(a is b)'),
        Q("I", "What is the difference between `==` and `is`?",
          "`==` compares values (calls `__eq__`). `is` compares identity: whether both names refer to the very same object. Use `is` only for singletons like `None`, `True` and `False`.",
          "Two separate lists with the same contents are equal but not identical. `x is None` is the idiomatic None check.",
          'a = [1, 2]\nb = [1, 2]\nprint(a == b, a is b)\nresult = None\nprint(result is None)'),
        Q("I", "Which types are mutable and which are immutable?",
          "Mutable (can change in place): `list`, `dict`, `set`, `bytearray` and most user-defined objects. Immutable: `int`, `float`, `bool`, `str`, `tuple`, `frozenset`, `bytes`.",
          "\"Changing\" an immutable object really creates a new one and rebinds the name. Only immutable (hashable) values can be dict keys or set members.",
          'point = (1, 2)\ntry:\n    point[0] = 9\nexcept TypeError as err:\n    print(err)\nname = "py"\nname += "thon"   # a new string object\nprint(name)'),
        Q("B", "What is `None`?",
          "A singleton object of type `NoneType` meaning \"no value\". Functions without a `return` return `None`. Compare with `is None`, not `== None`.",
          "It's commonly used for optional arguments and \"not found\" results, e.g. `dict.get()` returns `None` for a missing key.",
          'def greet():\n    print("hi")\n\nresult = greet()\nprint(result, type(result).__name__)'),
        Q("B", "How do `/`, `//`, `%` and `**` work?",
          "`/` is true division and always returns a float. `//` is floor division (rounds toward negative infinity). `%` is the remainder, with the sign of the divisor. `**` is power. `divmod(a, b)` returns `(a // b, a % b)`.",
          "Floor division surprises people with negatives: `-7 // 2` is `-4`, not `-3`.",
          'print(7 / 2, 7 // 2, 7 % 2)\nprint(-7 // 2, -7 % 3)\nprint(2 ** 10, divmod(17, 5))'),
        Q("I", "Why is `0.1 + 0.2` not equal to `0.3`?",
          "Floats are binary (IEEE 754 double precision), and 0.1 cannot be represented exactly in binary, so tiny rounding errors appear. Compare floats with `math.isclose()`, and use `decimal.Decimal` for money.",
          "This isn't a Python bug; every language using IEEE floats does the same.",
          'print(0.1 + 0.2)\nimport math\nprint(math.isclose(0.1 + 0.2, 0.3))\nfrom decimal import Decimal\nprint(Decimal("0.1") + Decimal("0.2"))'),
        Q("B", "How do you convert between types?",
          "Call the type as a function: `int(\"42\")`, `float(\"3.5\")`, `str(10)`, `list(\"abc\")`, `tuple([1, 2])`, `set([1, 1, 2])`, `bool(0)`. Invalid text raises `ValueError`.",
          "`int(\"3.5\")` fails; use `int(float(\"3.5\"))`. `int(3.9)` truncates toward zero, giving 3.",
          'print(int("42") + 1, float("3.5"), str(10) + "!")\nprint(list("abc"), set([1, 1, 2]), int(3.9))\ntry:\n    int("3.5")\nexcept ValueError as err:\n    print("ValueError:", err)'),
        Q("I", "What is truthiness?",
          "Every object has a truth value. Falsy values: `None`, `False`, `0`, `0.0`, `\"\"`, `[]`, `()`, `{}`, `set()` and `range(0)`. Everything else is truthy.",
          "It lets you write `if items:` instead of `if len(items) > 0:`. Careful: the string `\"0\"` and the list `[0]` are truthy.",
          'for value in [0, "", [], None, "0", [0], 0.0001]:\n    print(repr(value), bool(value))'),
        Q("A", "Is there a maximum size for Python integers?",
          "No. `int` has arbitrary precision and is limited only by memory. `float` is a 64-bit IEEE 754 double with a maximum of about 1.8e308.",
          "Python handles big numbers (cryptography, factorials) out of the box, unlike languages with fixed 32/64-bit integers.",
          'print(2 ** 100)\nimport math\nprint(len(str(math.factorial(100))), "digits in 100!")\nimport sys\nprint(sys.float_info.max)'),
        Q("I", "How do multiple assignment, swapping and star-unpacking work?",
          "`a, b = 1, 2` unpacks a tuple; `a, b = b, a` swaps without a temp variable; `first, *rest = items` collects the remainder into a list.",
          "The right side is evaluated completely before any assignment happens, which is why the swap works.",
          'a, b = 1, 2\na, b = b, a\nprint(a, b)\nfirst, *middle, last = [10, 20, 30, 40]\nprint(first, middle, last)'),
    ]),

    S("Strings", "🔤", "Module 3", [
        Q("B", "How do you create strings?",
          "With single quotes, double quotes or triple quotes (`'''`/`\"\"\"`) for multi-line text. Strings are immutable sequences of Unicode characters.",
          "Single and double quotes are equivalent; pick one and use the other when the text contains quotes: `\"it's\"`.",
          "single = 'hello'\ndouble = \"it's fine\"\nmulti = '''line one\nline two'''\nprint(single, double)\nprint(multi)"),
        Q("B", "How does string slicing work?",
          "`s[start:stop:step]`: `start` is included, `stop` is excluded, negative indexes count from the end, and omitted parts default to the whole string. `s[::-1]` reverses it.",
          "Slicing never raises an IndexError; out-of-range slices are simply clipped.",
          's = "Python"\nprint(s[0], s[-1], s[1:4], s[:2], s[-3:])\nprint(s[::2], s[::-1], s[10:])'),
        Q("B", "What are f-strings?",
          "Formatted string literals (Python 3.6+): prefix with `f` and put expressions in braces, like `f\"Hi {name}\"`. They support format specs (`{price:.2f}`, `{n:,}`), conversions (`{x!r}`) and self-documenting `{x=}` (3.8+).",
          "f-strings are the fastest and most readable way to format text; prefer them over `%` formatting and `.format()`.",
          'name, pi, n = "Ada", 3.14159, 1234567\nprint(f"{name} likes {pi:.2f} and {n:,}")\nprint(f"{name=}, {pi=:.1f}")\nprint(f"{name!r} is {len(name)} chars")'),
        Q("B", "Which string methods are used most often?",
          "`lower()`, `upper()`, `title()`, `strip()`, `split()`, `join()`, `replace()`, `startswith()`, `endswith()`, `find()`, `count()`, `isdigit()`.",
          "They all return new strings (or values), because strings can't change in place.",
          'raw = "  Snowflake and Python  "\nclean = raw.strip()\nprint(clean.lower(), "|", clean.upper())\nprint(clean.replace("and", "&"), clean.startswith("Snow"), clean.count("a"))'),
        Q("I", "Why use `\"\".join()` instead of `+=` in a loop?",
          "Strings are immutable, so each `+=` can create a brand-new string and copy everything so far (quadratic in the worst case). `\"sep\".join(parts)` computes the size once and builds the result in a single pass.",
          "Collect pieces in a list, then join them at the end. `join` only accepts strings, so convert numbers with `map(str, …)`.",
          'words = ["fast", "and", "clean"]\nprint(" ".join(words))\nprint(", ".join(map(str, [1, 2, 3])))'),
        Q("I", "What is the difference between `split()` and `split(\" \")`?",
          "`split()` with no argument splits on any run of whitespace (spaces, tabs, newlines) and drops empty strings. `split(\" \")` splits on every single space and keeps empty strings between consecutive spaces.",
          "Use `split()` for messy human text; use an explicit separator for structured data like CSV lines.",
          's = "a  b\\tc"\nprint(s.split())\nprint(s.split(" "))\nprint("2024-05-06".split("-", 1))'),
        Q("I", "What are raw strings?",
          "String literals prefixed with `r` where backslashes are kept literally instead of starting escape sequences. `r\"\\n\"` is two characters: a backslash and an `n`.",
          "Use them for regular expressions and Windows paths so you don't have to double every backslash.",
          'print(len("\\n"), len(r"\\n"))\nprint(r"C:\\new\\table")'),
        Q("I", "What is the difference between `str` and `bytes`?",
          "`str` is Unicode text; `bytes` is a sequence of raw 8-bit values. `text.encode(\"utf-8\")` converts text to bytes and `data.decode(\"utf-8\")` converts back.",
          "Files, sockets and HTTP carry bytes; your program should work with `str` internally and encode/decode at the edges.",
          's = "café"\nb = s.encode("utf-8")\nprint(b, len(s), len(b))\nprint(b.decode("utf-8"))'),
        Q("B", "How do you check whether a string contains a substring?",
          "Use the `in` operator: `\"py\" in \"python\"`. `find()` returns the index or -1; `index()` returns the index or raises `ValueError`.",
          "`in` is the most readable choice when you only need yes/no.",
          'text = "python academy"\nprint("academy" in text, text.find("py"), text.find("java"))'),
        Q("I", "How do you pad, align and format numbers in f-strings?",
          "With the format-spec mini-language after a colon: `>` right, `<` left, `^` center with a width (`{x:>8}`), zero padding (`{n:05}`), precision (`{f:.3f}`), percentages (`{p:.1%}`), thousands (`{n:,}`), binary/hex (`{n:b}`, `{n:x}`).",
          "Great for printing aligned tables and reports.",
          'print(f"[{\'hi\':>6}] [{\'hi\':^6}] [{\'hi\':<6}]")\nprint(f"{7:03} {0.256:.1%} {255:x} {10:b} {1e6:,.0f}")'),
        Q("I", "Are strings sequences? Can you change a character?",
          "Yes, they're sequences: you can iterate over them, index them and use `len` and `in`. But they're immutable: `s[0] = \"J\"` raises `TypeError`. Build a new string instead.",
          "For many character-level edits, convert to a list, modify it and `\"\".join()` it back.",
          's = "python"\nfor ch in s[:3]:\n    print(ch, end=" ")\nprint()\ntry:\n    s[0] = "J"\nexcept TypeError as err:\n    print(err)\nprint("J" + s[1:])'),
        Q("A", "What is string interning, and why shouldn't you compare strings with `is`?",
          "CPython reuses a single object for some strings (identifier-like literals, compile-time constants) to save memory. Whether two equal strings are the same object is an implementation detail.",
          "`is` might happen to return True for short literals and False for strings built at runtime. Always compare text with `==`. `sys.intern()` interns strings explicitly when you need it.",
          'a = "hello"\nb = "".join(["hel", "lo"])\nprint(a == b)\nimport sys\nprint(sys.intern(a) is sys.intern(b))'),
    ]),

    S("Lists & Tuples", "📋", "Module 4", [
        Q("B", "What is the difference between a list and a tuple?",
          "A list (`[1, 2]`) is mutable: you can add, remove and change items. A tuple (`(1, 2)`) is immutable. Tuples of hashable items are hashable, so they can be dict keys or set members.",
          "Use a list for a collection that changes (a queue of tasks) and a tuple for a fixed record (a point `(x, y)` or a database row).",
          'coords = {(0, 0): "origin"}      # tuple as a dict key\ntasks = ["load", "clean"]\ntasks.append("report")\nprint(coords[(0, 0)], tasks)'),
        Q("B", "What is the difference between `append()` and `extend()`?",
          "`append(x)` adds one item (even if that item is a list). `extend(iterable)` adds each element of the iterable. `insert(i, x)` adds at a position; `+` creates a new concatenated list.",
          "A classic bug is calling `append` with a list when you meant `extend`, which produces a nested list.",
          'a = [1, 2]\na.append([3, 4])\nb = [1, 2]\nb.extend([3, 4])\nprint(a)\nprint(b)'),
        Q("B", "How do you remove items from a list?",
          "`remove(value)` deletes the first matching value (raises `ValueError` if absent); `pop(i)` removes and returns the item at index `i` (the last item by default); `del a[i]` or `del a[i:j]` deletes by position; `clear()` empties it.",
          "`pop()` from the end is O(1); removing from the front is O(n) because everything shifts.",
          'a = ["x", "y", "z", "y"]\na.remove("y")\nlast = a.pop()\ndel a[0]\nprint(a, last)'),
        Q("I", "What is the difference between `sort()` and `sorted()`?",
          "`list.sort()` sorts the list in place and returns `None`. `sorted(iterable)` returns a new sorted list from any iterable. Both accept `key=` and `reverse=` and are stable.",
          "`key=` receives a function applied to each item; `key=str.lower` gives case-insensitive sorting.",
          'words = ["banana", "Apple", "cherry"]\nprint(sorted(words))\nprint(sorted(words, key=str.lower))\nprint(sorted(words, key=len, reverse=True))\nprint(words.sort())'),
        Q("I", "Shallow copy vs deep copy?",
          "A shallow copy (`a.copy()`, `a[:]`, `list(a)`) creates a new outer list but shares the inner objects. `copy.deepcopy(a)` recursively copies everything.",
          "With nested lists or dicts, a shallow copy still shares the inner lists, so changes to them show up in both.",
          'import copy\na = [[1, 2], [3]]\nshallow = a.copy()\ndeep = copy.deepcopy(a)\na[0].append(99)\nprint(shallow)\nprint(deep)'),
        Q("A", "Why is `[[0] * 3] * 3` a trap?",
          "The outer `* 3` repeats a reference to the *same* inner list three times, so changing one row changes all of them. Build the rows with a comprehension instead: `[[0] * 3 for _ in range(3)]`.",
          "`[0] * 3` on its own is fine because integers are immutable.",
          'grid = [[0] * 3] * 3\ngrid[0][0] = 1\nprint(grid)\nok = [[0] * 3 for _ in range(3)]\nok[0][0] = 1\nprint(ok)'),
        Q("B", "How do you create a tuple with one element?",
          "Add a trailing comma: `(5,)` or just `5,`. Without the comma, `(5)` is simply the integer 5 in parentheses.",
          "It's the comma that makes a tuple, not the parentheses (except for the empty tuple `()`).",
          'print(type((5)).__name__, type((5,)).__name__)\nt = 1, 2, 3\nprint(t)'),
        Q("I", "What are the time complexities of common list operations?",
          "Index read/write O(1); `append` and `pop()` amortized O(1); `insert(0, x)` and `pop(0)` O(n); `x in list` O(n); sorting O(n log n).",
          "Need fast membership tests? Use a `set` (O(1) on average). Need a queue? Use `collections.deque`, which has O(1) appends and pops at both ends.",
          'from collections import deque\nq = deque([1, 2, 3])\nq.appendleft(0)\nq.pop()\nprint(q)\nbig = set(range(1_000_000))\nprint(999_999 in big)'),
        Q("I", "What is a named tuple?",
          "A tuple subclass with named fields, from `collections.namedtuple` or `typing.NamedTuple`. It's lightweight, immutable and readable: `p.x` instead of `p[0]`.",
          "Great for records like rows from a CSV. If you need mutability or defaults, use a `dataclass`.",
          'from typing import NamedTuple\n\nclass Point(NamedTuple):\n    x: int\n    y: int = 0\n\np = Point(2, 3)\nprint(p, p.x + p.y, Point(5))'),
        Q("B", "How do you get the length, min, max and sum of a list?",
          "Built-ins: `len(a)`, `min(a)`, `max(a)`, `sum(a)`. Methods: `a.count(x)` counts occurrences, `a.index(x)` finds the first position.",
          "`min`/`max` accept `key=` too, e.g. `max(words, key=len)` returns the longest word.",
          'scores = [72, 95, 88, 95]\nprint(len(scores), min(scores), max(scores), sum(scores) / len(scores))\nprint(scores.count(95), scores.index(95), max(["hi", "hello"], key=len))'),
        Q("I", "How does slice assignment work?",
          "Assigning to a slice replaces that region with the items of an iterable, and the list can grow or shrink: `a[1:3] = [\"x\"]`. `a[:] = …` replaces all contents in place; `del a[::2]` deletes every other item.",
          "`a[:] = new` keeps the same list object, so other references see the change, unlike `a = new`.",
          'a = [0, 1, 2, 3, 4]\na[1:3] = ["x"]\nprint(a)\na[:0] = ["start"]\nprint(a)\ndel a[::2]\nprint(a)'),
        Q("I", "How do you unpack a list into function arguments?",
          "Use `*` in a call: `f(*items)` passes each element as a separate positional argument, and `**mapping` passes keys as keyword arguments.",
          "`print(*items)` is a quick way to print list items separated by spaces.",
          'def total(a, b, c):\n    return a + b + c\n\nnums = [1, 2, 3]\nprint(total(*nums))\nprint(*nums, sep=" + ")'),
    ]),

    S("Dictionaries & Sets", "🗂️", "Module 5", [
        Q("B", "What is a dictionary?",
          "A mutable mapping from unique, hashable keys to values: `{\"name\": \"Ada\"}`. It's implemented as a hash table, so lookup, insert and delete are O(1) on average. Since Python 3.7 dicts preserve insertion order.",
          "Dicts are everywhere in Python: JSON, keyword arguments, object attributes (`obj.__dict__`) and caches.",
          'user = {"name": "Ada", "lang": "python"}\nuser["level"] = 3\nprint(user["name"], len(user), list(user))'),
        Q("B", "What is the difference between `d[key]` and `d.get(key)`?",
          "`d[key]` raises `KeyError` when the key is missing. `d.get(key)` returns `None`, or the default you pass as the second argument.",
          "Use `[]` when a missing key is a bug; use `get` when missing is normal.",
          'd = {"a": 1}\nprint(d.get("b"), d.get("b", 0))\ntry:\n    d["b"]\nexcept KeyError as err:\n    print("KeyError:", err)'),
        Q("B", "How do you loop over a dictionary?",
          "`for k in d` loops over keys; `for k, v in d.items()` loops over key-value pairs; `d.keys()` and `d.values()` give views of the keys and values.",
          "`.items()` is the idiomatic way when you need both keys and values.",
          'prices = {"apple": 1.2, "pear": 0.8}\nfor fruit, price in prices.items():\n    print(f"{fruit}: ${price:.2f}")'),
        Q("I", "What can be used as a dictionary key?",
          "Any hashable object: `str`, `int`, `float`, `bool`, `None`, `frozenset`, and tuples of hashable items. Mutable containers (`list`, `dict`, `set`) are unhashable and raise `TypeError`.",
          "A key's hash must never change, which is why mutable objects aren't allowed.",
          'd = {(1, 2): "point", frozenset({1}): "fs"}\nprint(d[(1, 2)])\ntry:\n    d[[1, 2]] = "list"\nexcept TypeError as err:\n    print(err)'),
        Q("I", "How do you merge two dictionaries?",
          "`a | b` (3.9+) returns a new merged dict, `a |= b` updates `a` in place, `{**a, **b}` works in older versions, and `a.update(b)` also merges in place. On duplicate keys, the right-hand side wins.",
          "Merging is handy for combining default settings with user overrides.",
          'defaults = {"theme": "dark", "size": 12}\nuser = {"size": 14}\nprint(defaults | user)\nprint({**defaults, **user, "lang": "py"})'),
        Q("I", "What are `defaultdict` and `Counter`?",
          "Both come from `collections`. `defaultdict(factory)` creates missing values automatically, e.g. `defaultdict(list)` for grouping. `Counter` counts hashable items and has `most_common()`.",
          "They remove the \"if key not in d: d[key] = …\" boilerplate.",
          'from collections import Counter, defaultdict\nprint(Counter("mississippi").most_common(2))\ngroups = defaultdict(list)\nfor word in ["apple", "avocado", "banana"]:\n    groups[word[0]].append(word)\nprint(dict(groups))'),
        Q("I", "What does `setdefault()` do?",
          "`d.setdefault(key, default)` returns `d[key]` if the key exists; otherwise it inserts `key: default` and returns the default.",
          "It's a one-liner for grouping without `defaultdict`, but note that the default is evaluated every time.",
          'index = {}\nfor word in ["sql", "snow", "python"]:\n    index.setdefault(word[0], []).append(word)\nprint(index)'),
        Q("B", "What is a set?",
          "An unordered collection of unique, hashable items with O(1) average membership tests: `{1, 2, 3}`. `{}` is an empty *dict*, so use `set()` for an empty set.",
          "Sets are perfect for removing duplicates and for fast `in` checks.",
          'print(type({}).__name__, type(set()).__name__)\ntags = set(["py", "sql", "py"])\ntags.add("dbt")\nprint(sorted(tags), "py" in tags)'),
        Q("I", "Which operations do sets support?",
          "`|` union, `&` intersection, `-` difference, `^` symmetric difference, and `<=` / `issubset()`, `>=` / `issuperset()`, `isdisjoint()`.",
          "Example: `required - have` gives the skills you're missing.",
          'a = {1, 2, 3}\nb = {2, 3, 4}\nprint(a | b, a & b, a - b, a ^ b)\nprint({2, 3} <= a, a.isdisjoint({9}))'),
        Q("I", "How do you remove duplicates from a list while keeping the order?",
          "`list(dict.fromkeys(items))`. Dict keys are unique and keep insertion order. `list(set(items))` also removes duplicates but loses the order.",
          "This is a classic interview question and a real everyday need when cleaning data.",
          'items = ["b", "a", "b", "c", "a"]\nprint(list(dict.fromkeys(items)))\nprint(sorted(set(items)))'),
        Q("I", "How do you write a dict comprehension, and how do you invert a dict?",
          "`{key_expr: value_expr for item in iterable if cond}`. To invert a dict: `{v: k for k, v in d.items()}` (duplicate values collapse, and the last one wins).",
          "Dict comprehensions are the cleanest way to build lookup tables.",
          'prices = {"apple": 1.2, "pear": 0.8, "kiwi": 2.5}\nprint({v: k for k, v in prices.items()})\nprint({k: v for k, v in prices.items() if v > 1})'),
        Q("A", "How does a dict work internally, and why must keys be hashable?",
          "`hash(key)` picks a slot in an internal table. Collisions are resolved by probing other slots. Lookups compare hashes first and then `==`. Equal objects must have equal hashes, and a key's hash must not change while it's in the dict.",
          "If you define `__eq__` on a class, you must also define a matching `__hash__` (or leave it unhashable). Otherwise dicts and sets behave incorrectly.",
          'print(hash(1) == hash(1.0) == hash(True))\nd = {1: "int"}\nd[1.0] = "float"\nd[True] = "bool"\nprint(d)'),
    ]),

    S("Control Flow", "🔀", "Module 6", [
        Q("B", "How do `if`, `elif` and `else` work?",
          "Conditions are checked top to bottom, and only the first true branch runs. `elif` can repeat; `else` is optional and runs when nothing matched.",
          "Python has no `switch`; use `elif` chains, a dict lookup or `match` (3.10+).",
          'def grade(score):\n    if score >= 90:\n        return "A"\n    elif score >= 75:\n        return "B"\n    else:\n        return "C"\n\nprint(grade(95), grade(80), grade(40))'),
        Q("B", "How do `for` loops and `range()` work?",
          "`for x in iterable` visits every item of any iterable (list, str, dict, file, generator). `range(start, stop, step)` produces numbers lazily, and `stop` is excluded.",
          "Python's `for` is a for-each loop. Use `enumerate()` when you also need the index.",
          'print(list(range(5)), list(range(2, 10, 3)), list(range(5, 0, -2)))\nfor i, name in enumerate(["Ada", "Guido"], start=1):\n    print(i, name)'),
        Q("B", "What do `break`, `continue` and `pass` do?",
          "`break` exits the innermost loop immediately; `continue` skips to the next iteration; `pass` does nothing and is a placeholder where a statement is required.",
          "`pass` is useful for empty functions or classes you'll fill in later.",
          'for n in range(10):\n    if n % 2:\n        continue\n    if n > 6:\n        break\n    print(n, end=" ")\n\ndef todo():\n    pass'),
        Q("I", "What does `else` on a `for` or `while` loop do?",
          "The `else` block runs only if the loop finished without hitting `break`. It's handy for search loops (\"not found\").",
          "Think of it as \"no break\". It removes the need for a `found = False` flag.",
          'for n in [3, 5, 7]:\n    if n % 2 == 0:\n        print("found an even number")\n        break\nelse:\n    print("no even numbers")'),
        Q("B", "What is Python's ternary (conditional) expression?",
          "`value_if_true if condition else value_if_false`. It's an expression, so it can be used inside assignments, f-strings and comprehensions.",
          "Keep it short. For complex logic, a normal `if` statement is clearer.",
          'age = 20\nstatus = "adult" if age >= 18 else "minor"\nprint(status, f"{\'even\' if age % 2 == 0 else \'odd\'}")'),
        Q("I", "What is the `match` statement?",
          "Structural pattern matching (Python 3.10+). It matches a value against patterns: literals, sequences, mappings, classes, captures, guards (`if`) and the wildcard `_`.",
          "It is more powerful than a switch because it can destructure data like tuples and dicts while matching.",
          'def describe(point):\n    match point:\n        case (0, 0):\n            return "origin"\n        case (x, 0):\n            return f"on the x-axis at {x}"\n        case (x, y) if x == y:\n            return "on the diagonal"\n        case (x, y):\n            return f"point {x},{y}"\n        case _:\n            return "not a point"\n\nprint(describe((0, 0)), "|", describe((3, 0)), "|", describe((2, 2)), "|", describe("hi"))'),
        Q("I", "What is the walrus operator `:=`?",
          "An assignment expression (3.8+) that assigns and returns a value in one step, e.g. inside an `if`, a `while` or a comprehension.",
          "It avoids computing a value twice. Use it sparingly for readability.",
          'data = [4, 8, 15, 16, 23, 42]\nif (n := len(data)) > 3:\n    print(f"{n} items is a lot")\nprint([y for x in data if (y := x * 2) > 30])'),
        Q("I", "What do `and` and `or` actually return?",
          "They short-circuit and return one of the operands, not necessarily `True` or `False`. `a or b` returns `a` if it's truthy, else `b`; `a and b` returns `a` if it's falsy, else `b`.",
          "That's why `name = user_input or \"Guest\"` works as a default value.",
          'print(0 or "default", "a" and "b", None and 1, [] or {} or "last")'),
        Q("I", "What are chained comparisons?",
          "Python lets you chain comparisons like maths: `1 < x < 10` means `1 < x and x < 10`, with `x` evaluated only once.",
          "Any comparison operators can be chained, e.g. `a == b == c`.",
          'x = 5\nprint(1 < x < 10, 10 > x > 7, 1 == 1.0 == True)'),
        Q("B", "How do you loop with an index?",
          "Use `enumerate(iterable, start=0)`, which yields `(index, item)` pairs. Avoid `for i in range(len(items))`.",
          "`enumerate` is more readable and works with any iterable, not just lists.",
          'for i, lang in enumerate(["python", "sql", "bash"], start=1):\n    print(f"{i}. {lang}")'),
        Q("A", "Why shouldn't you modify a list while looping over it?",
          "Removing items shifts the remaining elements, so the loop's internal index skips the next element. Loop over a copy (`for x in items[:]`) or, better, build a new list with a comprehension.",
          "In this example the second 2 is never checked, so one 2 survives.",
          'nums = [1, 2, 2, 3]\nfor n in nums:\n    if n == 2:\n        nums.remove(n)\nprint(nums)\nnums = [1, 2, 2, 3]\nprint([n for n in nums if n != 2])'),
        Q("I", "How does a `while` loop work, and how do you avoid infinite loops?",
          "`while condition:` repeats while the condition is truthy. Make sure something in the body moves toward making it false, or `break` out of it.",
          "`while True:` with an explicit `break` is idiomatic for \"loop until done\" logic, like retries or reading input.",
          'attempts = 0\nwhile True:\n    attempts += 1\n    if attempts == 3:\n        print("connected after", attempts, "attempts")\n        break'),
    ]),
]
