"""Sections 13-19: modules, decorators, concurrency, testing, data, Python + Snowflake, interview."""
from schema import Q, S

SECTIONS = [
    S("Modules & Packages", "📦", "Module 13", [
        Q("B", "What is a module?",
          "Any `.py` file. Importing it runs its top-level code once, and its functions, classes and variables become available as attributes: `import math; math.sqrt(9)`.",
          "Modules are cached in `sys.modules`, so a second `import` doesn't re-run the file.",
          'import math\nimport sys\nprint(math.sqrt(9), "math" in sys.modules)'),
        Q("B", "What are the different ways to import?",
          "`import math` (then use `math.pi`), `from math import pi, sqrt` (names directly), `import numpy as np` (an alias), `from os import path as p`.",
          "Plain `import module` keeps it obvious where each name comes from.",
          'import math\nfrom math import pi, sqrt\nimport statistics as stats\nprint(math.floor(pi), sqrt(16), stats.mean([1, 2, 3, 4]))'),
        Q("I", "What does `if __name__ == \"__main__\":` do?",
          "`__name__` is `\"__main__\"` when a file is run directly and the module's name when it's imported. The guard lets a file work both as a script and as an importable module, without side effects on import.",
          "Put the script's entry point (argument parsing, `main()`) under the guard.",
          'def main():\n    print("running as a script")\n\nprint("__name__ is", __name__)\nif __name__ == "__main__":\n    main()'),
        Q("I", "What is a package?",
          "A directory of modules, usually containing an `__init__.py` that runs when the package is imported and can expose a public API. You import with dotted paths: `from mypkg.loaders import csv_loader`.",
          "Directories without `__init__.py` still work as namespace packages (PEP 420), but an explicit `__init__.py` is clearer.",
          'myproject/\n├── pyproject.toml\n└── src/\n    └── etl/\n        ├── __init__.py\n        ├── extract.py\n        ├── transform.py\n        └── load.py', lang="text"),
        Q("I", "How does Python find modules to import?",
          "It searches the directories in `sys.path` in order: the script's directory (or the current directory in the REPL), directories from the `PYTHONPATH` environment variable, then the standard library and `site-packages`.",
          "Naming your own file `random.py` or `pandas.py` shadows the real module, which is a classic confusing bug.",
          'import sys\nprint(type(sys.path).__name__, len(sys.path) > 0)\nimport json\nprint(json.__name__)'),
        Q("I", "Why avoid `from module import *`?",
          "It dumps every public name into your namespace, which hides where names come from, can silently overwrite your own variables and confuses linters. A module can limit it with `__all__`.",
          "Explicit imports are part of \"explicit is better than implicit\".",
          'from math import *\nprint(pi, e > 2)\n# which module did "e" come from? explicit imports make that obvious'),
        Q("I", "What is `pyproject.toml`, and how does it relate to `requirements.txt`?",
          "`pyproject.toml` is the standard project configuration file (PEP 621): name, version, dependencies, build backend and tool settings (ruff, pytest). `requirements.txt` is a plain list of pinned packages, often used for deployments.",
          "Libraries declare flexible ranges in `pyproject.toml`; applications pin exact versions with a lock file or requirements file.",
          '[project]\nname = "etl-pipeline"\nversion = "0.1.0"\nrequires-python = ">=3.10"\ndependencies = ["pandas>=2.0", "snowflake-connector-python"]\n\n[tool.ruff]\nline-length = 100', lang="text"),
        Q("A", "What is a circular import, and how do you fix one?",
          "Module A imports B while B imports A. One of them sees a partially initialised module, causing `ImportError` or `AttributeError`. Fix it by moving shared code into a third module, importing inside the function that needs it, or restructuring the dependencies.",
          "Circular imports usually point to a design problem: two modules that are too tightly coupled.",
          '# models.py\nfrom services import send_email      # services imports models too -> circular\n\n# fix: import lazily where it is used\ndef notify(user):\n    from services import send_email\n    send_email(user)', lang="text"),
        Q("I", "What is the difference between absolute and relative imports?",
          "Absolute imports use the full path from the project root (`from etl.load import write`). Relative imports use dots within a package (`from .load import write`, `from ..utils import x`). PEP 8 recommends absolute imports.",
          "Relative imports only work inside packages, not in a script run directly.",
          '# inside etl/transform.py\nfrom etl.load import write_table     # absolute (preferred)\nfrom .load import write_table        # relative', lang="text"),
        Q("B", "What is PyPI?",
          "The Python Package Index (pypi.org), the public repository of over 500,000 third-party packages that `pip install` downloads from. Companies often run private mirrors.",
          "Check a package's maintenance, downloads and license before depending on it.",
          'pip install "pandas>=2"\npip index versions pandas\npip download snowflake-connector-python --no-deps', lang="bash"),
    ]),

    S("Decorators & Closures", "✨", "Module 14", [
        Q("I", "What is a closure?",
          "A function that remembers variables from the enclosing scope where it was created, even after the outer function has returned.",
          "Closures let you create configured functions without writing a class.",
          'def make_multiplier(factor):\n    def multiply(x):\n        return x * factor\n    return multiply\n\ndouble, triple = make_multiplier(2), make_multiplier(3)\nprint(double(5), triple(5))\nprint(double.__closure__[0].cell_contents)'),
        Q("I", "What is a decorator?",
          "A function that takes a function and returns a new function that usually wraps the original with extra behaviour. `@decorator` above a `def` is shorthand for `func = decorator(func)`.",
          "Used for logging, timing, caching, retries, access checks and registering routes (Flask, FastAPI).",
          'def loud(func):\n    def wrapper(*args, **kwargs):\n        print(f"calling {func.__name__}")\n        return func(*args, **kwargs).upper()\n    return wrapper\n\n@loud\ndef greet(name):\n    return f"hello {name}"\n\nprint(greet("ada"))'),
        Q("I", "Why use `functools.wraps` in decorators?",
          "Without it, the wrapped function loses its `__name__`, `__doc__` and signature and looks like `wrapper`. `@wraps(func)` copies that metadata so debugging, docs and introspection keep working.",
          "Always put `@wraps(func)` on the inner wrapper.",
          'from functools import wraps\n\ndef plain(f):\n    def wrapper(*a, **k):\n        return f(*a, **k)\n    return wrapper\n\ndef proper(f):\n    @wraps(f)\n    def wrapper(*a, **k):\n        return f(*a, **k)\n    return wrapper\n\n@plain\ndef one(): """Docs for one."""\n@proper\ndef two(): """Docs for two."""\nprint(one.__name__, two.__name__, two.__doc__)'),
        Q("A", "How do you write a decorator that takes arguments?",
          "Add one more layer: an outer function takes the arguments and returns the actual decorator. `@retry(times=3)` calls `retry(times=3)` first, then applies the result to the function.",
          "Three levels: the factory (arguments), the decorator (the function), and the wrapper (the call).",
          'from functools import wraps\n\ndef repeat(times):\n    def decorator(func):\n        @wraps(func)\n        def wrapper(*args, **kwargs):\n            return [func(*args, **kwargs) for _ in range(times)]\n        return wrapper\n    return decorator\n\n@repeat(times=3)\ndef roll():\n    return "🎲"\n\nprint(roll())'),
        Q("I", "Which built-in and standard library decorators are common?",
          "`@property`, `@classmethod`, `@staticmethod`, `@functools.lru_cache`/`@cache`, `@functools.wraps`, `@dataclasses.dataclass`, `@contextlib.contextmanager`, `@abc.abstractmethod`, `@typing.override` (3.12+).",
          "Frameworks add their own, like `@app.get(\"/\")` in FastAPI or `@pytest.fixture`.",
          'from functools import cache\n\n@cache\ndef slow_square(n):\n    print(f"computing {n}")\n    return n * n\n\nprint(slow_square(4), slow_square(4))'),
        Q("A", "What is the late-binding closure pitfall?",
          "Closures look up variables when they're *called*, not when they're created. Lambdas created in a loop all see the loop variable's final value. Bind the current value with a default argument (`lambda i=i: i`) or use `functools.partial`.",
          "A common interview trick question.",
          'late = [lambda: i for i in range(3)]\nprint([f() for f in late])\nbound = [lambda i=i: i for i in range(3)]\nprint([f() for f in bound])'),
        Q("A", "How can a decorator keep state, e.g. count calls?",
          "Store the state on the wrapper function (`wrapper.calls = 0`), in a closure variable with `nonlocal`, or use a class with `__call__` as the decorator.",
          "Function attributes are an easy way to expose the state to callers and tests.",
          'from functools import wraps\n\ndef counted(func):\n    @wraps(func)\n    def wrapper(*args, **kwargs):\n        wrapper.calls += 1\n        return func(*args, **kwargs)\n    wrapper.calls = 0\n    return wrapper\n\n@counted\ndef ping():\n    return "pong"\n\nfor _ in range(3):\n    ping()\nprint(ping.calls)'),
        Q("A", "In what order are stacked decorators applied?",
          "Bottom-up at definition time: `@a` over `@b` over `def f` means `f = a(b(f))`. At call time, the outer wrapper (`a`) runs first and passes the call inward.",
          "Order matters, e.g. put `@app.route` outermost and auth checks inside it.",
          'def a(fn):\n    def w(): return "a(" + fn() + ")"\n    return w\n\ndef b(fn):\n    def w(): return "b(" + fn() + ")"\n    return w\n\n@a\n@b\ndef f():\n    return "f"\n\nprint(f())'),
        Q("I", "How do you write a retry decorator?",
          "Wrap the call in a loop that catches the exception, waits (ideally with exponential backoff) and tries again up to N times, re-raising the error after the last attempt.",
          "Retries are essential for flaky network calls (APIs, databases). Libraries like `tenacity` do this well.",
          'import time\nfrom functools import wraps\n\ndef retry(times=3, delay=0.01):\n    def deco(func):\n        @wraps(func)\n        def wrapper(*args, **kwargs):\n            for attempt in range(1, times + 1):\n                try:\n                    return func(*args, **kwargs)\n                except ConnectionError:\n                    if attempt == times:\n                        raise\n                    time.sleep(delay * 2 ** attempt)\n        return wrapper\n    return deco\n\ncalls = {"n": 0}\n\n@retry(times=3)\ndef flaky():\n    calls["n"] += 1\n    if calls["n"] < 3:\n        raise ConnectionError("timeout")\n    return f"ok after {calls[\'n\']} tries"\n\nprint(flaky())'),
    ]),

    S("Concurrency & Performance", "⚡", "Module 15", [
        Q("I", "What is the GIL?",
          "The Global Interpreter Lock in CPython lets only one thread execute Python bytecode at a time. I/O-bound threads still run concurrently because the GIL is released while they wait, but CPU-bound Python code doesn't speed up with threads.",
          "Use `multiprocessing` for CPU-bound work, and threads or asyncio for I/O-bound work. Python 3.13 adds an experimental free-threaded (no-GIL) build.",
          'import sys\nprint("GIL check available:", hasattr(sys, "_is_gil_enabled"))'),
        Q("I", "Threading vs multiprocessing vs asyncio: when do you use each?",
          "`threading` suits I/O-bound tasks with blocking libraries (such as many HTTP calls). `multiprocessing` suits CPU-bound work, since separate processes bypass the GIL. `asyncio` handles thousands of concurrent I/O operations in one thread with `async`/`await`.",
          "Rule of thumb: waiting on the network → threads or asyncio; crunching numbers → processes (or NumPy, which releases the GIL).",
          'from concurrent.futures import ThreadPoolExecutor\nimport time\n\ndef fetch(n):\n    time.sleep(0.1)          # pretend network call\n    return n * n\n\nstart = time.perf_counter()\nwith ThreadPoolExecutor(max_workers=5) as pool:\n    results = list(pool.map(fetch, range(5)))\nprint(results, "fast:", time.perf_counter() - start < 0.4)', play=False),
        Q("I", "How do `async` and `await` work?",
          "`async def` defines a coroutine. `await` pauses it until another awaitable finishes, letting the event loop run other tasks in the meantime. `asyncio.gather()` runs coroutines concurrently; `asyncio.run(main())` starts the loop.",
          "Only one coroutine runs at a time; concurrency comes from overlapping the waiting. Never call blocking functions like `time.sleep` inside async code.",
          'import asyncio\n\nasync def fetch(name, delay):\n    await asyncio.sleep(delay)\n    return f"{name} done"\n\nasync def main():\n    results = await asyncio.gather(fetch("a", 0.02), fetch("b", 0.01))\n    print(results)\n\nasyncio.run(main())', play=False),
        Q("I", "How do you measure and profile performance?",
          "`time.perf_counter()` for quick timings, `timeit` for micro-benchmarks, `cProfile`/`profile` for finding which functions take the time, and tools like `py-spy`, `line_profiler` and `memory_profiler`.",
          "Measure before optimising. The bottleneck is rarely where you'd guess.",
          'import timeit\nloop = timeit.timeit("r = []\\nfor i in range(1000): r.append(i * 2)", number=500)\ncomp = timeit.timeit("[i * 2 for i in range(1000)]", number=500)\nprint("comprehension faster:", comp < loop)'),
        Q("I", "What does `__slots__` do?",
          "Declaring `__slots__ = (\"x\", \"y\")` replaces the per-instance `__dict__` with fixed storage, so each object uses less memory and attribute access is slightly faster. The trade-off is that you can't add new attributes.",
          "Useful when creating millions of small objects. `@dataclass(slots=True)` (3.10+) generates slots for you.",
          'class P:\n    __slots__ = ("x", "y")\n    def __init__(self, x, y):\n        self.x, self.y = x, y\n\np = P(1, 2)\ntry:\n    p.z = 3\nexcept AttributeError as err:\n    print("AttributeError:", err)\nprint(hasattr(p, "__dict__"))'),
        Q("A", "How does memory management work in CPython?",
          "Primarily through reference counting: an object is freed as soon as its reference count reaches zero. A cyclic garbage collector (the `gc` module) periodically finds groups of objects that only reference each other.",
          "Memory leaks in Python usually come from references that live too long: global caches, closures, unbounded lists.",
          'import gc\nclass Node:\n    pass\na, b = Node(), Node()\na.other, b.other = b, a     # reference cycle\ndel a, b\nprint("collected objects:", gc.collect() >= 2)'),
        Q("I", "Which quick wins make Python code faster?",
          "Use the right data structure (`set`/`dict` for lookups), built-ins and comprehensions instead of manual loops, `str.join`, generators for large data, local variables inside hot loops, `lru_cache` for repeated work, and vectorised NumPy/pandas for numeric data.",
          "Algorithmic improvements (O(n²) → O(n)) beat micro-optimisations every time.",
          'import time\nitems = list(range(20_000))\nlookup = set(items)\nt = time.perf_counter(); _ = [i in items for i in range(0, 20_000, 50)]; slow = time.perf_counter() - t\nt = time.perf_counter(); _ = [i in lookup for i in range(0, 20_000, 50)]; fast = time.perf_counter() - t\nprint("set lookup faster:", fast < slow)'),
        Q("A", "How do you run CPU-bound work in parallel?",
          "Use `multiprocessing` or `concurrent.futures.ProcessPoolExecutor`, which run work in separate processes, each with its own interpreter and GIL. Arguments and results are pickled between processes, so send big chunks of work rather than tiny tasks.",
          "Guard the entry point with `if __name__ == \"__main__\":` because child processes may re-import your module.",
          'from concurrent.futures import ProcessPoolExecutor\n\ndef crunch(n):\n    return sum(i * i for i in range(n))\n\nif __name__ == "__main__":\n    with ProcessPoolExecutor() as pool:\n        print(list(pool.map(crunch, [10_000, 20_000, 30_000])))', run=False, play=False),
    ]),

    S("Testing & Debugging", "🧪", "Module 16", [
        Q("B", "What does `assert` do?",
          "`assert condition, \"message\"` raises `AssertionError` if the condition is falsy. It's used in tests and to state internal invariants, not to validate user input, because asserts are stripped when Python runs with `-O`.",
          "In pytest, a plain `assert` is all you need; it shows detailed diffs when it fails.",
          'def average(xs):\n    assert xs, "list must not be empty"\n    return sum(xs) / len(xs)\n\nprint(average([2, 4]))\ntry:\n    average([])\nexcept AssertionError as err:\n    print("AssertionError:", err)'),
        Q("I", "What does a basic `pytest` test look like?",
          "Put functions named `test_*` in files named `test_*.py`, use plain `assert`, and run `pytest`. Fixtures (`@pytest.fixture`) provide setup; `@pytest.mark.parametrize` runs one test with many inputs; `pytest.raises` checks for exceptions.",
          "pytest is the de facto standard for testing in Python.",
          'import pytest\nfrom pricing import apply_discount\n\n@pytest.mark.parametrize("price, pct, expected", [(100, 10, 90), (50, 0, 50)])\ndef test_apply_discount(price, pct, expected):\n    assert apply_discount(price, pct) == expected\n\ndef test_negative_discount_rejected():\n    with pytest.raises(ValueError):\n        apply_discount(100, -5)', run=False, play=False),
        Q("I", "How do you write tests with the built-in `unittest` module?",
          "Subclass `unittest.TestCase` and write `test_*` methods that use assertion methods like `assertEqual`, `assertTrue` and `assertRaises`. Run them with `python -m unittest`. `setUp`/`tearDown` run around each test.",
          "`unittest` needs no install; pytest can run unittest tests too.",
          'import unittest\n\ndef slugify(text):\n    return "-".join(text.lower().split())\n\nclass SlugTests(unittest.TestCase):\n    def test_spaces(self):\n        self.assertEqual(slugify("Hello World"), "hello-world")\n    def test_empty(self):\n        self.assertEqual(slugify(""), "")\n\nresult = unittest.TextTestRunner(stream=open("test.log", "w")).run(\n    unittest.defaultTestLoader.loadTestsFromTestCase(SlugTests))\nprint("ran", result.testsRun, "tests, ok:", result.wasSuccessful())'),
        Q("I", "How do you debug with `pdb` and `breakpoint()`?",
          "Put `breakpoint()` in your code to pause and open the debugger. Commands: `n` (next line), `s` (step into), `c` (continue), `p expr` (print), `l` (list source), `w` (where / stack), `q` (quit). IDEs like VS Code and PyCharm offer the same features visually.",
          "`python -m pdb script.py` starts a script under the debugger; `pytest --pdb` drops into it on a test failure.",
          'def total(prices):\n    running = 0\n    for p in prices:\n        breakpoint()          # pauses here: try "p p", "p running", "n", "c"\n        running += p\n    return running', run=False, play=False),
        Q("I", "Why use `logging` instead of `print`?",
          "`logging` has levels (DEBUG, INFO, WARNING, ERROR, CRITICAL), timestamps, module names, configurable handlers (console, file, cloud) and can be turned up or down without changing code.",
          "Use `logger = logging.getLogger(__name__)` in each module and configure logging once at the entry point.",
          'import logging, sys\nlogging.basicConfig(level=logging.INFO, stream=sys.stdout, format="%(levelname)s %(name)s: %(message)s")\nlog = logging.getLogger("etl")\nlog.debug("hidden at INFO level")\nlog.info("loaded %d rows", 1200)\nlog.warning("3 rows had null ids")'),
        Q("I", "What is mocking?",
          "Replacing a real dependency (an API, a database, the clock) with a fake object during a test, using `unittest.mock.Mock`, `MagicMock` or `patch`. You can set return values or side effects and later assert how it was called.",
          "Tests stay fast and deterministic, and they don't hit real services.",
          'from unittest.mock import Mock\napi = Mock()\napi.get_user.return_value = {"id": 7, "name": "Ada"}\n\ndef greeting(client, uid):\n    return f"Hi {client.get_user(uid)[\'name\']}"\n\nprint(greeting(api, 7))\napi.get_user.assert_called_once_with(7)\nprint("calls:", api.get_user.call_count)'),
        Q("A", "How do you read a Python traceback?",
          "Read from the bottom up. The last line is the exception type and message; the lines above show the call stack from outermost to innermost, with file, line number and code. Find the deepest frame in *your* code.",
          "`raise ... from` chains show \"The above exception was the direct cause of…\". Read both parts.",
          'import traceback\n\ndef level_two():\n    return {}["missing"]\n\ndef level_one():\n    return level_two()\n\ntry:\n    level_one()\nexcept KeyError:\n    lines = traceback.format_exc().strip().splitlines()\n    print(lines[0])\n    print(lines[-1])'),
        Q("I", "Which tools keep Python code quality high?",
          "`ruff` (a very fast linter and formatter), `black` (formatter), `mypy`/`pyright` (type checkers), `pytest` with `pytest-cov` (tests and coverage), and `pre-commit` to run them all automatically before each commit.",
          "Automate style so code reviews can focus on logic.",
          'pip install ruff mypy pytest pytest-cov pre-commit\nruff check . --fix && ruff format .\nmypy src/\npytest --cov=src', lang="bash"),
        Q("I", "What are doctests?",
          "Examples written in a docstring as REPL sessions (`>>> expr` followed by the expected output). `doctest` runs them and checks the output, so your documentation stays correct.",
          "Great for small pure functions; use pytest for anything bigger.",
          'import doctest\n\ndef add(a, b):\n    """\n    >>> add(2, 3)\n    5\n    >>> add("py", "thon")\n    \'python\'\n    """\n    return a + b\n\nprint(doctest.run_docstring_examples(add, {"add": add}) is None)\nprint(doctest.testmod(verbose=False).failed)'),
    ]),

    S("Python for Data", "📊", "Module 17", [
        Q("B", "What is NumPy, and why is it faster than Python lists?",
          "NumPy provides `ndarray`, a typed, contiguous array with operations implemented in C. Vectorised operations (`arr * 2`) run over the whole array without Python-level loops, often 10 to 100 times faster.",
          "pandas, scikit-learn and most of the data stack are built on NumPy arrays.",
          'import numpy as np\narr = np.arange(1, 6)\nprint(arr * 2, arr.mean(), arr[arr > 2])\nm = np.array([[1, 2], [3, 4]])\nprint(m.T, m @ m, sep="\\n")'),
        Q("B", "What are a pandas DataFrame and Series?",
          "A `Series` is a labelled one-dimensional array. A `DataFrame` is a table of columns (each a Series) sharing a row index, like a spreadsheet or SQL table in memory.",
          "`df.head()`, `df.info()`, `df.describe()` and `df.shape` are your first commands on any new dataset.",
          'import pandas as pd\ndf = pd.DataFrame({"region": ["EU", "US", "EU"], "sales": [120, 340, 90]})\nprint(df)\nprint(df.shape, df["sales"].sum())'),
        Q("I", "How do you filter rows in pandas?",
          "With a boolean mask: `df[df[\"sales\"] > 100]`. Combine conditions with `&` and `|`, and put each condition in parentheses. `df.query(\"sales > 100 and region == 'EU'\")` is a readable alternative; `.isin([...])` checks membership.",
          "Use `&`/`|` rather than `and`/`or` on Series; the keywords raise \"truth value is ambiguous\".",
          'import pandas as pd\ndf = pd.DataFrame({"region": ["EU", "US", "EU", "APAC"], "sales": [120, 340, 90, 200]})\nprint(df[(df["sales"] > 100) & (df["region"] != "US")])\nprint(df.query("sales < 150"))'),
        Q("I", "How does `groupby` work?",
          "Split-apply-combine: `df.groupby(\"region\")[\"sales\"].sum()` splits rows by region, sums each group and combines the results. `.agg()` computes several aggregations at once, such as named aggregations.",
          "It's pandas' equivalent of SQL `GROUP BY`.",
          'import pandas as pd\ndf = pd.DataFrame({"region": ["EU", "US", "EU", "US"], "sales": [120, 340, 90, 60]})\nprint(df.groupby("region")["sales"].sum())\nprint(df.groupby("region").agg(total=("sales", "sum"), orders=("sales", "count")))'),
        Q("I", "What is the difference between `loc` and `iloc`?",
          "`loc` selects by label (index labels and column names), and label slices *include* the end. `iloc` selects by integer position, like Python slicing, where the end is excluded.",
          "`df.loc[df[\"sales\"] > 100, \"region\"]` combines a row mask with a column selection.",
          'import pandas as pd\ndf = pd.DataFrame({"sales": [10, 20, 30]}, index=["a", "b", "c"])\nprint(df.loc["a":"b", "sales"].tolist(), df.iloc[0:2, 0].tolist())'),
        Q("I", "How do you handle missing values in pandas?",
          "Detect them with `isna()`/`notna()`, drop them with `dropna()`, fill them with `fillna(value)` or `ffill()`/`bfill()`, and count them with `df.isna().sum()`. Missing values appear as `NaN`, `None` or `NaT`.",
          "Decide deliberately: dropping can bias results, and filling with 0 can be wrong for averages.",
          'import pandas as pd\nimport numpy as np\ns = pd.Series([1.0, np.nan, 3.0, None])\nprint(s.isna().sum(), s.fillna(0).tolist(), s.mean())'),
        Q("I", "How do you join DataFrames?",
          "`pd.merge(left, right, on=\"key\", how=\"inner\")`, where `how` can be `left`, `right`, `outer` or `cross`, works like SQL joins. `df.join()` joins on the index; `pd.concat([a, b])` stacks frames.",
          "`validate=\"one_to_one\"` or `\"many_to_one\"` catches unexpected duplicate keys that would multiply rows.",
          'import pandas as pd\norders = pd.DataFrame({"cust": [1, 2, 1], "amount": [50, 20, 30]})\ncustomers = pd.DataFrame({"cust": [1, 2], "name": ["Ada", "Bob"]})\nmerged = orders.merge(customers, on="cust", how="left", validate="many_to_one")\nprint(merged)'),
        Q("A", "Why avoid `iterrows()`, and what should you use instead?",
          "`iterrows()` builds a Series for every row, which makes it very slow. Prefer vectorised column operations (`df[\"a\"] * df[\"b\"]`), `np.where`/`np.select` for conditions, `.map()` for lookups, and `itertuples()` if you really must loop.",
          "Vectorised code is often 100 times faster on large frames.",
          'import pandas as pd\nimport numpy as np\ndf = pd.DataFrame({"qty": [1, 5, 12], "price": [9.5, 3.0, 1.25]})\ndf["total"] = df["qty"] * df["price"]\ndf["size"] = np.where(df["qty"] >= 10, "bulk", "single")\nprint(df)'),
        Q("A", "What does `SettingWithCopyWarning` mean?",
          "You may be modifying a temporary copy produced by chained indexing (`df[df.x > 0][\"y\"] = 1`), so the original DataFrame might not change. Use a single `.loc[row_mask, \"col\"] = value`, or take an explicit `.copy()` when you want an independent subset.",
          "pandas' Copy-on-Write mode (the default in pandas 3.0) makes this behaviour consistent.",
          'import pandas as pd\ndf = pd.DataFrame({"x": [-1, 2, 3], "y": [0, 0, 0]})\ndf.loc[df["x"] > 0, "y"] = 1          # correct: one .loc call\nsubset = df[df["x"] > 0].copy()        # explicit independent copy\nsubset["y"] = 99\nprint(df["y"].tolist(), subset["y"].tolist())'),
        Q("I", "How do you read a large CSV in pandas efficiently?",
          "Load only the columns you need (`usecols=`), set types up front (`dtype=`, category types for repeated strings), parse dates explicitly (`parse_dates=`), and use `chunksize=` to process the file in pieces. Consider Parquet for repeated reads.",
          "Choosing narrow types (int32, category) can cut memory use by 5 to 10 times.",
          'import pandas as pd, io\ncsv_text = "id,region,amount\\n" + "\\n".join(f"{i},{\'EU\' if i % 2 else \'US\'},{i * 1.5}" for i in range(1, 10_001))\ntotal = 0\nfor chunk in pd.read_csv(io.StringIO(csv_text), usecols=["region", "amount"], dtype={"region": "category"}, chunksize=2_500):\n    total += chunk.loc[chunk["region"] == "EU", "amount"].sum()\nprint(total)'),
    ]),

    S("Python + Snowflake", "❄️", "Module 18", [
        Q("I", "How do you connect Python to Snowflake?",
          "Install `snowflake-connector-python`, then call `snowflake.connector.connect(account=..., user=..., authenticator=..., warehouse=..., database=..., schema=...)`, open a cursor and `execute()` SQL.",
          "Read credentials from environment variables or a secrets manager, and use `with` blocks so connections always close.",
          'import os\nimport snowflake.connector\n\nwith snowflake.connector.connect(\n    account=os.environ["SNOWFLAKE_ACCOUNT"],\n    user=os.environ["SNOWFLAKE_USER"],\n    authenticator="externalbrowser",      # SSO; or key-pair auth\n    warehouse="ANALYTICS_WH", database="SALES", schema="PUBLIC",\n) as con:\n    with con.cursor() as cur:\n        cur.execute("select current_version()")\n        print(cur.fetchone()[0])', run=False, play=False),
        Q("I", "How do you pass parameters safely (and avoid SQL injection)?",
          "Never build SQL with f-strings from user input. Use bind parameters: `cur.execute(\"select * from orders where id = %s\", (order_id,))`, or the `qmark` style `?` when enabled.",
          "Binding also lets the database reuse query plans. Only identifiers (table names) must be validated separately.",
          'import sqlite3                      # same idea with any DB-API driver\ncon = sqlite3.connect(":memory:")\ncon.execute("create table users(name text)")\ncon.execute("insert into users values (?)", ("Ada",))\nuser_input = "Ada\' OR \'1\'=\'1"\nrows = con.execute("select * from users where name = ?", (user_input,)).fetchall()\nprint(rows)   # [] : the injection attempt is treated as plain text'),
        Q("I", "How do you move data between pandas and Snowflake?",
          "Reading: `cur.fetch_pandas_all()` or `fetch_pandas_batches()` (install `snowflake-connector-python[pandas]`). Writing: `snowflake.connector.pandas_tools.write_pandas(con, df, \"TABLE_NAME\", auto_create_table=True)`, which stages Parquet files and runs `COPY INTO` behind the scenes.",
          "For large data, avoid row-by-row inserts; `write_pandas` or staged files are much faster.",
          'from snowflake.connector.pandas_tools import write_pandas\n\ncur = con.cursor()\ncur.execute("select region, sum(amount) as total from orders group by region")\ndf = cur.fetch_pandas_all()\n\nsuccess, chunks, rows, _ = write_pandas(con, df, "REGION_TOTALS", auto_create_table=True)\nprint(success, rows)', run=False, play=False),
        Q("I", "What is Snowpark for Python?",
          "A library that gives you a DataFrame API (`session.table(\"orders\").filter(col(\"amount\") > 100).group_by(\"region\").agg(sum_(\"amount\"))`). It's lazily translated to SQL and runs inside Snowflake's warehouses, so the data never leaves Snowflake.",
          "It combines pandas-like code with Snowflake's scale; you only call `.collect()` or `.to_pandas()` for the final, small result.",
          'from snowflake.snowpark import Session\nfrom snowflake.snowpark.functions import col, sum as sum_\n\nsession = Session.builder.configs(connection_params).create()\nresult = (session.table("ORDERS")\n          .filter(col("AMOUNT") > 100)\n          .group_by("REGION")\n          .agg(sum_("AMOUNT").alias("TOTAL")))\nresult.show()          # runs as SQL inside Snowflake', run=False, play=False),
        Q("A", "What are Python UDFs and stored procedures in Snowflake?",
          "User-defined functions and procedures written in Python that run inside Snowflake's secure sandbox, created with `CREATE FUNCTION ... LANGUAGE PYTHON` or Snowpark's `@udf`/`@sproc`. Packages come from the Snowflake Anaconda channel.",
          "Vectorised UDFs process batches as pandas Series, which is much faster than row-by-row UDFs.",
          'create or replace function clean_email(e string)\nreturns string\nlanguage python\nruntime_version = \'3.11\'\nhandler = \'clean\'\nas $$\ndef clean(e):\n    return e.strip().lower() if e else None\n$$;\n\nselect clean_email(\'  Ada@Example.COM \');', lang="text"),
        Q("I", "How should Python scripts handle Snowflake credentials?",
          "Never hardcode them. Use environment variables, a `connections.toml` file with restricted permissions, a secrets manager (AWS Secrets Manager, Vault) or key-pair / SSO authentication. Keep `.env` files out of git with `.gitignore`.",
          "Leaked credentials in git history are a common and serious incident; rotate them immediately if it happens.",
          'import os\n\ndef snowflake_config():\n    missing = [k for k in ("SNOWFLAKE_ACCOUNT", "SNOWFLAKE_USER") if k not in os.environ]\n    if missing:\n        return f"set env vars first: {missing}"\n    return {k: os.environ[k] for k in ("SNOWFLAKE_ACCOUNT", "SNOWFLAKE_USER")}\n\nprint(snowflake_config())'),
        Q("I", "How do you load a local file into Snowflake from Python?",
          "Run `PUT file://path @stage` to upload (and compress) the file to a stage, then `COPY INTO table FROM @stage FILE_FORMAT=(...)` to load it. Both are just SQL statements executed through the cursor.",
          "This is exactly how Project Milano's Python loader moves its CSV into Snowflake.",
          'cur.execute("create stage if not exists raw_stage")\ncur.execute("put file://./company_expenses_db.csv @raw_stage auto_compress=true")\ncur.execute("""\n    copy into expenses\n    from @raw_stage/company_expenses_db.csv.gz\n    file_format = (type = csv skip_header = 1 field_optionally_enclosed_by = \'\\"\')\n    on_error = abort_statement\n""")\nprint(cur.fetchall())', run=False, play=False),
        Q("A", "Why use Snowpark instead of pulling data into pandas?",
          "Pulling millions of rows into pandas moves data over the network and is limited by one machine's memory. Snowpark pushes the computation down to Snowflake's elastic warehouses and returns only the result.",
          "Pull data out only when the result is small or you need a Python-only library, and even then filter and aggregate in Snowflake first.",
          'aggregate in Snowflake, fetch only the answer:\n\n  session.table("EVENTS").group_by("DAY").count().to_pandas()   # ~365 rows\n\ninstead of:\n\n  pd.read_sql("select * from EVENTS", con).groupby("DAY").size() # 500M rows over the wire', lang="text"),
    ]),

    S("Interview & Coding Challenges", "🎯", "Whole course", [
        Q("A", "How do you check whether a string is a palindrome, ignoring case and punctuation?",
          "Normalise it by keeping only alphanumeric characters and lowercasing them, then compare the result with its reverse: `cleaned == cleaned[::-1]`.",
          "This is O(n) time. Interviewers may ask for a two-pointer version that uses O(1) extra memory.",
          'def is_palindrome(text):\n    cleaned = [c.lower() for c in text if c.isalnum()]\n    return cleaned == cleaned[::-1]\n\nprint(is_palindrome("A man, a plan, a canal: Panama"), is_palindrome("python"))'),
        Q("A", "How do you solve Two Sum in O(n)?",
          "Keep a dict of `value → index` for the numbers seen so far. For each number, check whether `target - number` is already in the dict. That's a single pass with O(1) lookups.",
          "The brute-force version with nested loops is O(n²); the dict trades memory for speed.",
          'def two_sum(nums, target):\n    seen = {}\n    for i, n in enumerate(nums):\n        if target - n in seen:\n            return seen[target - n], i\n        seen[n] = i\n    return None\n\nprint(two_sum([2, 7, 11, 15], 9), two_sum([3, 2, 4], 6))'),
        Q("I", "How do you write FizzBuzz?",
          "Loop from 1 to n. Print \"FizzBuzz\" for multiples of 15, \"Fizz\" for multiples of 3, \"Buzz\" for multiples of 5, and the number otherwise. Check 15 first, or build the string up piece by piece.",
          "The string-building version extends easily to new rules (e.g. 7 → \"Bazz\").",
          'def fizzbuzz(n):\n    for i in range(1, n + 1):\n        word = ("Fizz" if i % 3 == 0 else "") + ("Buzz" if i % 5 == 0 else "")\n        print(word or i, end=" ")\n\nfizzbuzz(15)'),
        Q("I", "How do you find the most common words in a text?",
          "Lowercase the text, extract words with a regex, count them with `collections.Counter` and call `most_common(k)`.",
          "Mention stop-word removal and streaming (reading line by line) for big files.",
          'import re\nfrom collections import Counter\ntext = "The quick fox. The lazy dog! The fox jumps; the DOG sleeps."\nwords = re.findall(r"[a-z\']+", text.lower())\nprint(Counter(words).most_common(3))'),
        Q("A", "How do you group anagrams?",
          "Use a `defaultdict(list)` keyed by each word's sorted letters (`\"\".join(sorted(word))`), so all anagrams share the same key.",
          "Sorting each word costs O(k log k); a 26-letter count tuple as the key gives O(k).",
          'from collections import defaultdict\n\ndef group_anagrams(words):\n    groups = defaultdict(list)\n    for w in words:\n        groups["".join(sorted(w))].append(w)\n    return list(groups.values())\n\nprint(group_anagrams(["eat", "tea", "tan", "ate", "nat", "bat"]))'),
        Q("A", "How do you implement an LRU cache?",
          "Use `collections.OrderedDict`: on `get`, move the key to the end; on `put`, insert it or move it to the end, and if the capacity is exceeded, `popitem(last=False)` evicts the least recently used item. Both operations are O(1).",
          "In real code, `functools.lru_cache` already does this for function results.",
          'from collections import OrderedDict\n\nclass LRUCache:\n    def __init__(self, capacity):\n        self.capacity, self.data = capacity, OrderedDict()\n    def get(self, key):\n        if key not in self.data:\n            return -1\n        self.data.move_to_end(key)\n        return self.data[key]\n    def put(self, key, value):\n        self.data[key] = value\n        self.data.move_to_end(key)\n        if len(self.data) > self.capacity:\n            self.data.popitem(last=False)\n\nc = LRUCache(2)\nc.put("a", 1); c.put("b", 2); c.get("a"); c.put("c", 3)\nprint(list(c.data), c.get("b"))'),
        Q("A", "How do you merge two sorted lists?",
          "Use two pointers: repeatedly take the smaller head element, then append whatever remains of either list. That's O(n + m). `heapq.merge` does the same lazily for any number of sorted iterables.",
          "`sorted(a + b)` works but is O((n+m) log(n+m)) and ignores the fact that the inputs are already sorted.",
          'import heapq\n\ndef merge(a, b):\n    i = j = 0\n    out = []\n    while i < len(a) and j < len(b):\n        if a[i] <= b[j]:\n            out.append(a[i]); i += 1\n        else:\n            out.append(b[j]); j += 1\n    return out + a[i:] + b[j:]\n\nprint(merge([1, 4, 9], [2, 3, 10, 11]))\nprint(list(heapq.merge([1, 4], [2, 3], [0])))'),
        Q("A", "How do you flatten an arbitrarily nested list?",
          "Recurse: for each item, if it's a list (or any non-string iterable), flatten it recursively; otherwise yield the item. A generator with `yield from` keeps it elegant and lazy.",
          "For very deep nesting, use an explicit stack to avoid `RecursionError`.",
          'def flatten(items):\n    stack = [iter(items)]\n    while stack:\n        for item in stack[-1]:\n            if isinstance(item, list):\n                stack.append(iter(item))\n                break\n            yield item\n        else:\n            stack.pop()\n\nprint(list(flatten([1, [2, [3, [4, [5]]]], 6])))'),
        Q("A", "Scenario: a script processing a 20 GB CSV runs out of memory. What do you do?",
          "Stream instead of loading everything: read line by line or with `pandas.read_csv(chunksize=...)`, keep only the needed columns and narrow dtypes, and aggregate incrementally. Better still, push the work to a database: stage the file and let Snowflake `COPY INTO` and aggregate it.",
          "Also profile memory (`tracemalloc`), consider Parquet and columnar tools (polars, DuckDB), and parallelise by splitting the file.",
          'import csv, io\nfake_file = io.StringIO("region,amount\\n" + "EU,10\\nUS,5\\n" * 50_000)\ntotals = {}\nfor row in csv.DictReader(fake_file):           # one row in memory at a time\n    totals[row["region"]] = totals.get(row["region"], 0) + int(row["amount"])\nprint(totals)'),
        Q("A", "Scenario: a long-running Python service keeps using more memory. How do you investigate?",
          "Measure first with `tracemalloc` snapshots (compare the top allocations over time), `objgraph` and `gc.get_objects()`. Common culprits are unbounded caches or lists, growing global dicts, reference cycles holding big objects, and listeners that are never removed.",
          "Fix it with bounded caches (`lru_cache(maxsize=...)`, `deque(maxlen=...)`), weak references (`weakref`) and clearing state per request.",
          'import tracemalloc\ntracemalloc.start()\ncache = [bytes(1000) for _ in range(1000)]     # a suspicious "cache"\nsnapshot = tracemalloc.take_snapshot()\ntop = snapshot.statistics("lineno")[0]\nprint("biggest allocation (KB) >= 900:", top.size // 1024 >= 900)'),
        Q("I", "How do you reverse the words in a sentence?",
          "`\" \".join(sentence.split()[::-1])`: split into words, reverse the list and join it back. `split()` with no arguments also collapses extra spaces.",
          "A follow-up is often \"reverse each word but keep the order\": `\" \".join(w[::-1] for w in s.split())`.",
          's = "  learn   python  daily "\nprint(" ".join(s.split()[::-1]))\nprint(" ".join(w[::-1] for w in s.split()))'),
        Q("A", "How do you find the first non-repeating character?",
          "Count the characters with `Counter` (one pass), then return the first character whose count is 1 (a second pass). That's O(n) time.",
          "Dicts and Counters preserve insertion order, which makes the second pass simple.",
          'from collections import Counter\n\ndef first_unique(s):\n    counts = Counter(s)\n    return next((c for c in s if counts[c] == 1), None)\n\nprint(first_unique("swiss"), first_unique("aabb"))'),
    ]),
]
