"""Sections 7-12: functions, comprehensions & generators, standard library, OOP, exceptions, files."""
from schema import Q, S

SECTIONS = [
    S("Functions", "🧩", "Module 7", [
        Q("B", "How do you define and call a function?",
          "Use `def name(params):` followed by an indented body; `return` sends a value back. A function without `return` returns `None`. Call it with `name(args)`.",
          "Functions let you name a piece of logic, reuse it and test it on its own.",
          'def greet(name):\n    return f"Hello, {name}!"\n\nprint(greet("Ada"))'),
        Q("B", "What is the difference between positional and keyword arguments?",
          "Positional arguments are matched by order; keyword arguments are matched by name (`f(b=2, a=1)`) and can come in any order. Positional arguments must come before keyword arguments in a call.",
          "Keyword arguments make calls self-documenting: `connect(timeout=30)` is clearer than `connect(30)`.",
          'def power(base, exp=2):\n    return base ** exp\n\nprint(power(3), power(2, 10), power(exp=3, base=2))'),
        Q("I", "What are `*args` and `**kwargs`?",
          "`*args` collects extra positional arguments into a tuple; `**kwargs` collects extra keyword arguments into a dict. The names are conventions; the `*` and `**` are what matter.",
          "They're used to write flexible functions and wrappers (decorators) that pass arguments through.",
          'def report(*args, **kwargs):\n    print("args:", args)\n    print("kwargs:", kwargs)\n\nreport(1, 2, user="ada", debug=True)'),
        Q("A", "What is the mutable default argument pitfall?",
          "Default values are evaluated once, when the function is defined, not on each call. A mutable default like `[]` or `{}` is shared between calls and keeps growing. Use `None` and create the object inside the function.",
          "This is one of the most common Python interview questions.",
          'def add(item, bucket=[]):\n    bucket.append(item)\n    return bucket\n\nprint(add(1), add(2))\n\ndef add_fixed(item, bucket=None):\n    if bucket is None:\n        bucket = []\n    bucket.append(item)\n    return bucket\n\nprint(add_fixed(1), add_fixed(2))'),
        Q("I", "What is the LEGB rule?",
          "The order Python searches for a name: Local (the current function), Enclosing (outer functions), Global (the module), Built-in (`len`, `print`, …).",
          "Assigning to a name inside a function makes it local unless you declare `global` or `nonlocal`.",
          'x = "global"\n\ndef outer():\n    x = "enclosing"\n    def inner():\n        return x          # found in the enclosing scope\n    return inner()\n\nprint(outer(), x, len("abc"))'),
        Q("I", "What do `global` and `nonlocal` do?",
          "`global name` makes an assignment inside a function update the module-level variable. `nonlocal name` updates a variable in the nearest enclosing function scope, which is useful in closures.",
          "Prefer returning values over mutating globals; `nonlocal` is fine for small closure-based counters.",
          'count = 0\n\ndef bump():\n    global count\n    count += 1\n\ndef make_counter():\n    n = 0\n    def inc():\n        nonlocal n\n        n += 1\n        return n\n    return inc\n\nbump(); bump()\nc = make_counter()\nc(); c()\nprint(count, c())'),
        Q("I", "What is a lambda?",
          "A small anonymous function written as an expression: `lambda args: expression`. It's limited to a single expression and has no statements.",
          "Lambdas are used mostly as short `key=` functions. If you need a name, use `def`.",
          'people = [("Ada", 36), ("Guido", 69), ("Linus", 55)]\nprint(sorted(people, key=lambda p: p[1]))\nsquare = lambda n: n * n\nprint(square(7))'),
        Q("I", "What does it mean that functions are first-class objects?",
          "Functions are values: you can assign them to variables, store them in lists or dicts, pass them as arguments and return them from other functions.",
          "This is the basis of callbacks, decorators and dispatch tables.",
          'def shout(text):\n    return text.upper() + "!"\n\ndef whisper(text):\n    return text.lower() + "..."\n\nstyles = {"loud": shout, "quiet": whisper}\nfor name, fn in styles.items():\n    print(name, fn("Hello"))'),
        Q("I", "What are type hints?",
          "Optional annotations like `def area(w: float, h: float) -> float:`. Python doesn't enforce them at runtime; tools like `mypy`, `pyright` and IDEs use them to catch bugs and improve autocomplete.",
          "Modern syntax: `list[int]`, `dict[str, float]`, `int | None` (3.10+).",
          'def mean(values: list[float]) -> float | None:\n    return sum(values) / len(values) if values else None\n\nprint(mean([1, 2, 3]), mean([]))\nprint(mean.__annotations__)'),
        Q("A", "What do `/` and `*` mean in a parameter list?",
          "Parameters before `/` are positional-only; parameters after `*` are keyword-only. For `def f(a, /, b, *, c)`, `a` must be positional, `b` can be either, and `c` must be passed by keyword.",
          "Keyword-only parameters prevent confusing calls like `connect(\"db\", True, False)`.",
          'def f(a, /, b, *, c):\n    return a + b + c\n\nprint(f(1, 2, c=3), f(1, b=2, c=3))\ntry:\n    f(a=1, b=2, c=3)\nexcept TypeError as err:\n    print("TypeError:", err)'),
        Q("B", "How can a function return multiple values?",
          "Return several values separated by commas; Python packs them into a tuple, which the caller can unpack: `lo, hi = min_max(data)`.",
          "For more than 2-3 values, return a named tuple or a dataclass so the fields have names.",
          'def min_max(values):\n    return min(values), max(values)\n\nlo, hi = min_max([4, 1, 9])\nprint(lo, hi, min_max([2, 3]))'),
        Q("I", "What is recursion, and what is Python's recursion limit?",
          "Recursion is a function calling itself on a smaller problem until it reaches a base case. CPython limits the call depth (1000 frames by default; see `sys.getrecursionlimit()`) and raises `RecursionError` beyond it.",
          "Python doesn't optimise tail calls, so deep recursion should be rewritten as a loop.",
          'import sys\n\ndef factorial(n):\n    return 1 if n <= 1 else n * factorial(n - 1)\n\nprint(factorial(10), sys.getrecursionlimit())'),
        Q("A", "Is Python pass-by-value or pass-by-reference?",
          "Neither exactly: it's \"pass by object reference\" (call by sharing). The function receives a reference to the same object. Mutating it (`lst.append`) is visible to the caller; rebinding the parameter (`lst = …`, `n += 1` on an int) isn't.",
          "Whether a change is visible depends on mutation vs rebinding, not on the type of \"passing\".",
          'def change(items, n):\n    items.append(4)   # mutates the shared list\n    n += 1            # rebinds a local name only\n    items = [0]       # rebinding again: caller unaffected\n\nnums, count = [1, 2, 3], 10\nchange(nums, count)\nprint(nums, count)'),
    ]),

    S("Comprehensions & Generators", "🔁", "Module 8", [
        Q("B", "What is a list comprehension?",
          "A concise way to build a list: `[expression for item in iterable if condition]`. It is usually clearer and faster than an explicit loop with `append`.",
          "Read it left to right as \"give me this, for each item, if that\".",
          'squares = [n * n for n in range(6)]\nevens = [n for n in range(10) if n % 2 == 0]\nprint(squares)\nprint(evens)'),
        Q("I", "What is the difference between a filter `if` and a conditional expression in a comprehension?",
          "A trailing `if` filters items out: `[x for x in xs if x > 0]`. A conditional expression *before* the `for` transforms every item: `[x if x > 0 else 0 for x in xs]`.",
          "If you need an `else`, it goes before the `for`.",
          'nums = [-2, -1, 0, 1, 2]\nprint([n for n in nums if n > 0])\nprint([n if n > 0 else 0 for n in nums])'),
        Q("I", "How do nested comprehensions work?",
          "Multiple `for` clauses run in the same order as nested loops: `[x for row in matrix for x in row]` flattens a matrix. A comprehension inside a comprehension builds nested lists (like transposing).",
          "If it needs more than two levels, a normal loop is usually more readable.",
          'matrix = [[1, 2, 3], [4, 5, 6]]\nprint([x for row in matrix for x in row])\nprint([[row[i] for row in matrix] for i in range(3)])'),
        Q("I", "What are set and dict comprehensions?",
          "Set: `{expr for x in xs}` produces unique values. Dict: `{key: value for x in xs}`. Same syntax as list comprehensions but with braces.",
          "Use them to build lookup tables and to find unique values.",
          'words = ["apple", "avocado", "banana", "blueberry"]\nprint(sorted({w[0] for w in words}))\nprint({w: len(w) for w in words if len(w) > 5})'),
        Q("I", "What is a generator expression, and when should you use one?",
          "Like a list comprehension but with parentheses: `(x * x for x in xs)`. It produces items lazily, one at a time, instead of building the whole list in memory.",
          "Use one when you consume the values once, e.g. `sum(x * x for x in huge)`. It uses constant memory no matter how many items there are.",
          'import sys\nprint(sum(n * n for n in range(1_000_000)))\nlist_size = sys.getsizeof([n for n in range(10_000)])\ngen_size = sys.getsizeof((n for n in range(10_000)))\nprint(list_size > 50_000, gen_size < 500)'),
        Q("I", "What is the difference between an iterable and an iterator?",
          "An iterable can give you an iterator via `iter()` (lists, strings, dicts, files). An iterator produces values with `next()` and raises `StopIteration` when it's exhausted. Every iterator is iterable, but not every iterable is an iterator.",
          "A `for` loop calls `iter()` once, then `next()` repeatedly until `StopIteration`.",
          'it = iter([1, 2])\nprint(next(it), next(it))\ntry:\n    next(it)\nexcept StopIteration:\n    print("exhausted")'),
        Q("I", "What is a generator function?",
          "A function that uses `yield`. Calling it returns a generator object without running the body; each `next()` runs until the next `yield`, pauses there and keeps its local state.",
          "Generators are the simplest way to write your own lazy iterators and data pipelines.",
          'def countdown(n):\n    while n > 0:\n        yield n\n        n -= 1\n\nprint(list(countdown(5)))\ng = countdown(2)\nprint(next(g), next(g))'),
        Q("A", "What does `yield from` do?",
          "It delegates to another iterable or generator, yielding each of its values (and, for generators, passing through `send()` and `throw()` and returning its return value).",
          "It's a clean way to flatten recursive structures.",
          'def flatten(items):\n    for item in items:\n        if isinstance(item, list):\n            yield from flatten(item)\n        else:\n            yield item\n\nprint(list(flatten([1, [2, [3, [4]]], 5])))'),
        Q("A", "Why can a generator only be consumed once?",
          "A generator is an iterator: it keeps its position and doesn't restart. After it's exhausted, iterating it again produces nothing. To iterate twice, recreate it or store the results in a list.",
          "A common bug is passing a generator to two functions and wondering why the second one sees nothing.",
          'g = (x * 2 for x in range(3))\nprint(list(g))\nprint(list(g))'),
        Q("I", "Which `itertools` functions are worth knowing?",
          "`count`, `cycle`, `repeat` (infinite iterators); `chain`, `islice`, `takewhile`, `dropwhile`; `groupby`; `accumulate`; combinatorics: `product`, `permutations`, `combinations`; `batched` (3.12+).",
          "They're lazy, fast (implemented in C) and compose well with generators.",
          'from itertools import islice, count, combinations, chain, accumulate\nprint(list(islice(count(10, 5), 4)))\nprint(list(combinations("ABC", 2)))\nprint(list(chain([1, 2], (3,))), list(accumulate([1, 2, 3, 4])))'),
        Q("I", "How does `zip()` work, and how do you \"unzip\"?",
          "`zip(a, b, …)` pairs up items from several iterables and stops at the shortest one (`strict=True` raises an error on a length mismatch, 3.10+). `zip(*pairs)` unzips pairs back into separate tuples.",
          "`dict(zip(keys, values))` is the quickest way to build a dict from two lists.",
          'names = ["ada", "guido"]\nscores = [95, 88]\nprint(dict(zip(names, scores)))\npairs = [(1, "x"), (2, "y")]\nnums, letters = zip(*pairs)\nprint(nums, letters)'),
        Q("A", "How can you work with infinite sequences in Python?",
          "Use a generator that never stops, and take only what you need with `itertools.islice` or `takewhile`. Nothing is computed until it's requested.",
          "Lazy pipelines let you process endless streams (logs, sensor data) in constant memory.",
          'from itertools import islice\n\ndef fibonacci():\n    a, b = 0, 1\n    while True:\n        yield a\n        a, b = b, a + b\n\nprint(list(islice(fibonacci(), 12)))'),
    ]),

    S("Built-ins & Standard Library", "🧰", "Module 9", [
        Q("B", "What do `any()` and `all()` do?",
          "`any(iterable)` is `True` if at least one item is truthy; `all(iterable)` is `True` if every item is truthy. Both short-circuit. For an empty iterable, `any` returns `False` and `all` returns `True`.",
          "Combine them with generator expressions: `all(x > 0 for x in xs)`.",
          'scores = [72, 95, 88]\nprint(any(s > 90 for s in scores), all(s > 70 for s in scores))\nprint(any([]), all([]))'),
        Q("I", "How do you sort by multiple criteria?",
          "Return a tuple from the `key` function: `sorted(people, key=lambda p: (-p.age, p.name))` sorts by age descending, then name ascending. Negate numbers to reverse just one criterion.",
          "Because sorting is stable, you can also sort in multiple passes, least important key first.",
          'people = [("Ann", 30), ("Bob", 25), ("Cy", 30)]\nprint(sorted(people, key=lambda p: (-p[1], p[0])))\nfrom operator import itemgetter\nprint(sorted(people, key=itemgetter(1)))'),
        Q("I", "`map()`/`filter()` or comprehensions: which should you use?",
          "`map(fn, xs)` applies a function and `filter(fn, xs)` keeps items where the function is truthy; both return lazy iterators. Comprehensions are usually more readable, especially when you'd otherwise need a lambda.",
          "`map(str, nums)` is fine and fast; `[x * 2 for x in xs]` beats `map(lambda x: x * 2, xs)`.",
          'nums = [1, 2, 3, 4]\nprint(list(map(str, nums)), list(filter(lambda n: n % 2, nums)))\nprint([n * 2 for n in nums if n > 2])'),
        Q("I", "What are `functools.lru_cache`, `partial` and `reduce`?",
          "`lru_cache` memoizes function results by their arguments. `partial` pre-fills some arguments of a function. `reduce` folds an iterable into a single value by applying a function cumulatively.",
          "`@lru_cache` turns an exponential recursive Fibonacci into a linear one. `@functools.cache` (3.9+) is the unbounded version.",
          'from functools import lru_cache, partial, reduce\n\n@lru_cache(maxsize=None)\ndef fib(n):\n    return n if n < 2 else fib(n - 1) + fib(n - 2)\n\nprint(fib(80))\nbase2 = partial(int, base=2)\nprint(base2("1010"), reduce(lambda a, b: a * b, [1, 2, 3, 4]))'),
        Q("I", "Why does `round(2.5)` return 2?",
          "Python rounds halves to the nearest even number (\"banker's rounding\") to avoid statistical bias: `round(2.5) == 2`, `round(3.5) == 4`. Floats like 2.675 also aren't stored exactly, which can make rounding look odd.",
          "For money, use `decimal.Decimal` with an explicit rounding mode such as `ROUND_HALF_UP`.",
          'print(round(2.5), round(3.5), round(2.675, 2))\nfrom decimal import Decimal, ROUND_HALF_UP\nprint(Decimal("2.5").quantize(Decimal("1"), rounding=ROUND_HALF_UP))'),
        Q("B", "What do the `math` and `random` modules provide?",
          "`math`: `sqrt`, `ceil`, `floor`, `pi`, `log`, `isclose`, `factorial`, `gcd`, `inf`. `random`: `random()`, `randint(a, b)`, `choice`, `shuffle`, `sample`, and `seed` for reproducible results.",
          "For security tokens, use the `secrets` module, not `random`.",
          'import math, random\nprint(math.sqrt(16), math.ceil(2.1), math.floor(2.9), round(math.pi, 3))\nrandom.seed(42)\nprint(random.randint(1, 6), random.choice(["a", "b", "c"]))'),
        Q("I", "How do you work with dates and times?",
          "Use the `datetime` module: `date`, `datetime`, `timedelta` for arithmetic, `strftime` to format and `strptime`/`fromisoformat` to parse. Use timezone-aware datetimes (`zoneinfo`) for real-world timestamps.",
          "Store and compute in UTC; convert to local time only for display.",
          'from datetime import date, datetime, timedelta\nd = date(2024, 1, 31)\nprint(d + timedelta(days=1), d.strftime("%d %b %Y"), d.isoformat())\nprint(datetime.fromisoformat("2024-05-06T10:30").hour)'),
        Q("I", "What is `pathlib`?",
          "An object-oriented way to work with file paths: `Path(\"data\") / \"sales.csv\"`, with `.name`, `.stem`, `.suffix`, `.parent`, `.exists()`, `.read_text()`, `.glob(\"*.csv\")`.",
          "It's cleaner and more portable than string concatenation or `os.path.join`.",
          'from pathlib import PurePosixPath as Path\np = Path("data") / "sales" / "2024.csv"\nprint(p, p.name, p.stem, p.suffix, p.parent)\nprint(p.with_suffix(".parquet"))'),
        Q("I", "What is `collections.deque`?",
          "A double-ended queue with O(1) `append`, `appendleft`, `pop` and `popleft`. `maxlen=` makes it a fixed-size rolling buffer; `rotate(n)` shifts the items.",
          "Use it for queues, BFS and \"last N items\" windows. A list's `pop(0)` is O(n).",
          'from collections import deque\nrecent = deque(maxlen=3)\nfor page in ["home", "topics", "quiz", "playground"]:\n    recent.append(page)\nprint(list(recent))\nq = deque([1, 2, 3])\nq.rotate(1)\nprint(q)'),
        Q("I", "What is `heapq` used for?",
          "A binary min-heap on a plain list: `heappush` and `heappop` are O(log n), and `nsmallest`/`nlargest` get the top k items. It's the basis for priority queues.",
          "For a max-heap, push negated values.",
          'import heapq\ntasks = []\nheapq.heappush(tasks, (2, "write tests"))\nheapq.heappush(tasks, (1, "fix bug"))\nheapq.heappush(tasks, (3, "refactor"))\nprint(heapq.heappop(tasks))\nprint(heapq.nlargest(2, [5, 1, 8, 3, 9]))'),
        Q("I", "How do you use regular expressions in Python?",
          "Use the `re` module: `re.search` finds the first match, `re.findall` finds all matches, `re.sub` replaces, and `re.compile` builds a reusable pattern. Groups `( )` capture parts of a match. Write patterns as raw strings.",
          "Named groups `(?P<year>\\d{4})` make matches readable: `m[\"year\"]`.",
          'import re\ntext = "Order 42 shipped on 2024-05-06"\nprint(re.findall(r"\\d+", text))\nm = re.search(r"(?P<y>\\d{4})-(?P<m>\\d{2})-(?P<d>\\d{2})", text)\nprint(m["y"], m.groups())\nprint(re.sub(r"\\d", "#", "call 555-1234"))'),
        Q("B", "What does \"batteries included\" mean?",
          "Python ships with a large standard library covering most everyday needs: `os`, `sys`, `json`, `csv`, `re`, `datetime`, `pathlib`, `collections`, `itertools`, `functools`, `logging`, `unittest`, `sqlite3`, `subprocess`, `threading`, `asyncio`, `http`, `urllib`…",
          "Check the standard library before installing a package; it's well tested and always available.",
          'import sqlite3\ncon = sqlite3.connect(":memory:")\ncon.execute("create table t(x int)")\ncon.executemany("insert into t values (?)", [(1,), (2,), (3,)])\nprint(con.execute("select sum(x) from t").fetchone()[0])'),
    ]),

    S("Object-Oriented Python", "🏗️", "Module 10", [
        Q("B", "How do you define a class and create an object?",
          "`class Name:` with methods defined inside. `__init__` initialises a new instance. Create an object by calling the class: `rex = Dog(\"Rex\")`.",
          "A class is a blueprint; each object (instance) has its own attribute values.",
          'class Dog:\n    def __init__(self, name):\n        self.name = name\n\n    def speak(self):\n        return f"{self.name} says woof"\n\nrex = Dog("Rex")\nprint(rex.speak(), rex.name)'),
        Q("B", "What is `self`?",
          "The first parameter of an instance method: a reference to the object the method was called on. Python passes it automatically, so `rex.speak()` is really `Dog.speak(rex)`.",
          "`self` is just a strong convention, not a keyword, but always use it.",
          'class Counter:\n    def __init__(self):\n        self.value = 0\n    def inc(self):\n        self.value += 1\n        return self\n\nc = Counter()\nCounter.inc(c)\nprint(c.inc().value)'),
        Q("I", "What is the difference between class attributes and instance attributes?",
          "Class attributes are defined in the class body and shared by all instances. Instance attributes are set on `self` and belong to one object. Reading `obj.x` checks the instance first, then the class.",
          "A mutable class attribute (like a list) is shared by every instance, which is a common bug. Initialise it in `__init__` instead.",
          'class Player:\n    count = 0              # class attribute\n    def __init__(self, name):\n        self.name = name   # instance attribute\n        Player.count += 1\n\na, b = Player("Ada"), Player("Bob")\nprint(Player.count, a.name, b.name)'),
        Q("I", "How do inheritance and `super()` work?",
          "`class Child(Parent):` inherits the parent's attributes and methods, and it can override them. `super().method()` calls the next implementation in the method resolution order, typically the parent's.",
          "Call `super().__init__(...)` in the child's `__init__` so the parent's setup still runs.",
          'class Animal:\n    def __init__(self, name):\n        self.name = name\n    def speak(self):\n        return "..."\n\nclass Cat(Animal):\n    def __init__(self, name, indoor=True):\n        super().__init__(name)\n        self.indoor = indoor\n    def speak(self):\n        return f"{self.name}: meow"\n\nc = Cat("Tom")\nprint(c.speak(), c.indoor, isinstance(c, Animal))'),
        Q("A", "What is the MRO, and how does multiple inheritance work?",
          "The Method Resolution Order is the order Python searches classes for an attribute, computed with the C3 linearisation algorithm and shown by `Cls.__mro__`. With multiple inheritance, `super()` follows the MRO, so each class in a diamond runs exactly once.",
          "In a diamond `D(B, C)`, where B and C both inherit from A, the order is D, B, C, A, object.",
          'class A:\n    def hi(self): return "A"\nclass B(A):\n    def hi(self): return "B" + super().hi()\nclass C(A):\n    def hi(self): return "C" + super().hi()\nclass D(B, C):\n    def hi(self): return "D" + super().hi()\n\nprint(D().hi())\nprint([k.__name__ for k in D.__mro__])'),
        Q("I", "What is the difference between `__str__` and `__repr__`?",
          "`__str__` is the readable, user-facing text used by `print()` and `str()`. `__repr__` is the unambiguous developer view used by the REPL, containers and `repr()`; ideally it looks like code that recreates the object.",
          "If you define only one, define `__repr__`; `str()` falls back to it.",
          'class Money:\n    def __init__(self, amount):\n        self.amount = amount\n    def __repr__(self):\n        return f"Money({self.amount!r})"\n    def __str__(self):\n        return f"${self.amount:,.2f}"\n\nm = Money(1234.5)\nprint(m)\nprint([m], repr(m))'),
        Q("I", "What are dunder methods and operator overloading?",
          "\"Double underscore\" methods such as `__add__`, `__eq__`, `__lt__`, `__len__`, `__getitem__`, `__iter__` and `__contains__` let your objects work with operators and built-ins.",
          "This is how `len(obj)`, `a + b`, `obj[i]` and `x in obj` work for your own classes.",
          'class Vector:\n    def __init__(self, x, y):\n        self.x, self.y = x, y\n    def __add__(self, other):\n        return Vector(self.x + other.x, self.y + other.y)\n    def __eq__(self, other):\n        return (self.x, self.y) == (other.x, other.y)\n    def __abs__(self):\n        return (self.x ** 2 + self.y ** 2) ** 0.5\n    def __repr__(self):\n        return f"Vector({self.x}, {self.y})"\n\nprint(Vector(1, 2) + Vector(3, 4), abs(Vector(3, 4)), Vector(1, 1) == Vector(1, 1))'),
        Q("I", "What does `@property` do?",
          "It turns a method into an attribute you can read without calling it. Add a `@name.setter` to validate assignments. This gives you controlled access without Java-style `get_x()`/`set_x()` methods.",
          "Start with plain attributes; switch to a property later without changing the calling code.",
          'class Temperature:\n    def __init__(self, celsius):\n        self.celsius = celsius\n    @property\n    def fahrenheit(self):\n        return self.celsius * 9 / 5 + 32\n    @property\n    def celsius(self):\n        return self._c\n    @celsius.setter\n    def celsius(self, value):\n        if value < -273.15:\n            raise ValueError("below absolute zero")\n        self._c = value\n\nt = Temperature(25)\nprint(t.fahrenheit)\ntry:\n    t.celsius = -300\nexcept ValueError as err:\n    print(err)'),
        Q("I", "`@classmethod` vs `@staticmethod`: what is the difference?",
          "A classmethod receives the class (`cls`) as its first argument and is commonly used for alternative constructors like `from_string`. A staticmethod receives nothing automatically; it's a plain function grouped inside the class.",
          "Classmethod constructors also work correctly for subclasses because `cls` is the subclass.",
          'class Date:\n    def __init__(self, y, m, d):\n        self.y, self.m, self.d = y, m, d\n    @classmethod\n    def from_string(cls, text):\n        return cls(*map(int, text.split("-")))\n    @staticmethod\n    def is_leap(year):\n        return year % 4 == 0 and (year % 100 != 0 or year % 400 == 0)\n\nd = Date.from_string("2024-05-06")\nprint(d.y, d.m, d.d, Date.is_leap(2024), Date.is_leap(1900))'),
        Q("I", "What are dataclasses?",
          "The `@dataclass` decorator generates `__init__`, `__repr__` and `__eq__` from class-level type annotations. Options include `frozen=True` (immutable), `order=True` (comparisons) and `field(default_factory=list)` for mutable defaults.",
          "They remove boilerplate for classes that mainly hold data.",
          'from dataclasses import dataclass, field\n\n@dataclass(order=True)\nclass Item:\n    price: float\n    name: str\n    tags: list[str] = field(default_factory=list)\n\na, b = Item(1.5, "pen"), Item(0.5, "clip", ["office"])\nprint(a)\nprint(sorted([a, b])[0].name, a == Item(1.5, "pen"))'),
        Q("A", "What do `_single` and `__double` leading underscores mean?",
          "`_name` is a convention for \"internal, please don't use\"; nothing is enforced. `__name` inside a class triggers name mangling to `_ClassName__name`, which avoids accidental clashes in subclasses. It's not real privacy.",
          "Python's philosophy is \"we're all consenting adults\": conventions over access control.",
          'class Account:\n    def __init__(self):\n        self._internal = "hint"\n        self.__secret = 42\n\na = Account()\nprint(a._internal, a._Account__secret)\ntry:\n    a.__secret\nexcept AttributeError:\n    print("AttributeError: name was mangled")'),
        Q("A", "What are abstract base classes?",
          "Classes that inherit from `abc.ABC` and mark methods with `@abstractmethod`. They can't be instantiated, and subclasses must implement every abstract method before they can be.",
          "Use them to define a contract (e.g. every `Loader` must have `load()`). For structural typing without inheritance, see `typing.Protocol`.",
          'from abc import ABC, abstractmethod\n\nclass Loader(ABC):\n    @abstractmethod\n    def load(self): ...\n\nclass CsvLoader(Loader):\n    def load(self):\n        return "rows from csv"\n\nprint(CsvLoader().load())\ntry:\n    Loader()\nexcept TypeError as err:\n    print("TypeError:", err)'),
        Q("I", "What is duck typing?",
          "\"If it walks like a duck and quacks like a duck, it's a duck.\" Python cares about what an object can do (its methods), not its declared type. Any object with a `.read()` method can be used where a file is expected.",
          "It's why functions work with any iterable, not just lists. `typing.Protocol` lets type checkers understand duck typing.",
          'import io\n\ndef count_lines(f):\n    return sum(1 for _ in f)\n\nprint(count_lines(io.StringIO("a\\nb\\nc\\n")))\nprint(count_lines(["x", "y"]))'),
    ]),

    S("Errors & Exceptions", "🚨", "Module 11", [
        Q("B", "How do `try` and `except` work?",
          "Code that might fail goes in `try:`. If an exception is raised, Python jumps to the first matching `except` block. Unhandled exceptions stop the program with a traceback.",
          "Catch the most specific exception you can handle meaningfully.",
          'def parse_age(text):\n    try:\n        return int(text)\n    except ValueError:\n        return None\n\nprint(parse_age("42"), parse_age("forty-two"))'),
        Q("I", "What do `else` and `finally` do in a `try` statement?",
          "`else` runs only if no exception occurred, so keep the \"happy path\" there. `finally` always runs, with or without an exception, and is used for cleanup.",
          "Putting the success code in `else` avoids accidentally catching exceptions raised by it.",
          'def divide(a, b):\n    try:\n        result = a / b\n    except ZeroDivisionError:\n        print("cannot divide by zero")\n    else:\n        print("result:", result)\n    finally:\n        print("done")\n\ndivide(6, 3)\ndivide(1, 0)'),
        Q("I", "How do you catch several exception types?",
          "Use a tuple, `except (ValueError, TypeError) as err:`, or several `except` blocks in order from most to least specific. `as err` gives you the exception object.",
          "`except Exception` catches almost everything; use it only at top-level boundaries, and log the error.",
          'for raw in ["10", "ten", None]:\n    try:\n        print(int(raw) * 2)\n    except (ValueError, TypeError) as err:\n        print(type(err).__name__, "->", err)'),
        Q("B", "How do you raise an exception?",
          "`raise ValueError(\"message\")`. A bare `raise` inside an `except` block re-raises the current exception.",
          "Raise early with a clear message rather than returning odd values like -1.",
          'def withdraw(balance, amount):\n    if amount > balance:\n        raise ValueError(f"insufficient funds: {balance} < {amount}")\n    return balance - amount\n\ntry:\n    withdraw(50, 80)\nexcept ValueError as err:\n    print(err)'),
        Q("I", "How do you create a custom exception?",
          "Subclass `Exception` (or a more specific built-in): `class PipelineError(Exception): pass`. Add attributes if callers need details.",
          "A small hierarchy of custom exceptions lets callers catch your library's errors precisely.",
          'class PipelineError(Exception):\n    pass\n\nclass MissingColumn(PipelineError):\n    def __init__(self, column):\n        super().__init__(f"missing column: {column}")\n        self.column = column\n\ntry:\n    raise MissingColumn("amount")\nexcept PipelineError as err:\n    print(err, "|", err.column)'),
        Q("I", "Why is a bare `except:` a bad idea?",
          "It catches everything, including `KeyboardInterrupt` and `SystemExit`, which makes programs impossible to stop with Ctrl+C and hides real bugs like typos (`NameError`).",
          "Catch specific exceptions. If you must catch broadly, use `except Exception as err:` and log or re-raise.",
          'try:\n    undefined_function()\nexcept Exception as err:\n    print("caught:", type(err).__name__)'),
        Q("I", "What are EAFP and LBYL?",
          "EAFP (\"Easier to Ask Forgiveness than Permission\") means trying the operation and handling the exception. LBYL (\"Look Before You Leap\") means checking conditions first. Python style favours EAFP.",
          "EAFP avoids race conditions (e.g. a file deleted between the check and the open) and duplicate lookups.",
          'config = {"host": "db.local"}\n\n# LBYL\nport = config["port"] if "port" in config else 5432\n# EAFP\ntry:\n    port = config["port"]\nexcept KeyError:\n    port = 5432\nprint(port)'),
        Q("I", "What is a context manager?",
          "An object used with `with` that sets something up and guarantees cleanup via `__enter__`/`__exit__`, even if an exception is raised. Files, locks and database connections are common examples. `contextlib.contextmanager` makes one from a generator.",
          "The code before `yield` runs on entry and the code after it runs on exit.",
          'from contextlib import contextmanager\n\n@contextmanager\ndef tag(name):\n    print(f"<{name}>")\n    try:\n        yield\n    finally:\n        print(f"</{name}>")\n\nwith tag("b"):\n    print("bold text")'),
        Q("A", "What is exception chaining (`raise ... from ...`)?",
          "`raise NewError(...) from err` records the original exception as `__cause__`, and the traceback shows both. `from None` hides the original when it's just noise.",
          "Use it when translating low-level errors into domain errors without losing the root cause.",
          'class ConfigError(Exception):\n    pass\n\ndef load_port(cfg):\n    try:\n        return int(cfg["port"])\n    except (KeyError, ValueError) as err:\n        raise ConfigError("invalid port setting") from err\n\ntry:\n    load_port({"port": "abc"})\nexcept ConfigError as err:\n    print(err, "| caused by", type(err.__cause__).__name__)'),
        Q("I", "What does the exception hierarchy look like?",
          "`BaseException` is the root. Beneath it are `SystemExit`, `KeyboardInterrupt`, `GeneratorExit` and `Exception`. Under `Exception`: `ArithmeticError` (→ `ZeroDivisionError`), `LookupError` (→ `KeyError`, `IndexError`), `OSError` (→ `FileNotFoundError`), `ValueError`, `TypeError` and more.",
          "Catching a parent class catches all of its children, e.g. `except LookupError` handles both `KeyError` and `IndexError`.",
          'print(issubclass(KeyError, LookupError), issubclass(FileNotFoundError, OSError))\nprint([c.__name__ for c in ZeroDivisionError.__mro__])'),
        Q("B", "Which built-in exceptions are most common?",
          "`ValueError` (right type, bad value), `TypeError` (wrong type), `KeyError`, `IndexError`, `AttributeError`, `NameError`, `ZeroDivisionError`, `FileNotFoundError`, `ImportError`/`ModuleNotFoundError`, `StopIteration`.",
          "Recognising the exception name is the fastest way to know where to look.",
          'tests = [lambda: int("x"), lambda: len(5), lambda: {}["k"], lambda: [][0], lambda: None.upper()]\nfor t in tests:\n    try:\n        t()\n    except Exception as err:\n        print(type(err).__name__)'),
        Q("A", "Does `finally` run if the `try` block returns?",
          "Yes. `finally` runs before the function actually returns, even after `return`, `break` or an exception. Avoid putting `return` inside `finally`: it silently overrides the original return value or swallows exceptions (newer Pythons warn about it).",
          "Use `finally` only for cleanup such as closing files or releasing locks.",
          'def fetch():\n    try:\n        return "data"\n    finally:\n        print("closing connection")\n\nprint(fetch())'),
    ]),

    S("Files & Data Formats", "📁", "Module 12", [
        Q("B", "How do you write to and read from a text file?",
          "`open(path, mode, encoding=\"utf-8\")` inside a `with` block. `\"w\"` writes (truncating), `\"a\"` appends, `\"r\"` reads (the default). Iterating a file object yields lines.",
          "The `with` block closes the file automatically, even if an error occurs.",
          'with open("notes.txt", "w", encoding="utf-8") as f:\n    f.write("line 1\\nline 2\\n")\n\nwith open("notes.txt", encoding="utf-8") as f:\n    for line in f:\n        print(line.strip())'),
        Q("B", "What are the common file modes?",
          "`r` read (default), `w` write/truncate, `a` append, `x` create (fails if the file exists), `b` binary (`rb`, `wb`), `t` text (default), `+` read and write (`r+`).",
          "Use binary mode for images, Parquet and other non-text data; text mode handles encoding and newlines.",
          'with open("log.txt", "a", encoding="utf-8") as f:\n    f.write("run 1\\n")\nwith open("log.txt", "a", encoding="utf-8") as f:\n    f.write("run 2\\n")\nprint(open("log.txt", encoding="utf-8").read().splitlines())'),
        Q("I", "How do you read and write JSON?",
          "Use the `json` module: `json.dumps(obj)` / `json.loads(text)` for strings, and `json.dump(obj, f)` / `json.load(f)` for files. Options include `indent=2`, `sort_keys=True` and `default=str` for types JSON doesn't support.",
          "JSON maps to dicts, lists, str, int/float, bool and None. Tuples become lists, and dates need converting.",
          'import json\ndata = {"name": "Ada", "langs": ["python", "sql"], "active": True}\ntext = json.dumps(data, indent=2)\nprint(text)\nprint(json.loads(text)["langs"][0])'),
        Q("I", "How do you read CSV files with the standard library?",
          "`csv.reader` yields each row as a list; `csv.DictReader` yields dicts keyed by the header row. Open the file with `newline=\"\"` and remember that every value arrives as a string.",
          "For analysis, `pandas.read_csv` is usually more convenient; `csv` is great for lightweight scripts.",
          'import csv, io\nraw = "name,score\\nAda,95\\nBob,87\\n"\nfor row in csv.DictReader(io.StringIO(raw)):\n    print(row["name"], int(row["score"]) + 5)'),
        Q("I", "How do you process a huge file without running out of memory?",
          "Iterate over it line by line (`for line in f`), or read fixed-size chunks with `f.read(size)`, instead of `f.read()`/`readlines()` on the whole file. Combine this with generators to build streaming pipelines.",
          "Memory then stays constant whether the file is 1 MB or 50 GB.",
          'with open("big.txt", "w") as f:\n    f.writelines(f"row {i}\\n" for i in range(100_000))\n\ndef numbered_lines(path):\n    with open(path) as f:\n        for line in f:\n            yield line.rstrip()\n\nprint(sum(1 for line in numbered_lines("big.txt") if line.endswith("7")))'),
        Q("I", "How does `pathlib` simplify file work?",
          "`Path.write_text()`, `read_text()`, `exists()`, `mkdir(parents=True, exist_ok=True)`, `glob(\"*.csv\")`, `iterdir()`, `stat()` and `unlink()` are all methods on a path object.",
          "One-liners like `Path(\"out.txt\").write_text(\"hi\")` replace the open/write/close dance for small files.",
          'from pathlib import Path\nout = Path("reports")\nout.mkdir(exist_ok=True)\nfor month in ["jan", "feb"]:\n    (out / f"{month}.csv").write_text("id,amount\\n1,10\\n")\nprint(sorted(p.name for p in out.glob("*.csv")))\nprint((out / "jan.csv").read_text().splitlines()[1])'),
        Q("I", "Why should you always pass `encoding=\"utf-8\"`?",
          "Without it, Python uses the platform's default encoding (historically cp1252 on Windows), so the same code can work on a Mac and crash with `UnicodeDecodeError` on Windows. Passing an explicit encoding makes it portable.",
          "Python 3.15 is moving to UTF-8 by default, but explicit is still better than implicit.",
          'text = "naïve café ✓"\nwith open("u.txt", "w", encoding="utf-8") as f:\n    f.write(text)\nprint(open("u.txt", encoding="utf-8").read())\nprint(len(open("u.txt", "rb").read()), "bytes")'),
        Q("A", "What is `pickle`, and when is it dangerous?",
          "`pickle` serialises almost any Python object to bytes and back. Unpickling runs code chosen by whoever created the data, so never unpickle data from untrusted sources. It's also Python-specific and version-sensitive.",
          "For data exchange, prefer JSON, CSV or Parquet. Use pickle only for trusted, short-lived caches.",
          'import pickle\nmodel = {"weights": [0.1, 0.2], "labels": ("cat", "dog")}\nblob = pickle.dumps(model)\nprint(type(blob).__name__, pickle.loads(blob) == model)'),
        Q("I", "How do you read a file that doesn't exist without crashing?",
          "Catch `FileNotFoundError` (a subclass of `OSError`), or check `Path(p).exists()` first. EAFP with try/except is the idiomatic choice.",
          "Also catch `PermissionError` or `IsADirectoryError` if they can happen in your environment.",
          'def read_config(path):\n    try:\n        with open(path, encoding="utf-8") as f:\n            return f.read()\n    except FileNotFoundError:\n        return "{}"\n\nprint(read_config("missing.json"))'),
        Q("I", "How do you write CSV files correctly?",
          "Use `csv.writer` or `csv.DictWriter` on a file opened with `newline=\"\"`. They quote values containing commas, quotes and newlines for you.",
          "Building CSV lines with `\",\".join()` breaks as soon as a value contains a comma.",
          'import csv\nrows = [{"name": "Ada, Countess", "score": 95}, {"name": "Bob", "score": 87}]\nwith open("out.csv", "w", newline="", encoding="utf-8") as f:\n    w = csv.DictWriter(f, fieldnames=["name", "score"])\n    w.writeheader()\n    w.writerows(rows)\nprint(open("out.csv", encoding="utf-8").read())'),
    ]),
]
