// Generated by source/generate_avatars.py
window.SF_AVATARS = [
 {
  "id": "boy-1",
  "name": "Aarav",
  "group": "boy",
  "src": "avatars/boy-1.svg"
 },
 {
  "id": "boy-2",
  "name": "Kabir",
  "group": "boy",
  "src": "avatars/boy-2.svg"
 },
 {
  "id": "boy-3",
  "name": "Rohan",
  "group": "boy",
  "src": "avatars/boy-3.svg"
 },
 {
  "id": "boy-4",
  "name": "Dev",
  "group": "boy",
  "src": "avatars/boy-4.svg"
 },
 {
  "id": "boy-5",
  "name": "Arjun",
  "group": "boy",
  "src": "avatars/boy-5.svg"
 },
 {
  "id": "girl-1",
  "name": "Ananya",
  "group": "girl",
  "src": "avatars/girl-1.svg"
 },
 {
  "id": "girl-2",
  "name": "Isha",
  "group": "girl",
  "src": "avatars/girl-2.svg"
 },
 {
  "id": "girl-3",
  "name": "Priya",
  "group": "girl",
  "src": "avatars/girl-3.svg"
 },
 {
  "id": "girl-4",
  "name": "Sara",
  "group": "girl",
  "src": "avatars/girl-4.svg"
 },
 {
  "id": "girl-5",
  "name": "Zoya",
  "group": "girl",
  "src": "avatars/girl-5.svg"
 }
];
