"""50 Essential Behavioral & HR Interview Questions (90%+ frequency in Tech Interviews).
Structured using the STAR framework (Situation, Task, Action, Result) with GenZ career insights.
"""
from schema import Q, S

QUESTIONS = [
    Q("B", "Tell me about yourself and walk me through your journey.",
      "The classic opening question. Structure using the Present-Past-Future framework: 1. Present: Current role, tech stack, and primary technical focus. 2. Past: Educational background, high-impact projects, and how you fell in love with building software. 3. Future: Why this specific team and challenge aligns with your career trajectory.",
      "Keep it under 90-120 seconds. Focus on quantifiable impact and passion for problem solving rather than reciting your resume line by line.",
      category="behavioural",
      star={"S": "Currently building full-stack distributed web applications.",
            "T": "Deliver high-availability backend microservices with strong engineering hygiene.",
            "A": "Mastered Java/Spring, algorithmic optimization, and modern cloud deployment patterns.",
            "R": "Increased system performance by 40% and prepared to tackle large-scale challenges on your team."},
      tags=["Opening", "Elevator Pitch", "Must-Know"]),

    Q("B", "Tell me about a time you had a serious conflict with a team member.",
      "Focus on professional disagreement about technical decisions, never personal friction. Walk through how you prioritized data over ego, listened to their perspective, benchmarked alternatives, and found a collaborative middle ground.",
      "Interviewers want to see psychological safety, empathy, emotional intelligence, and commitment to the team's shared goal.",
      category="behavioural",
      star={"S": "Two engineers had conflicting opinions on using PostgreSQL vs MongoDB for an analytics dashboard.",
            "T": "Determine the optimal database before sprint architecture lockdown.",
            "A": "Organized a 2-day proof-of-concept spike measuring read latency, complex query aggregations, and migration cost.",
            "R": "Data showed PostgreSQL with JSONB satisfied both relational integrity and document flexibility; team aligned smoothly."},
      tags=["Conflict", "Collaboration", "EQ"]),

    Q("B", "Tell me about a project that failed or missed its goals. What did you learn?",
      "Own the failure directly without blaming teammates, management, or external vendors. Clearly identify root causes (e.g. scope ambiguity, insufficient load testing) and explain the systemic improvements you implemented to prevent recurrence.",
      "Demonstrates resilience, extreme ownership, and continuous growth mindset.",
      category="behavioural",
      star={"S": "Deployed a real-time notification service that degraded during peak traffic on launch day.",
            "T": "Mitigate downtime immediately and address systemic performance bottlenecks.",
            "A": "Rolled back to stable build, profiled memory leaks in thread pools, and introduced Redis caching with rate limiting.",
            "R": "Service achieved 99.99% uptime during subsequent sales, and we instituted mandatory automated load tests before releases."},
      tags=["Failure", "Resilience", "Ownership"]),

    Q("B", "Describe a time you had to meet a tight or seemingly impossible deadline.",
      "Highlight prioritization, aggressive scope reduction (MoSCoW method: Must have vs Nice to have), proactive stakeholder communication, and avoiding burnout while delivering quality.",
      "Shows composure under pressure, strategic execution, and pragmatic engineering trade-offs.",
      category="behavioural",
      star={"S": "A compliance security feature was required by enterprise clients with only 10 days remaining in the quarter.",
            "T": "Implement OAuth2 role-based authorization without delaying other critical deliverable roadmaps.",
            "A": "Broke requirements into core authentication vs non-critical audit UI, automated tests early, and paired with senior devs.",
            "R": "Shipped MVP 24 hours ahead of deadline with zero regressions; audit UI rolled out in subsequent sprint."},
      tags=["Deadlines", "Execution", "Prioritization"]),

    Q("B", "Tell me about a time you disagreed with your manager or tech lead.",
      "Showcase 'Disagree and Commit' (Amazon Leadership Principle): respectfully voiced concerns backed by evidence, listened openly, and once a decision was finalized, executed with 100% commitment.",
      "Proves you are thoughtful and courageous, but never disruptive or toxic.",
      category="behavioural",
      star={"S": "Tech lead advocated for custom in-house authentication rather than adopting an industry-standard OAuth provider.",
            "T": "Ensure application security and reduce maintenance overhead without undermining leadership.",
            "A": "Compiled a risk-assessment document highlighting long-term patching burdens and compliance liabilities.",
            "R": "Lead agreed to adopt Spring Security with Auth0, saving 3 weeks of custom engineering time."},
      tags=["Leadership", "Disagree and Commit", "Communication"]),

    Q("B", "Why do you want to work at our company specifically?",
      "Do your homework! Connect your personal engineering interests with their exact tech stack, open-source initiatives, recent product launches, or engineering culture.",
      "Avoid generic answers like 'You are a market leader'. Be specific about problems they solve that excite you.",
      category="behavioural",
      star={"S": "Targeting high-scale distributed backend teams tackling real-time latency challenges.",
            "T": "Find a culture that values engineering craftsmanship, rapid iteration, and mentorship.",
            "A": "Researched your engineering blog posts on Kafka streaming pipelines and zero-downtime deployments.",
            "R": "My background in high-concurrency systems makes this the ideal platform to deliver immediate impact."},
      tags=["Culture Fit", "Motivation", "Research"]),

    Q("B", "What is your greatest technical strength and greatest weakness?",
      "Strength: pick a capability that directly impacts team velocity (e.g. system debugging, performance profiling, clean code architecture). Weakness: pick a genuine area of improvement, not a humblebrag ('I work too hard'). Detail active steps you are taking to bridge the gap.",
      "Demonstrates deep self-awareness and active professional growth.",
      category="behavioural",
      star={"S": "Self-assessment across system design, algorithmic efficiency, and front-end state management.",
            "T": "Continuously improve engineering breadth while maintaining deep backend mastery.",
            "A": "Strength: dissecting complex distributed bottlenecks; Weakness: historically hesitant to delegate, now using Kanban WIP limits.",
            "R": "Improved team sprint velocity by 25% by mentoring junior peers on tasks I previously monopolized."},
      tags=["Self-Awareness", "Growth", "Strengths"]),

    Q("I", "Tell me about a time you had to learn a new technology or language on short notice.",
      "Demonstrate learning agility: breaking down the syntax into fundamental paradigms, building tiny proof-of-concept prototypes, reading official documentation, and delivering production-ready code.",
      "In modern tech, adaptability is valued higher than static trivia memorization.",
      category="behavioural",
      star={"S": "Company acquired a Go microservice that required immediate feature additions, but my primary stack was Java.",
            "T": "Onboard and ship a critical payment webhook within 2 weeks.",
            "A": "Mapped Go concurrency (goroutines/channels) to Java Virtual Threads, studied idiomatic Go patterns, and wrote end-to-end tests.",
            "R": "Shipped the webhook on schedule with 100% test coverage and no production incidents."},
      tags=["Learning Agility", "Adaptability", "Polyglot"]),

    Q("B", "Give an example of a time you went above and beyond your assigned responsibilities.",
      "Focus on proactive initiative: fixing broken CI/CD pipelines, writing missing documentation, building an internal developer tool, or resolving technical debt that everyone else ignored.",
      "Highlights leadership, high agency, and organizational ownership.",
      category="behavioural",
      star={"S": "Local development environment setup took new developers 3 full days of manual script executions.",
            "T": "Reduce onboarding friction across the entire engineering department.",
            "A": "Volunteered over a weekend to containerize the development stack with Docker Compose and wrote a one-click setup script.",
            "R": "Onboarding time dropped from 3 days to under 15 minutes, praised by VP of Engineering."},
      tags=["Initiative", "High Agency", "Productivity"]),

    Q("I", "Tell me about a time you made a production mistake or introduced a critical bug.",
      "Admit the incident transparently, explain how you prioritized fast mitigation (rollback / hotfix), and discuss the blameless post-mortem actions you instituted (monitoring, unit tests, canary deployments).",
      "Tests honesty, calmness under fire, and devotion to systemic reliability.",
      category="behavioural",
      star={"S": "Pushed a database migration that omitted a column index, causing query latency to spike to 8 seconds.",
            "T": "Restore database responsiveness immediately during live business hours.",
            "A": "Acknowledged issue in incident Slack channel, added index concurrently without table locks, and stabilized database.",
            "R": "Instituted an automated CI check that requires EXPLAIN ANALYZE validation on all migration PRs."},
      tags=["Mistakes", "Post-Mortem", "Production"]),

    Q("I", "How do you handle ambiguous requirements when product specs are vague?",
      "Showcase proactive inquiry: interviewing stakeholders, writing an architectural design doc (RFC), mapping user personas, identifying edge cases, and proposing an incremental MVP.",
      "Senior engineers navigate ambiguity by creating clarity for the team.",
      category="behavioural",
      star={"S": "Product requested an 'AI-driven search' without specifying latency SLAs, ranking criteria, or fallback behaviors.",
            "T": "Define concrete technical and business requirements before writing code.",
            "A": "Drafted an RFC outlining semantic vs keyword search trade-offs, hosted an alignment session, and created wireframe prototypes.",
            "R": "Aligned stakeholders on hybrid search architecture delivered in 2 phased milestones."},
      tags=["Ambiguity", "RFC", "Product Thinking"]),

    Q("I", "Describe a time you persuaded your team to adopt a new tool or architecture.",
      "Highlight influence without authority: building a small prototype, measuring objective performance metrics, presenting findings respectfully, and offering training support.",
      "Shows technical leadership, communication skills, and data-driven persuasion.",
      category="behavioural",
      star={"S": "Team spent hours debugging fragile manual integration tests in staging environments.",
            "T": "Advocate for adopting Testcontainers for disposable Docker-based integration testing.",
            "A": "Created a working branch demonstrating reproducible Postgres tests running in 30 seconds inside CI/CD.",
            "R": "Team unanimously voted to adopt Testcontainers; test flakiness dropped to virtually zero."},
      tags=["Influence", "Leadership", "Testing"]),

    Q("B", "Tell me about a time you received harsh or critical feedback during a code review.",
      "Demonstrate thick skin, gratitude for critique, separation of self-worth from code, and immediate action to elevate your code craftsmanship.",
      "Reduces concern about defensiveness or toxic reactions in code reviews.",
      category="behavioural",
      star={"S": "A senior architect flagged multiple architectural anti-patterns and lack of concurrency safety in my PR.",
            "T": "Address the critique professionally and elevate the implementation.",
            "A": "Thanked the architect, scheduled a 15-minute pairing session to understand the concurrency subtleties, and refactored the class.",
            "R": "The PR became a reference model for thread-safe service design in our internal wiki."},
      tags=["Feedback", "Code Review", "Humility"]),

    Q("B", "Describe how you prioritize multiple urgent tasks competing for your attention.",
      "Explain your framework: Eisenhower Matrix (Urgent vs Important), evaluating business impact, assessing blast radius, communicating blockers early, and protecting deep-work focus time.",
      "Shows mature time management and reliability under competing demands.",
      category="behavioural",
      star={"S": "Simultaneously assigned a high-priority customer defect, a sprint feature deliverable, and a code review for a blocker PR.",
            "T": "Execute all three responsibilities without dropping quality.",
            "A": "Triaged the defect first (contained blast radius), unblocked the peer's PR with a targeted review, then engaged in focused deep work.",
            "R": "Resolved the defect within SLA, unblocked the release, and delivered sprint goals on time."},
      tags=["Prioritization", "Time Management", "Focus"]),

    Q("I", "Tell me about a time you worked with an underperforming or unresponsive teammate.",
      "Emphasize empathy and curiosity over accusations: checked in privately to see if they were blocked or dealing with personal challenges, offered pairing, and clarified task boundaries.",
      "Shows peer leadership, empathy, and constructive problem-solving.",
      category="behavioural",
      star={"S": "A paired sprint partner was missing daily standup updates and falling behind on API contracts.",
            "T": "Ensure sprint deliverables were met while supporting the colleague.",
            "A": "Reached out via private 1-on-1, discovered they were struggling with Docker networking setup, and spent 45 minutes pairing.",
            "R": "Colleague regained confidence, delivered their endpoints on time, and our team cohesion strengthened."},
      tags=["Empathy", "Teamwork", "Peer Support"]),

    Q("B", "What motivates you in software engineering, and what drains your energy?",
      "Motivators: solving difficult architectural challenges, automating repetitive tasks, seeing real users benefit from software, clean code craftsmanship. Drainers: unaddressed technical debt without a roadmap, lack of automated tests, gatekeeping.",
      "Helps the hiring manager gauge cultural alignment and role fit.",
      category="behavioural",
      star={"S": "Reflecting on 3+ years of building software systems.",
            "T": "Identify conditions where I operate in flow state vs friction.",
            "A": "Thrive in collaborative environments with fast CI/CD feedback loops and clear ownership.",
            "R": "Consistently produce high-velocity, resilient systems when empowered with technical autonomy."},
      tags=["Motivation", "Culture", "Energy"]),

    Q("B", "Where do you see yourself in 3 to 5 years?",
      "Focus on technical growth, architectural leadership, driving engineering excellence, and mentoring junior engineers. Balance ambition with grounding in the role you are applying for.",
      "Reassures the employer that you are committed, ambitious, and looking for sustainable growth.",
      category="behavioural",
      star={"S": "Planning long-term software engineering career progression.",
            "T": "Evolve from a strong individual contributor into a technical lead/staff engineer.",
            "A": "Deepening domain mastery in distributed systems, cloud architecture, and cross-functional team leadership.",
            "R": "Driving major system design initiatives while cultivating an inclusive engineering environment."},
      tags=["Career Goals", "Vision", "Ambition"]),

    Q("I", "Tell me about a time you simplified a complex system or eliminated technical debt.",
      "Highlight recognizing over-engineering: replacing hundreds of lines of brittle custom code with standard library features or clean design patterns.",
      "Great engineers write code; exceptional engineers delete unnecessary code.",
      category="behavioural",
      star={"S": "A legacy order processing service had 14 nested if-else statements with tangled mutations across 2,000 lines.",
            "T": "Refactor the module to enable new payment method integrations without fear of regressions.",
            "A": "Introduced Strategy Pattern and Pipeline architecture, backed by comprehensive characterization tests.",
            "R": "Deleted 1,200 lines of brittle code, reduced bug reports by 60%, and cut onboarding time for new payment methods to 2 hours."},
      tags=["Refactoring", "Clean Code", "Tech Debt"]),

    Q("B", "How do you approach work-life balance and prevent burnout?",
      "Discuss clear boundaries, asynchronous communication, taking active breaks, automated alerting (so you aren't manually checking servers at midnight), and maintaining outside passions.",
      "Demonstrates sustainability, mature habits, and long-term career resilience.",
      category="behavioural",
      star={"S": "Operating in fast-paced startup and enterprise delivery environments.",
            "T": "Maintain high sprint velocity without compromising mental acuity and health.",
            "A": "Enforce strict shutdown routines, configure automated PagerDuty escalation policies, and disconnect during off-hours.",
            "R": "Sustained high performance for consecutive quarters with zero burnout incidents."},
      tags=["Work-Life Balance", "Burnout", "Wellness"]),

    Q("I", "Tell me about a time you mentored an intern, junior developer, or peer.",
      "Showcase patience, Socratic questioning (guiding them to the answer rather than spoon-feeding), celebrating their wins, and creating an environment where no question is considered stupid.",
      "Signals team multiplier potential and readiness for senior responsibilities.",
      category="behavioural",
      star={"S": "An incoming intern was intimidated by the company's multi-repository microservices codebase.",
            "T": "Help the intern ship their first production feature within their first two weeks.",
            "A": "Created a curated architecture walkthrough, set up pair programming sessions, and provided constructive PR feedback.",
            "R": "Intern shipped their feature in 9 days and received a return full-time offer at the end of the summer."},
      tags=["Mentorship", "Leadership", "Multiplier"]),

    Q("I", "Describe a situation where you had to make an architectural decision with incomplete data.",
      "Highlight two-way door vs one-way door decisions (Jeff Bezos framework): if reversible, move quickly and test hypotheses; if irreversible, gather critical boundaries and build abstraction layers.",
      "Proves you can break analysis paralysis and keep engineering momentum moving forward.",
      category="behavioural",
      star={"S": "Needed to choose an event streaming tool before final traffic projections were verified by sales.",
            "T": "Architect a solution that would not lock us into expensive infrastructure if volume stayed modest.",
            "A": "Built an event publisher abstraction interface, initially backed by lightweight Redis streams with easy swap to Kafka.",
            "R": "Shipped on schedule; when traffic surged 10x 6 months later, swapped implementation in 3 days with zero API changes."},
      tags=["Decisions", "Architecture", "Agility"]),

    Q("I", "Tell me about a time you had to advocate for code quality or testing against product pressure.",
      "Show how you framed technical quality in business terms (uptime, customer retention, velocity in future sprints) rather than purely academic purism.",
      "Product managers respect engineers who understand business trade-offs.",
      category="behavioural",
      star={"S": "Product leadership requested skipping automated integration tests to hit an arbitrary marketing launch date.",
            "T": "Protect production stability without stonewalling product goals.",
            "A": "Demonstrated that automated test execution caught 4 critical bugs in the previous sprint that would have caused billing downtime.",
            "R": "Product agreed to allocate 2 days for core happy-path and edge-case integration tests; launch occurred with zero billing glitches."},
      tags=["Quality", "Testing", "Negotiation"]),

    Q("I", "How do you handle scope creep when stakeholders keep adding features mid-sprint?",
      "Explain transparent trade-off discussions: when something is added, something of equal weight must be moved to the backlog to protect sprint integrity and engineer well-being.",
      "Demonstrates boundary management, agile maturity, and professional candor.",
      category="behavioural",
      star={"S": "Stakeholder requested two new dashboard filters during the final week of a two-week sprint.",
            "T": "Accommodate customer value while safeguarding sprint completion.",
            "A": "Walked stakeholder through the sprint capacity burndown chart and negotiated moving two lower-priority tasks to the next sprint.",
            "R": "Stakeholder got their essential filter, sprint completed at 100% velocity, and team avoided frantic overtime."},
      tags=["Scope Creep", "Agile", "Stakeholders"]),

    Q("B", "Tell me about a time you had to deliver bad news to a stakeholder or client.",
      "Key elements: communicate early (no surprises), present facts transparently, take ownership, and bring two viable recovery options with estimated timelines.",
      "Building trust through transparency during difficult moments.",
      category="behavioural",
      star={"S": "Third-party payment gateway migration hit unexpected API deprecation, delaying release by 4 days.",
            "T": "Inform VP of Product immediately rather than hiding the delay until demo day.",
            "A": "Scheduled an emergency briefing with clear explanations, a revised timeline, and a temporary workaround.",
            "R": "Leadership appreciated the proactive communication and client trust was preserved."},
      tags=["Communication", "Transparency", "Stakeholders"]),

    Q("I", "Describe a time you solved a customer pain point directly through a proactive engineering fix.",
      "Focus on customer obsession: analyzing support tickets, observing user friction, and proposing an engineering solution that delighted users.",
      "Demonstrates commercial awareness and pride in end-user experience.",
      category="behavioural",
      star={"S": "Noticed customer support received 50+ tickets per week regarding confusing CSV bulk-upload error messages.",
            "T": "Eliminate support ticket volume and improve user onboarding experience.",
            "A": "Added row-by-row validation with inline error highlighting and downloadable corrected template files.",
            "R": "Upload failure tickets plummeted by 90%, and customer satisfaction scores increased by 18 points."},
      tags=["Customer Obsession", "Product", "Impact"]),

    Q("B", "Why are you looking to leave your current role / looking for your next challenge?",
      "Always stay positive about past employers. Frame the move around seeking greater technical scale, complex architectural challenges, and expanded leadership opportunities.",
      "Never vent or complain about previous managers or workplace politics.",
      category="behavioural",
      star={"S": "Achieved significant milestones and built solid foundations in current role.",
            "T": "Transition to a high-scale platform where I can contribute to mission-critical distributed systems.",
            "A": "Spent months upskilling in high-throughput cloud infrastructure and seeking teams with strong engineering culture.",
            "R": "This opportunity aligns perfectly with my ambition to solve large-scale backend challenges."},
      tags=["Career Transition", "Positivity", "Professionalism"]),

    Q("I", "Tell me about a cross-functional project where you collaborated with Design and Product.",
      "Highlight empathy for non-technical partners, speaking their language (user outcomes, conversion rates, visual hierarchy), and collaborating in tools like Figma.",
      "Proves you are a collaborative partner who breaks down engineering silos.",
      category="behavioural",
      star={"S": "Redesigning the mobile checkout flow with a dedicated UX designer and product manager.",
            "T": "Deliver a frictionless experience within technical mobile web performance constraints.",
            "A": "Attended Figma critiques, suggested subtle animation optimizations that preserved 60 FPS, and built responsive prototypes.",
            "R": "Checkout conversion rate improved by 14% and the design won internal quarterly innovation award."},
      tags=["Cross-Functional", "Design", "Collaboration"]),

    Q("I", "Describe a time you identified a security vulnerability or critical edge case before launch.",
      "Showcase security mindset: threat modeling, considering edge cases, validating untrusted inputs, and preventing potential data leaks.",
      "Demonstrates diligence and respect for customer data privacy.",
      category="behavioural",
      star={"S": "During a pre-launch security code review of a user profile update endpoint.",
            "T": "Ensure no Broken Object Level Authorization (BOLA/IDOR) vulnerabilities existed.",
            "A": "Identified that passing another user's ID in the payload allowed updating their email address; added strict tenant ID checks in Spring Security.",
            "R": "Prevented an IDOR exploit before public launch and added automated security integration tests."},
      tags=["Security", "IDOR", "Code Review"]),

    Q("B", "How do you stay up to date with emerging technologies and AI tools without feeling overwhelmed?",
      "Explain your signal-to-noise filter: curated newsletters (InfoQ, ByteByteGo, Hacker News), building hands-on weekend experiments, and focusing on enduring principles rather than fleeting hype.",
      "Shows structured curiosity and practical technological discernment.",
      category="behavioural",
      star={"S": "The relentless velocity of new AI models, libraries, and cloud frameworks.",
            "T": "Stay cutting-edge while maintaining focus on core production responsibilities.",
            "A": "Dedicate 3 hours weekly to hands-on prototyping and follow architectural deep-dives from engineering blogs.",
            "R": "Successfully integrated LLM code-assistants into team workflows, boosting boilerplate generation speed by 30%."},
      tags=["Continuous Learning", "AI", "Curiosity"]),

    Q("B", "Tell me about a time you worked under a manager whose leadership style differed from yours.",
      "Focus on adaptability: learning their preferred communication style (async Slack vs weekly syncs, high-level summaries vs granular metrics) and establishing mutual alignment.",
      "Demonstrates emotional intelligence, adaptability, and high coachability.",
      category="behavioural",
      star={"S": "New engineering manager preferred detailed bulleted status updates, whereas previous manager was purely hands-off.",
            "T": "Establish trust and smooth working alignment with the new manager.",
            "A": "Adapted by sending a concise 3-bullet Friday recap highlighting completed tasks, in-flight work, and blockers.",
            "R": "Manager expressed high confidence in my autonomy and granted full ownership of major projects."},
      tags=["Management", "Adaptability", "Trust"]),

    Q("I", "Tell me about a time you had to push back on an unreasonable feature request.",
      "Focus on respectful pushback grounded in security, regulatory compliance, or system stability, while proposing an alternative solution that achieved the underlying business goal.",
      "Shows courage to protect the business and customers.",
      category="behavioural",
      star={"S": "Marketing requested storing plain-text user passwords for an automated password-reminder email campaign.",
            "T": "Prevent a catastrophic security vulnerability while addressing marketing's user retention goal.",
            "A": "Explained the security risk and compliance fines (GDPR/SOC2) and proposed an industry-standard magic link password reset flow instead.",
            "R": "Magic link was built in 3 days, securing user accounts and achieving marketing's retention target."},
      tags=["Pushback", "Security", "Ethics"]),

    Q("I", "Describe a time you took ownership of an abandoned repository or unmaintained legacy module.",
      "Highlight courage to tackle messy code: establishing baseline integration tests before modifying code, upgrading dependencies, and documenting system behavior.",
      "Demonstrates extreme ownership, engineering courage, and institutional stewardship.",
      category="behavioural",
      star={"S": "A critical PDF invoice generation service had no maintainer, failing builds, and outdated Java 8 libraries.",
            "T": "Stabilize and modernize the service to prevent customer invoicing outages.",
            "A": "Upgraded dependencies to modern LTS, containerized the build, added automated regression tests, and created a README guide.",
            "R": "Build success reached 100%, invoice processing time was halved, and team members could easily contribute."},
      tags=["Legacy Code", "Ownership", "Modernization"]),

    Q("B", "What would you do in your first 30, 60, and 90 days on our engineering team?",
      "30 Days: Absorb knowledge, learn team processes, configure local environment, ship first small PR, build relationships. 60 Days: Take independent ownership of medium features, participate actively in code reviews, contribute to docs. 90 Days: Drive significant feature deliverables, suggest architectural improvements, mentor newcomers.",
      "Displays structured onboarding methodology and immediate value orientation.",
      category="behavioural",
      star={"S": "Joining a new fast-paced engineering organization.",
            "T": "Deliver rapid value without disrupting ongoing team momentum.",
            "A": "30 days: absorb codebase and ship quick PRs; 60 days: own end-to-end features; 90 days: propose system optimizations.",
            "R": "Provides hiring managers confidence that onboarding will be smooth, self-directed, and high-impact."},
      tags=["30-60-90 Plan", "Onboarding", "Impact"]),

    Q("I", "Tell me about a time you had to pivot your technical approach halfway through implementation.",
      "Demonstrate lack of sunk-cost fallacy: recognized new constraints, evaluated alternatives pragmatically, informed the team, and pivoted smoothly.",
      "Great engineers ditch failing approaches early rather than stubbornly doubling down.",
      category="behavioural",
      star={"S": "Building an in-memory caching layer that exceeded heap limits when tested with simulated 10x production payloads.",
            "T": "Pivot to an external distributed caching mechanism without delaying the launch.",
            "A": "Swapped in-memory Guava cache for Redis cluster with minimal code modifications via a clean Cache interface.",
            "R": "Prevented OutOfMemoryError crashes and delivered scalable caching architecture on time."},
      tags=["Pivot", "Sunk Cost", "Adaptability"]),

    Q("I", "How do you handle constructive disagreement during system design whiteboard sessions?",
      "Showcase objective evaluation: separating ideas from egos, drawing trade-off matrices (latency vs consistency vs cost), and testing assumptions against real business requirements.",
      "Builds a culture of technical rigor without interpersonal animosity.",
      category="behavioural",
      star={"S": "Two senior engineers were deadlocked between synchronous REST microservices vs event-driven Kafka architecture.",
            "T": "Facilitate objective resolution so the design phase could conclude.",
            "A": "Created a decision matrix evaluating throughput requirements, eventual consistency tolerance, and operational complexity.",
            "R": "Matrix showed hybrid approach: synchronous for immediate payment auth, Kafka for downstream fulfillment."},
      tags=["System Design", "Consensus", "Architecture"]),

    Q("I", "Tell me about a time you automated a manual, repetitive business process.",
      "Highlight identifying repetitive toil, calculating time wasted, writing a reliable automation script/pipeline, and measuring hours saved.",
      "Demonstrates automation mindset and respect for engineering efficiency.",
      category="behavioural",
      star={"S": "QA team spent 4 hours every Monday manually seeding test databases with mock customer orders.",
            "T": "Automate database seeding to free up QA engineering capacity.",
            "A": "Wrote a parameterized Python script integrated into GitHub Actions that spins up seeded test databases in 90 seconds.",
            "R": "Saved 16 engineering hours per month and eliminated human errors in test datasets."},
      tags=["Automation", "Efficiency", "DevOps"]),

    Q("I", "Describe an instance where you optimized cloud costs or reduced infrastructure footprint.",
      "Highlight cost-conscious engineering: analyzing AWS/GCP bills, identifying unattached volumes, idle instances, oversized database tiers, or missing cache layers.",
      "Modern companies prize engineers who treat cloud spend with fiduciary responsibility.",
      category="behavioural",
      star={"S": "Monthly cloud infrastructure spending spiked by 35% following a new microservice rollout.",
            "T": "Identify the resource leaks and restore budget compliance.",
            "A": "Profiled CPU/RAM utilization, right-sized Kubernetes resource requests, and set up auto-scaling policies.",
            "R": "Reduced monthly cloud bill by $4,200 while maintaining identical response time SLAs."},
      tags=["Cloud Costs", "Optimization", "FinOps"]),

    Q("B", "Tell me about a time you had to give uncomfortable feedback to a peer or lead.",
      "Demonstrate the SBI framework (Situation, Behavior, Impact): delivered privately, empathetically, focused on observable actions rather than personality attacks, and paired with support.",
      "Shows courage and high interpersonal maturity.",
      category="behavioural",
      star={"S": "A colleague was frequently merging unreviewed PRs directly to the main branch to meet sprint goals.",
            "T": "Address the risk to deployment stability without damaging camaraderie.",
            "A": "Spoke privately over coffee, explaining the risk of unreviewed regressions, and offered to review their PRs within 30 minutes of notification.",
            "R": "Colleague agreed, rogue merges ceased, and production defect rate dropped significantly."},
      tags=["Feedback", "Courage", "Communication"]),

    Q("B", "How do you measure success in an engineering sprint beyond just finishing story points?",
      "Metrics: production defect rates, customer impact, code maintainability, zero rollbacks, team morale, and knowledge sharing (documentation/mentorship).",
      "Proves you value business outcomes over hollow velocity vanity metrics.",
      category="behavioural",
      star={"S": "Evaluating team performance across quarterly sprint cycles.",
            "T": "Move beyond velocity points to assess genuine engineering value.",
            "A": "Tracked DORA metrics: Deployment Frequency, Lead Time for Changes, Change Failure Rate, and Time to Restore Service.",
            "R": "Team reduced Change Failure Rate from 12% to under 2% while improving developer satisfaction."},
      tags=["DORA Metrics", "Agile", "Engineering Excellence"]),

    Q("I", "Tell me about a time you had to debug an issue live in front of a customer or executive.",
      "Showcase emotional composure: acknowledging the situation calmly, relying on structured troubleshooting (logs, metrics, recent deployments), and avoiding panic.",
      "Demonstrates poise, methodical thinking, and leadership under executive pressure.",
      category="behavioural",
      star={"S": "During an executive sales demo, the payment gateway returned a 500 internal server error.",
            "T": "Diagnose the failure immediately without panicking.",
            "A": "Maintained composure, checked CloudWatch logs, spotted an expired sandbox API credential, and renewed the test token in 2 minutes.",
            "R": "Demo proceeded seamlessly, executive praised the quick resolution, and the client signed the enterprise deal."},
      tags=["Poise", "Troubleshooting", "Live Demo"]),

    Q("B", "What do you value most in company culture and engineering team dynamics?",
      "Core values: psychological safety (freedom to ask questions and admit mistakes), blameless post-mortems, rigorous code reviews paired with kind communication, and continuous learning.",
      "Helps determine if your work style matches their organization.",
      category="behavioural",
      star={"S": "Reflecting on high-performing vs dysfunctional team environments.",
            "T": "Contribute to a thriving, high-retention engineering culture.",
            "A": "Promote psychological safety, blameless post-mortems, and celebrate teammates' contributions.",
            "R": "Fosters innovative experimentation and high retention among engineering teammates."},
      tags=["Culture", "Psychological Safety", "Values"]),

    Q("I", "Tell me about a time you had to onboard onto a massive legacy codebase with zero documentation.",
      "Strategy: run tests locally, follow execution flow from API entry point to DB layer, generate architecture diagrams, ask structured batch questions to senior devs, and write docs as you go.",
      "Shows self-reliance and initiative to improve institutional memory.",
      category="behavioural",
      star={"S": "Assigned to maintain a 10-year-old billing application with no documentation and departed original authors.",
            "T": "Understand system behavior and build confidence to make critical fixes.",
            "A": "Traced controller endpoints through service layers, drew sequence diagrams, and wrote characterization tests.",
            "R": "Created the definitive onboarding guide that reduced future dev onboarding time by 70%."},
      tags=["Legacy Systems", "Documentation", "Self-Reliance"]),

    Q("I", "Describe a time you turned down a shortcut to build a scalable, maintainable solution.",
      "Explain the trade-off: short-term hack vs long-term maintainability. Defended proper architecture by illustrating future maintenance tax and fragility.",
      "Shows commitment to software craftsmanship and long-term asset value.",
      category="behavioural",
      star={"S": "Pressured to copy-paste 300 lines of business logic across 4 different service endpoints for a quick release.",
            "T": "Prevent technical debt and duplicate bug surfaces.",
            "A": "Refactored the logic into a reusable shared library with unit tests in just 4 additional hours.",
            "R": "When business rules changed 2 months later, the change required editing 1 central method rather than 4 scattered files."},
      tags=["Craftsmanship", "DRY Principle", "Integrity"]),

    Q("B", "How do you communicate complex technical concepts to non-technical business partners?",
      "Techniques: analogies, diagrams, focusing on business impact (costs, speed, risk) rather than jargon, and validating comprehension with interactive check-ins.",
      "Essential skill for high-impact senior engineering roles.",
      category="behavioural",
      star={"S": "Explaining why the team needed 2 weeks to upgrade PostgreSQL major versions to marketing executives.",
            "T": "Gain stakeholder buy-in without confusing them with database WAL or MVCC terminology.",
            "A": "Used the analogy of changing the foundation of a building to support 5 new floors of features without collapse.",
            "R": "Executives fully approved the maintenance window and praised the clear communication."},
      tags=["Communication", "Analogies", "Stakeholders"]),

    Q("I", "Tell me about a time you had to resolve a deadlock or conflict between two engineering peers.",
      "Acted as a neutral mediator: brought them together, framed the discussion around customer needs, wrote out objective criteria, and helped them find consensus.",
      "Demonstrates high emotional intelligence and servant leadership.",
      category="behavioural",
      star={"S": "Two engineers argued for days on whether to use GraphQL or REST for a new public mobile API.",
            "T": "Unblock the project while preserving healthy peer relationships.",
            "A": "Facilitated a structured workshop listing concrete mobile client network constraints and caching needs.",
            "R": "Team agreed REST satisfied aggressive CDN caching goals, and both engineers shook hands and began coding."},
      tags=["Mediation", "Conflict Resolution", "Leadership"]),

    Q("B", "What is your philosophy on remote work, asynchronous communication, and collaboration?",
      "Keys: over-communicating progress, writing clear PR descriptions and documentation, respecting time zones, using async Loom videos/RFCs, and protecting focus time.",
      "Critical for modern remote and distributed software teams.",
      category="behavioural",
      star={"S": "Working across 4 distinct time zones in a distributed software engineering team.",
            "T": "Maintain high sprint velocity without requiring 8 hours of video meetings daily.",
            "A": "Adopted written design docs, structured pull requests with before/after screenshots, and concise async status updates.",
            "R": "Team delivered all quarterly milestones with minimal meeting fatigue and high developer happiness."},
      tags=["Remote Work", "Async", "Productivity"]),

    Q("I", "Tell me about an open source contribution, hackathon, or side project you built from scratch.",
      "Highlight passion for creation: finding an unsolved itch, architecting the solution, shipping it, and interacting with users or community feedback.",
      "Shows intrinsic passion for software engineering beyond a 9-to-5 paycheck.",
      category="behavioural",
      star={"S": "Noticed students and young engineers lacked an intuitive, interactive way to prepare for interview coding traps.",
            "T": "Build an open-source interactive interview prep hub with runnable code and 3D flashcards.",
            "A": "Built 'GenZ Prep' with in-browser Java execution, JUnit 5 quiz runners, and offline AI tutor.",
            "R": "Received 500+ GitHub stars, hundreds of active daily users, and helped multiple peers land tech offers."},
      tags=["Open Source", "Side Projects", "Passion"]),

    Q("I", "Describe a time you had to balance building features fast vs refactoring technical debt.",
      "Explain the Boy Scout Rule (leave code cleaner than you found it) and allocating a steady 15-20% capacity in each sprint for debt reduction rather than stalling all product work for a full rewrite.",
      "Shows mature engineering balance that leadership loves.",
      category="behavioural",
      star={"S": "Sprint featured 5 new user features while our user service had noticeable tech debt.",
            "T": "Deliver new features while steadily improving core codebase health.",
            "A": "Applied the Boy Scout rule: cleaned up method signatures and added tests in every file touched during feature work.",
            "R": "Shipped all 5 features on time while improving overall test coverage by 8%."},
      tags=["Tech Debt", "Boy Scout Rule", "Balance"]),

    Q("I", "How do you handle stress when a major production outage occurs?",
      "Keys: stay calm, follow the incident response protocol, assign clear roles (Incident Commander, Scribe, Investigators), communicate status updates every 15 minutes, focus on containment first (rollback/isolate) then root cause later.",
      "Shows steady nerves and command under high-stakes production stress.",
      category="behavioural",
      star={"S": "Primary database CPU spiked to 100% on Black Friday, dropping 40% of checkout transactions.",
            "T": "Restore checkout functionality without panicking.",
            "A": "Assumed Incident Commander role, isolated misbehaving analytics query, killed long-running sessions, and restored capacity in 7 minutes.",
            "R": "Prevented estimated $50,000 in lost revenue and conducted a blameless post-mortem that fixed index configurations."},
      tags=["Incident Response", "Production Outage", "Composure"]),

    Q("B", "Do you have any questions for us at the end of the interview?",
      "Top 5 high-impact questions to ask: 1. 'What does success look like for this role in the first 90 days?' 2. 'What is the biggest technical bottleneck currently slowing your engineering velocity?' 3. 'How does the team handle on-call rotations and blameless post-mortems?' 4. 'What surprised you most about the company culture since you joined?' 5. 'What are you most excited about on your technical roadmap for the next year?'",
      "Always ask insightful questions! It demonstrates preparation, engagement, and shows you are interviewing the company as much as they are interviewing you.",
      category="behavioural",
      star={"S": "The closing 10 minutes of an interview.",
            "T": "Leave a lasting impression and evaluate team culture and technical maturity.",
            "A": "Ask targeted questions about engineering velocity, production deployments, and team mentorship.",
            "R": "Provides deep insight into team dynamics and signals strong intellectual curiosity."},
      tags=["Closing", "Candidate Questions", "High Impact"])
]

SECTION = S("Behavioral & HR Interview Questions", "🤝", "Track 3", QUESTIONS,
            desc="50 essential behavioral questions asked in 90%+ of engineering rounds, broken down with the STAR method (Situation, Task, Action, Result) and GenZ career advice.")
