"""Builds ../data.js (window.JAVA_DATA / window.GENZ_DATA) from the 4 tracks:
1. Coding Interview Questions (50 questions)
2. Technical Interview Questions (50 questions)
3. Behavioral & HR Interview Questions (50 questions)
4. Programming & Code Traps (50 questions)
Total: 200 high-yield questions with 90%+ frequency in tech interviews.
"""
import json
from pathlib import Path

import coding_questions
import interview_questions
import behavioural_questions
import programming_questions
from challenges import CHALLENGES, SNIPPETS

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
OUT_ROOT = ROOT / "data.js"


def main():
    sections = [
        coding_questions.SECTION,
        interview_questions.SECTION,
        behavioural_questions.SECTION,
        programming_questions.SECTION
    ]
    qid = 0
    for sid, sec in enumerate(sections, 1):
        sec["id"] = sid
        for q in sec["questions"]:
            qid += 1
            q["id"] = qid
            q["sid"] = sid
            q["stitle"] = sec["title"]
            q["sicon"] = sec["icon"]
            q["sref"] = sec["ref"]

    data = {
        "title": "GenZ Prep · 90% High-Yield Interview Hub",
        "sections": sections,
        "challenges": CHALLENGES,
        "snippets": SNIPPETS
    }

    content = (
        "// Generated by GenZ Prep source/generate_data.py; do not edit by hand.\n"
        f"window.JAVA_DATA = {json.dumps(data, ensure_ascii=False, indent=2)};\n"
        "window.GENZ_DATA = window.JAVA_DATA;\n"
    )

    OUT_ROOT.write_text(content, encoding="utf-8")

    total_q = sum(len(s["questions"]) for s in sections)
    summary_parts = [f"{len(s['questions'])} in {s['title']}" for s in sections]
    print(f"Generated {OUT_ROOT}: {len(sections)} sections, {total_q} questions total "
          f"({', '.join(summary_parts)}), "
          f"{len(CHALLENGES)} challenges, {len(SNIPPETS)} snippets")


if __name__ == "__main__":
    main()
